"""Blueberry 36 #2 — jar file (slug: bb362)."""
from datetime import date, datetime, timezone
from Dabby_Core import *

# ── Waypoint constants (local to this jar) ──
BB36_2_RUN6 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=4, temp_f=400, note='Steep early climb'),
    Waypoint(time_s=8, temp_f=420, note='Endpoint — 8s ramp; up 4°F from baseline'),
    Waypoint(time_s=40, temp_f=420, note='Hold'),
]

# ── Runs (chronological; run numbers assigned positionally by the generator) ──
RUNS = [
    CompletedRun(
        strain='Blueberry 36 #2',
        run_date=date(2026, 5, 31),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 1, 3, 26, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_5,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve',
        swab='Very golden — tad dark; user notes this jar tends toward darker reclaim than its sisters. Generally clean.',
        session_char='2 big draws + 6-second third; no harshness; terp cough. Very wispy vapor throughout. First draw very flavorful and fruity; second less distinct but not unpleasant.',
        intensity='Moderate — creative and chatty energy, body tingling/movement sensations, nothing overpowering.',
        dab_notes="Very golden swabs, I remember this jar seemed to have darker reclaim than its sisters. But generally clean looking, just a tad dark. Two big draws and then a 6 second third. No harshness at all, terp cough though. First draw was really flavorful, lots of fruit but I couldn't pick one out. Second draw less flavorful but not at all unpleasant. Very wispy vapor, wonder if this wants more heat applied. Effects are starting light, some body sensation. I think this one builds over maybe 15 mins. Oh I get a very clear blueberry note much much after taking the dab. It seems to come up my throat too, which is a strange way for something to show up. Moderate intensity — creative and chatty energy, body tingling movement sensations, nothing overpowering.",
        analysis="Run 1 on Rig 5, baseline curve — clean debut. No harshness across two big draws and a 6-second tail. On Rig 5, harshness has entered around draw 3 for FW106 and Watermellos; the short third here didn't trigger it, but 6 seconds is too thin to count as a full draw — treat the pattern as unresolved, not extended. Swab came back very golden — warmer than the beige Rig 5 typically returns on FW106 and Watermellos. User attributed it to the jar's character (darker reclaim than its sisters), which is the right read: within the clean range, swab is a floor indicator, and this isn't a floor signal. The golden does hint at less complete vaporization at this endpoint — consistent with the wispy vapor throughout — but one confounded data point isn't enough to act on. Wispy vapor was the defining session note. FW106 and WM both delivered denser vapor at 416°F on Rig 5; the contrast here may be material character (badder consistency, this phenotype), load size, or a temperature signal. The user's more-heat hypothesis is plausible, not confirmed. Flavor followed the Rig 5 terpene depletion pattern: fruity and distinct on the first draw, falling off sharply on the second — same arc as WM R4 ('big flavor on first draw, flavor was changing by then on second draw'). Retronasal blueberry arriving well after the session — coming up through the throat — is a novel presentation in the log. The blueberry character exists in this material but didn't express in real-time vapor; it released slowly post-session through retronasal olfaction. Whether that's a consistent signature or a first-run anomaly is worth watching. Intensity moderate after a ~15-minute build — creative and chatty energy with body tingling and movement sensations, nothing overpowering. The uplifting, social character is notable for a blueberry lineage strain; worth tracking on future runs to see if it's consistent or session-specific.",
    ),
    CompletedRun(
        strain='Blueberry 36 #2',
        run_date=date(2026, 6, 1),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 1, 22, 34, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_5,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve, repeated from Run 1',
        swab='Dark golden.',
        session_char='First draw very tasty (~20s elapsed); harshness midway through second draw (before terp-load cough, separate phenomena); notably thicker vapor than Run 1; small third draw at 6s remaining, continued drawing into cooldown to ~390°F; post-session throat burning.',
        intensity='Very hard.',
        dab_notes="Very tasty on the first draw that went to 30 seconds left. Just a hint of harshness showed up midway through second draw — harshness noticed before the cough. Didn't see the timer because the harshness coincided with a big terp cough, felt more like a choking sensation than irritation. Second draw had much thicker vapor than the wispy stuff yesterday, that was clear. I took a small third draw at 6 seconds left and kept drawing as it cooled down to 390 ish. The sapphire definitely holds heat longer than quartz. My throat is burning a bit still. Swabs were dark golden. I think the effect from this one is much bigger than yesterday — it's the same curve, so maybe load variation? It hit very hard.",
        analysis="Run 2 on Rig 5, baseline curve repeated. Thicker vapor throughout vs. Run 1's wispy, and intensity stepped up from moderate to very hard — both consistent with a larger load; same curve, so load variation is the most likely driver. Harshness arrived midway through the second draw, confirmed before the terp-load cough, so a real signal. This is earlier than the Rig 5 pattern of harshness entering around draw 3 on FW106 and Watermellos — points either at the load running thin within draw 2 (dense vapor depleting faster) or at 416°F sitting at the edge of the clean zone for this phenotype. Can't distinguish the two from this run alone — load wasn't controlled. Swab came back dark golden, a step darker than Run 1's 'very golden, just a tad dark.' On a larger load, the swab would be expected to run lighter if load quantity were the only variable; darker is a mild directional signal toward temperature rather than depletion, but doesn't rise to a floor signal. Post-session throat burning is consistent with the in-session harshness. Sapphire heat retention observed: continued drawing into cooldown to ~390°F, consistent with the insert's higher thermal mass holding temperature after the session ends.",
    ),
    CompletedRun(
        strain='Blueberry 36 #2',
        run_date=date(2026, 6, 1),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 6, 2, 3, 1, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_5,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve, third run',
        swab='Clean dark gold.',
        session_char='3 draws; very tasty throughout; low-level harshness at end of draw 2, stayed low.',
        intensity='Medium.',
        dab_notes="Swabs were clean and dark gold. 3 draws, very tasty, a little bit of harshness started in end of draw 2. Stayed low level. Medium intensity. Incredible quality and taste — easily as good as any top tier rosin I've had, maybe better.",
        analysis="Harshness at end of draw 2, consistent with Run 2 (midway through draw 2) — draw-2 harshness is now a two-run pattern. Load control was compromised by gooey consistency; load was if anything still larger than normal, so the pre-run condition ('controlled load → temperature signal') doesn't apply cleanly. Load density remains the unresolved variable: both runs with likely-large loads produced draw-2 harshness; Run 1 with wispy vapor and moderate intensity did not. Timing is directionally consistent with the density reading — harshness entered later in draw 2 on Run 3 than Run 2, as vapor density framing would predict if load was modestly smaller. But load isolation as a controlled test is structurally off the table for this jar: gooey consistency makes precise loading impossible in both directions. Temperature step-down remains available as the other lever if needed. Swab dark gold again, matching Run 2; warming character appears phenotype-specific for this jar on Rig 5, not a floor signal. Three draws taken; harshness entered at end of draw 2, not draw 3, so draw count isn't the culprit. Session character note: user rates this among the best rosin they've had — flavor quality is top tier regardless of the harshness question. Run 4 already loaded larger than normal — likely to replicate the pattern. Next deliberate test is Run 5: minimal load at 416°F, going as light as the consistency allows, to probe whether harshness tracks vapor density.",
    ),
    CompletedRun(
        strain='Blueberry 36 #2',
        run_date=date(2026, 6, 2),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 2, 23, 33, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_5,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve; larger-than-normal load',
        swab='Dark gold; lots of reclaim in insert.',
        session_char='3 draws; wispy throughout; first draw ended ~13s in at 404°F (before plateau); second draw tasty, very faint harshness at very end; third draw slightly more density then wispy.',
        intensity='Medium high — creative, chatty; high enough to want to be lounging.',
        dab_notes='Very tasty, first draw ended at 404, please do the math on how many seconds. Second draw stayed tasty and developed harshness at very end, but it was very faint. Seemed wispy again. Third draw little more density then wispy again. Lots of reclaim in insert, dark gold on the swabs. Same great medium high creative chatty effects. High enough I want to be lounging.',
        analysis="Larger-than-normal load, baseline curve, Rig 5, first dab of the day. Prediction from Session 87 was that a larger load would replicate the draw-2 harshness from Runs 2–3; instead, harshness was very faint and only at the very end of draw 2. Wispy vapor throughout and lots of reclaim — but Run 2 (same curve, also larger load) produced explicitly thick vapor and clear harshness, so load size doesn't explain the difference; and wispy has appeared on both Run 1 (likely smaller load) and Run 4, so it doesn't track load size cleanly either. This jar has enough run-to-run variability in vapor density and harshness that the inputs driving any given result are hard to isolate. Swab dark gold, consistent with phenotype character. Intensity medium high, familiar creative-chatty effects.",
    ),
    CompletedRun(
        strain='Blueberry 36 #2',
        run_date=date(2026, 6, 2),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 6, 3, 3, 5, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_5,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve; minimal load',
        swab='Dark golden.',
        session_char='2 draws; slight harshness in draw 2, stayed slight; lots of flavor; wispy vapor; lots of reclaim.',
        intensity='Medium high.',
        dab_notes="I loaded as little as I could. It felt exactly the same as the last run. Dark golden swabs, slight harshness in the second draw that stayed at the slight level. lots of flavor. wispy vapor. lots of reclaim. i'm really wondering if we need faster ramp and higher hold for this strain. medium high intensity",
        analysis='Minimal load, baseline curve, second dab of the day. User\'s own read: "felt exactly the same as Run 4." The run confirms it — dark golden swabs, slight draw-2 harshness staying slight, wispy vapor, lots of reclaim, medium high intensity. Load size did not move the needle: Run 4 (larger-than-normal load) and Run 5 (minimal) produced the same vapor character and harshness profile. The vapor density hypothesis does not explain this jar\'s behavior. Wispy vapor and draw-2 harshness are not load-driven. Dark golden swab with lots of reclaim is consistent across all five runs — phenotype character, not a floor signal.',
    ),
    CompletedRun(
        strain='Blueberry 36 #2',
        run_date=date(2026, 6, 3),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 6, 4, 2, 19, tzinfo=timezone.utc),
        waypoints=BB36_2_RUN6,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s ramp (steeper than baseline); up 4°F from baseline',
        swab='Beige, very clean. Not a lot of reclaim.',
        session_char="Thick vapor from start. Nice flavor. Harshness at end of draw 2, didn't increase much on short draw 3. Never tasted toasted.",
        intensity='Big — second dab of day, after OC (cross-strain switch confound).',
        dab_notes="Swabs were beige, very clean. And not a lot of reclaim. Vapor was thick from the start. Flavor was nice. Harshness at end of second draw, didn't increase a lot on short third draw. Never tasted toasted. Big effect after the OC earlier. I'm feeling rocked right now. Switching strains seems to lead to bigger effect than returning to same strain.",
        analysis="Two variables changed simultaneously — 8s ramp (vs baseline's 20s) and 420°F endpoint (vs 416°F) — so neither can be isolated as the driver. The results shifted clearly on three dimensions: swab went from dark golden on every prior run to beige, reclaim dropped from 'lots' to 'not a lot,' and vapor was thick from the start rather than wispy. All three prior-run patterns reversed in the same direction. The draw-2 harshness persisted — end of second draw, didn't escalate much on a short third — consistent with all five prior runs. No floor signal at 420°F (never tasted toasted). Intensity was big, but this was the second dab after OC on a different strain — the cross-strain confound is the user's own framing, held appropriately loosely.",
    ),
]

# ── Status ──
STATUS = StrainStatus(
    name='Blueberry 36 #2',
    profile_anchor='#bb362-profile',
    next_text='Run 7: repeat 8s ramp to 420°F — confirm Run 6 swab and vapor improvement',
    accent=None,
    slug='bb362',
    info=[
        ('Strain', 'Blueberry 36 #2 (Higher Ground Seed Bank — DJ Short Blueberry lineage unconfirmed despite the name)'),
        ('Provenance', "Pheno #2 of Matt's 4-seed pop — 1 male culled, surviving females jarred as #1, #2, #4"),
        ('Consistency', 'Badder'),
        ('Micron', '90μ'),
        ('Growers', 'Matt & Oliver'),
        ('Washer', 'Three Blind Trichs'),
        ('Nose', 'VERY loud at cold nose; strong grape jam note, very fruity'),
        ('Flavor', "Top-tier — user rates vapor flavor among the best hash rosin they've had"),
    ],
    terpene_note='<strong>Terpene inference:</strong> Myrcene inferred from Blueberry-type character (lineage unconfirmed — Higher Ground Seed Bank, not DJ Short confirmed); caryophyllene and alpha-pinene as secondaries. See <a href="#terpene-ref">Terpene Reference</a>.',
    next_dab_notes="Swabs were beige, very clean. And not a lot of reclaim. Vapor was thick from the start. Flavor was nice. Harshness at end of second draw, didn't increase a lot on short third draw. Never tasted toasted. Big effect after the OC earlier. I'm feeling rocked right now. Switching strains seems to lead to bigger effect than returning to same strain.",
    next_ai_analysis="Repeat this exact curve (8s ramp to 420°F, 40s session) to replicate before isolating variables. The swab shift (dark gold → beige) and vapor density reversal are large signals, but BB36 #2 has documented run-to-run variability — one clean run doesn't close the thread. If Run 7 replicates, then run the baseline 20s ramp at 420°F to separate the endpoint bump from the steeper front end.",
    next_waypoints=BB36_2_RUN6,
    jar_index='',
)
