"""Fire Water #106 — jar file (slug: fw106)."""
from datetime import date, datetime, timezone
from Dabby_Core import *

# ── Waypoint constants (local to this jar) ──
FW106_FASTER = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=4, temp_f=400, note='Steep early climb'),
    Waypoint(time_s=8, temp_f=416, note='Endpoint — 8s to 416°F'),
    Waypoint(time_s=40, temp_f=416, note='Hold — 40s session'),
]
FW106_HOLD_440 = [
    Waypoint(time_s=0, temp_f=440, note='Steady hold — flat 440°F from session open'),
    Waypoint(time_s=40, temp_f=440, note='Endpoint'),
]
FW106_RAMP460_40S = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=5, temp_f=400, note='Fast early climb'),
    Waypoint(time_s=25, temp_f=430, note='Mid ascent'),
    Waypoint(time_s=30, temp_f=430, note='Brief hold at 430°F'),
    Waypoint(time_s=40, temp_f=460, note='Endpoint — programmed; actual peak estimated high 440s (sapphire thermal lag)'),
]
FW106_FASTER_420 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=4, temp_f=400, note='Steep early climb'),
    Waypoint(time_s=8, temp_f=420, note='Endpoint — 8s ramp; up 4°F from operating point'),
    Waypoint(time_s=40, temp_f=420, note='Hold'),
]
FW106_FASTER_420_60S = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=4, temp_f=400, note='Steep early climb'),
    Waypoint(time_s=8, temp_f=420, note='Endpoint — 8s ramp'),
    Waypoint(time_s=60, temp_f=420, note='Hold — extended from 40s'),
]
FW106_FASTER_425_60S = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=4, temp_f=400, note='Steep early climb'),
    Waypoint(time_s=8, temp_f=425, note='Endpoint — 8s ramp; up 5°F from FW106_FASTER_420_60S'),
    Waypoint(time_s=60, temp_f=425, note='Hold'),
]

# ── Runs (chronological; run numbers assigned positionally by the generator) ──
RUNS = [
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 5, 24),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 5, 24, 23, 30, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_4,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve &nbsp;|&nbsp; <strong>Equipment:</strong> Inaugural Rig 4 (sapphire + ruby pearl) run',
        swab='Super clean, very light beige.',
        session_char='Very flavorful throughout; terpene-load cough without heat irritation. Mild harshness entering at ~39s (19s into 416°F hold).',
        intensity='Medium',
        dab_notes='Swabs are super clean, very light beige. Harshness very mild and at roughly 11 seconds left mark. Very flavorful, terpenes obvious from the coughing without harshness.',
        analysis='First run on Rig 4 (sapphire + 5mm ruby pearl). Super clean swab, very flavorful — terpene-load cough without harshness is a strong first-impression character read for FW106. Mild harshness at 19s into the 416°F hold (39s total). Ruby is corundum (same material as the sapphire insert) — ~2x heat capacity and ~20x conductivity over quartz, so despite the smaller diameter the pearl carries comparable thermal mass and delivers heat more uniformly; the full corundum pathway likely runs at a higher effective temperature than sapphire + quartz pearl at the same setpoint. Whether that pushes harshness earlier (denser vapor) or later (material done sooner) is unresolved — needs a same-strain cross-rig comparison to isolate.',
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 5, 24),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 5, 25, 2, 47, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_4,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve, repeated from Run 1',
        swab='Ultra clean, very light beige — same as Run 1.',
        session_char='Harshness entered mild at ~25s (5s into 416°F hold); grew through 2nd draw; nearly unbearable on 3rd draw. Notable bitter citrus note throughout.',
        intensity='Pretty big',
        dab_notes='Same ultra clean light beige. Harshness again very mild, around 25 seconds left. Grew through second and third draws. Third draw it was almost unbearable harshness. Pretty big intensity right now. Notable bitter citrus note throughout.',
        analysis="Run 2 on Rig 4, baseline curve repeated. Swab matched Run 1 — ultra clean, very light beige. Harshness entered notably earlier: ~25s elapsed (5s into the 416°F hold) vs. Run 1's 39s (19s into hold). More significantly, harshness escalated across three draws — mild at entry, grew through the 2nd, nearly unbearable on the 3rd. Run 1 had one mild harshness note at the tail; Run 2 had a three-draw escalation to the edge of tolerance. Two possible mechanisms: (1) airway sensitization — once harshness starts, subsequent draws hit already-irritated tissue and register more intensely; (2) session heat accumulation — the ruby pearl re-equilibrates to 416°F quickly between draws and delivers denser vapor on each successive hit. Both predict the same outcome, so they can't be isolated from this run alone. Draw count wasn't recorded for Run 1, which is the key gap — if Run 1 was a single draw, the difference may be draw-count-driven rather than a temperature shift. Intensity stepped up from Run 1's medium to pretty big, consistent with more complete vaporization across three draws. Notable bitter citrus note throughout — consistent with the cross-strain pattern (MB9ZST R1, MBD R4, OC R12); FW106's Key Limeade lineage makes limonene a plausible carrier, but the same note appears in unrelated strains.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 5, 26),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 5, 26, 20, 23, tzinfo=timezone.utc),
        waypoints=FW106_FASTER,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 416°F — faster ramp (8s), 40s session &nbsp;|&nbsp; <strong>Equipment:</strong> Rig 5 (sapphire + dual ruby pearls)',
        swab='Clean beige.',
        session_char='Very flavorful, 2 draws; tiny bit of harshness at tail of draw 2 (~last 10s). Strong effect, relatively short duration.',
        intensity='Strong, relatively short duration.',
        dab_notes='Swabs were clean beige, tiny bit of harshness at back of second draw, maybe last 10 seconds. Very very tasty, strong effect but relatively short duration.',
        analysis='Run 3 on Rig 5 (sapphire + dual ruby pearls), faster ramp (8s to 416°F vs. baseline\'s 20s), 40s session, 2 draws. Three things changed from Run 2 simultaneously: draw count (3→2), rig (Rig 4→5), and curve shape plus session length (50s→40s). Clean beige swab — consistent with FW106\'s ultra-clean light beige pattern across Runs 1–2 on Rig 4, suggesting swab character reflects the strain, not the rig. Harshness limited to a tiny trace at the tail of draw 2 (~last 10s) — a large improvement over Run 2\'s draw-by-draw escalation to nearly unbearable on draw 3. Draw-count reduction is a plausible factor — Watermellos R4 also showed harshness entering on draw 3; rig and curve changes are unresolved confounds. "Very very tasty" is a flavor step up from Run 1\'s "very flavorful" — the faster ramp may be concentrating first-draw character as observed on Watermellos in the immediately preceding session, but one data point. Strong intensity; relatively short duration — the 40s session (10s shorter than baseline) plausibly contributes.',
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 5, 26),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 5, 26, 22, 30, tzinfo=timezone.utc),
        waypoints=FW106_FASTER,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 416°F — faster ramp (8s), 40s session — repeated from Run 3',
        swab="Light golden — slightly darker than Run 3's clean beige.",
        session_char='Two draws; exhale-only harshness from draw 1, worsened on exhale of draw 2, lingering post-session. Very tasty; bitter citrus in first draw.',
        intensity='Really big.',
        dab_notes="Swabs were light golden slightly darker than last run. Very tasty, got a little bit of the bitter citrus taste in first draw. Harshness showed up on exhale of first drawn, didn't increase with inhale but with exhale of second draw it did. It's lingering now a few minutes later. Effects are really big right now whoot [Beat 2: harshness just on exhale, not on inhale]",
        analysis='Run 4, same setup as Run 3 (FW106_FASTER, Rig 5, 2 draws) — step back from Run 3\'s near-clean result. Exhale-only harshness appeared on draw 1 and worsened on exhale of draw 2, lingering for several minutes after. The exhale-specific pattern is distinct from the inhale-path harshness tracked across strains — this isn\'t hot vapor hitting airways on the way in, but something manifesting on breathout: condensed aerosol re-irritating on exhale, or exhaled vapor hitting already-sensitized tissue. One real confound: Run 3 was the first dab of the day, Run 4 was the second — accumulated exposure from Run 3 could be priming the airways before this session even started. Swab slightly darker than Run 3 (light golden vs. clean beige) — within noise. Intensity "really big," consistent with FW106\'s Rig 5 pattern. Bitter citrus in the first draw — consistent with FW106\'s cross-run character (R2: "notable bitter citrus throughout").',
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 5, 26),
        sessions_prior_today=2,
        utc_logged_at=datetime(2026, 5, 27, 1, 37, tzinfo=timezone.utc),
        waypoints=FW106_HOLD_440,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Setpoint:</strong> 440°F steady (no ramp)',
        swab='Very clean, almost beige.',
        session_char='Three draws, extended past heating cycle into residual insert heat. Harshness at ~28s (12s left in 40s cycle).',
        intensity='Heavy.',
        dab_notes='Very clean almost beige swabs. I set the curve for 40 seconds, and harshness came through around 12 seconds left. But it kept producing thick vapor so I kept hitting it. 3 draws, even went past the heating cycle drawing into the residual heat of the insert. Heaaaaaavy effect.',
        analysis="First run above 416°F for FW106 — flat 440°F hold, 40s, 3 draws with extension into residual heat. Swab came back clean beige, consistent with FW106's light beige pattern across Rig 5 runs; swab is a floor indicator here, not a quality signal. Harshness entered at ~28s — well into the session, not just the tail. That's earlier than FW106's 416°F profile (R3: trace at last ~10s; R4: exhale-only) and consistent with the cross-strain harshness pattern at ≥430°F seen across 7 strains on both ramp and flat-hold shapes. Effect stepped up to heavy — consistent with higher endpoint delivering more complete vaporization. Third dab of the day is a confound for harshness severity perception, but onset timing at ~28s is less sensitive to session order than subjective intensity. 440°F is above FW106's clean zone on current evidence.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 5, 28),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 5, 28, 16, 46, tzinfo=timezone.utc),
        waypoints=FW106_FASTER,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 416°F — faster ramp (8s), 40s session — first-dab isolation test',
        swab='Light golden — more reclaim than typical.',
        session_char='Very flavorful, 2 draws, no harshness.',
        intensity='Highest of the day.',
        dab_notes='2 draws. load was larger. swabs were light golden but more quantity than typical. no harshness and lots of flavor. highest intensity of the day.',
        analysis="First-dab isolation test for the session-order hypothesis from Run 4. Same setup (FW106_FASTER, Rig 5, 2 draws), first dab of the day — no harshness, clean result. Supports session order as the explanation for Run 4's exhale harshness: accumulated airway exposure from Run 3 primed the airways, not a fundamental problem with FW106_FASTER. Larger load with 2 draws produced more reclaim than typical — consistent with more material in the insert at session end, not a floor signal. Highest intensity of the day on the first dab is expected: fresh tolerance, full flavor, clean airways. FW106_FASTER, Rig 5, 2 draws, larger load is clean on this run.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 5, 28),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 5, 28, 19, 0, tzinfo=timezone.utc),
        waypoints=FW106_FASTER,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 416°F — faster ramp (8s), 40s session',
        swab='Clean golden — more reclaim than normal.',
        session_char='3 draws — harsh on draw 3.',
        intensity='Medium, faded quickly.',
        dab_notes='3 draws on a large load. third draw was harsh. swabs were clean golden, more reclaim than normal. intensity was medium, and seemed to fade quickly.',
        analysis='3 draws on a large load, 2nd dab of the day. Harsh on draw 3 — consistent with the draw-3 harshness pattern across Watermellos R4 and FW106 R2. Clean golden swab, more reclaim than normal, consistent with the larger-load pattern seen in Run 6. Medium intensity with quick fade — step down from Run 6, likely session order (2nd dab) plus the harshness on draw 3 cutting the session short.',
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 5, 28),
        sessions_prior_today=2,
        utc_logged_at=datetime(2026, 5, 28, 22, 0, tzinfo=timezone.utc),
        waypoints=FW106_FASTER,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 416°F — faster ramp (8s), 40s session',
        swab='Golden — very little reclaim.',
        session_char='2 draws — harshness midway through draw 2.',
        intensity='Medium, faded quickly.',
        dab_notes='smaller load, 2 draws, golden swabs with very little reclaim, harshness midway through second draw. medium intensity, faded quickly.',
        analysis="2 draws, smaller load, 3rd dab of the day. Harshness midway through draw 2 — the 2-draw ceiling held in principle but the smaller load shifted where within the session harshness arrived. Very little reclaim is the key signal: material was largely spent before draw 2 ended. Once the insert runs low on material, hot-insert-to-vapor contact increases and harshness follows regardless of draw count. Session order (3rd dab) can't be ruled out, but the reclaim data weighs toward load exhaustion. The more precise framing: the harshness ceiling is material depletion, not draw count per se. Draw count is a proxy because more draws deplete the load faster.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 5, 28),
        sessions_prior_today=3,
        utc_logged_at=datetime(2026, 5, 29, 0, 15, tzinfo=timezone.utc),
        waypoints=FW106_FASTER,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 416°F — faster ramp (8s), 40s session',
        swab='Golden — normal reclaim.',
        session_char='4 draws — very harsh on draws 3–4.',
        intensity='High, faded within 90 min.',
        dab_notes='larger load, 4 draws, golden swabs with normal amount of reclaim. very harsh 3-4 draws, high intensity but faded within 90 mins.',
        analysis="4 draws, larger load, 4th dab of the day — both draw count and session order at their daily maximum. Very harsh on draws 3–4, consistent with the draw-count pattern and likely amplified by accumulated daily exposure. Golden swab, normal reclaim on a larger load — expected. High intensity fading within 90 min — FW106's short-duration profile has appeared before (Run 3: 'relatively short duration'); consistent across sessions.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 5, 28),
        sessions_prior_today=4,
        utc_logged_at=datetime(2026, 5, 29, 3, 45, tzinfo=timezone.utc),
        waypoints=FW106_FASTER,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 416°F — faster ramp (8s), 40s session',
        swab='Light golden — lots of reclaim.',
        session_char='Very tasty, 2 draws, no harshness.',
        intensity='Medium.',
        dab_notes='very tasty larger load. 2 draws. no harshness. lots of light gold reclaim on swabs. medium intensity. fell asleep.',
        analysis="2 draws, larger load, 5th dab of the day. No harshness — the 2-draw ceiling held through the final session after maximum accumulated daily exposure. Very tasty, consistent with FW106's flavor character across the log. Lots of light golden reclaim consistent with the larger-load pattern (Runs 6, 7). Medium intensity at the 5th dab of the day is expected. Runs 6 and 10 bookend the day: 2 draws + larger load delivered no harshness first and last, regardless of session order.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 6, 5),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 5, 17, 42, tzinfo=timezone.utc),
        waypoints=FW106_RAMP460_40S,
        equipment=RIG_5,
        too_hot=True,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 460°F programmed — actual peak estimated high 440s (sapphire thermal lag)',
        swab='Light gold — surprisingly light given toasty session character.',
        session_char='Very harsh second draw; big clouds of vapor; heavy coughing. Toasty taste; hot in throat afterward.',
        intensity='Very high.',
        dab_notes='very harsh in second draw, big clouds of vapor, lots of coughing, big effects. Swabs were surprisingly light gold, I would have expected darker. Very tasty! But the coughing is nuts. It was hot and tasted toasty for sure. Definitely hot in that afterward.',
        analysis="First attempt at the 460°F ramp endpoint on Rig 5. The programmed curve arrives at 460°F at exactly 40s — the session terminus, with no hold at that temperature. The sapphire insert's higher thermal mass lagged the programmed setpoint: estimated actual temperature at terminus was in the high 440s rather than 460°F. Despite falling short of 460°F, the session was clearly above the ceiling: toasty taste, harsh second draw, heavy coughing, hot aftermath. The 'toasty' character distinguishes this from terpene-load cough — it's thermal degradation, not vapor overwhelm. Swab came back light gold, consistent with Rig 5's lighter-than-expected swab pattern, but the session character is the operative signal here. Light swab against toasty session is a new combination in the log — sapphire may leave less residue at elevated temperatures even while delivering hot vapor. Very high intensity, consistent with more complete vaporization at higher temperature. Run 12 returned the same result.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 6, 5),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 6, 5, 20, 15, tzinfo=timezone.utc),
        waypoints=FW106_RAMP460_40S,
        equipment=RIG_5,
        too_hot=True,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 460°F programmed — actual peak estimated high 440s (sapphire thermal lag) — same as Run 11',
        swab='Light gold — same as Run 11.',
        session_char='Identical result to Run 11: very harsh second draw, big clouds, heavy coughing, toasty taste, hot afterward.',
        intensity='Very high.',
        dab_notes='Same result as Run 11 — very harsh in second draw, big clouds of vapor, lots of coughing. Very tasty but toasty, hot in throat afterward. Very high intensity.',
        analysis="Same curve, second dab of the day — identical result to Run 11. Two consecutive confirming runs at the high-440s zone on this ramp: above FW106's clean zone on Rig 5. Session order (2nd dab) could amplify harshness perception, but 'toasty' is a flavor signal, not a harshness threshold — consistent with the material reaching above its clean vaporization zone regardless of airway sensitization. The ramp-to-460°F experiment is closed on Rig 5: the sapphire can't reach the programmed 460°F at the 40s terminus, and the high 440s it does reach is above the ceiling.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 6, 5),
        sessions_prior_today=2,
        utc_logged_at=datetime(2026, 6, 6, 0, 45, tzinfo=timezone.utc),
        waypoints=FW106_FASTER_420,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s ramp; up 4°F from operating point',
        swab='Beige.',
        session_char='Very tasty; hot at end of draw 3.',
        intensity='Medium-high.',
        dab_notes='beige looking swabs. Very tasty. Got hot at the end but I recommend re-running this one again. 3 draws, medium high intensity.',
        analysis="Stepped back to the fast ramp shape at 420°F (8s to endpoint, 40s session) — same curve shape as FW106_FASTER but endpoint raised 4°F from the operating point. Beige swab, consistent with Rig 5's FW106 pattern. Very tasty — full flavor recovery after Runs 11–12's toasty character. Three draws with hot character at the end of draw 3, consistent with the depletion pattern: 2-draw ceiling on Rig 5 at these temperatures, draw 3 triggers harshness. Tail harshness is consistent with the depletion pattern rather than an endpoint signal, though session order (third dab) is an unresolved confound. Intensity medium-high on the third dab of the day. The contrast with Runs 11–12 is the key read: same rig, same session day — 420°F fast ramp was very tasty in the clean zone; high 440s was not. Worth confirming at 2 draws to separate draw count from the endpoint bump.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 6, 7),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 8, 1, 50, tzinfo=timezone.utc),
        waypoints=FW106_FASTER_420,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s ramp; same as Run 13',
        swab='Very beige, lots of reclaim.',
        session_char='Two draws; very tasty throughout; harshness in throat at 5s left. Strong, with paranoia and somatic effects coming on.',
        intensity='Strong',
        dab_notes="Very beige swabs with lots reclaim. I think I loaded too much, but it's kind of gooey. Very tasty throughout, harshness in throat at 5 sec left. Effects feel pretty intense right now. Paranoia and somatic stuff coming on. Hypothesis: harshness is some sort of heat accumulation in the throat — this has been my experience. Not just building over a run — building over a longer timeframe.",
        analysis="First dab of the day, 2 draws — session-order and draw-count confounds are clean. The load went on heavy and gooey; the swab came back very beige with lots of reclaim, so material remained at session end and depletion is out — the load wasn't spent. Harshness at 5s left, with material to spare and only 2 draws, therefore doesn't fit the depletion/draw-count pattern of Runs 7 and 13. The user suggests harshness is heat accumulation in the throat that builds not just within a session but over a longer multi-day timeframe — backed by cross-run experience. This maps to and extends the airway/thermal-dose hypothesis open in the methodology, which to date has only been framed within-day (session-order escalation, e.g. FW106 R4/R9). Notably this was a first dab of the day yet still got harsh at the tail — under within-day accumulation alone the first dab should read cleanest, so the residual harshness is mild directional support for the longer-timeframe framing, though the heavy load (vapor density) is an unresolved confound. Logged as a directional signal, not a settled mechanism. Effects strong with paranoia and somatic onset.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 6, 8),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 9, 1, 0, tzinfo=timezone.utc),
        waypoints=FW106_FASTER_420,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s ramp; same as Runs 13–14 &nbsp;|&nbsp; <strong>Note:</strong> Second heating cycle added',
        swab='Beige, lots of reclaim.',
        session_char='Tiny hint of harshness at ~7s left on first cycle — ran second heating cycle, two more draws, still lots of reclaim. Very tasty throughout. Very very intense, uplifting, euphoric.',
        intensity='Very Strong',
        dab_notes='Beige swabs, lots of reclaim. Tiny hint of harshness around 7 seconds left, very minor — ran a second heating cycle and had two more draws. Still got a lot of reclaim after second cycle. Really tasty. Very very intense, uplifting, euphoric. Load was bigger than normal — consistency made it hard to load a normal amount.',
        analysis='Heavy load again (gooey consistency), same conditions as Run 14: first dab of the day, same curve. The contrast is notable — Run 14 had clear harshness at 5s left; Run 15 had a barely-there hint at 7s, and 7s aligns with depletion territory (4 draws across a 40s session plus a second cycle means the material was nearly gone by then). The tiny harshness in Run 15 reads as depletion-edge rather than the load-in-excess harshness of Run 14. Second cycle worked: heavy load left enough residual for two more draws and still produced reclaim, consistent with the material density. Run-to-run variance between 14 and 15 at the same conditions is real — the gooey consistency likely means load geometry and placement vary even when portion size is similar. 420°F 8s ramp is performing well in its best showing on this curve. Effects strongest on record — very very intense, uplifting, euphoric.',
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 6, 12),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 12, 23, 42, tzinfo=timezone.utc),
        waypoints=FW106_FASTER_420_60S,
        equipment=RIG_4,
        duration_seconds=60,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s ramp; 60s hold &nbsp;|&nbsp; <strong>Note:</strong> Rig 4 (single pearl); second cycle added',
        swab='Dark golden, heavy reclaim.',
        session_char='Single crackle first draw (water residue from cleaning — one drop, not persistent). First draw smooth and tasty, but wispy. Within-draw pattern every draw: thick vapor at draw start → wispy through draw. Harshness building across draws. Second cycle added, waited for 420°F — same within-draw pattern. Short draws until harshness said stop.',
        intensity='High',
        dab_notes="I confounded the hell out of that run. The part that worked was first cycle first draw, smooth, tasty. The taste to my recollection faded a bit maybe over time in the fridge — makes me wonder about the humidity environment in my fridge where I'm keeping this stuff. There was also a faint crackle and pop — only one crackle in the first draw, never heard again, probably from water left over from the cleaning I had just done to the entire rig. Wispy vapor in that first draw though. Each following draw had the pattern of thicker vapor at first part of draw and then wispy over the length of the draw. This kept going through the rest of the cycle regardless of number of draws. And the harshness was building up. I ran another cycle and waited for it to get to 420 before I drew on it and it was still doing it. Hit it short draws until the harshness warned me off. Swabs were dark golden, surprising amount of reclaim. I was sure I loaded on the normal side. I got as normal a load size as possible with the runny consistency. Pretty stoned. Chatty, creative, some body tension. High intensity.",
        analysis="Run 16 is the first FW106 run on Rig 4 since Runs 1–2 (May 24, at 416°F baseline), and the first at 420°F on Rig 4. The handoff plan was to isolate load size, but the rig changed simultaneously — load and equipment changed together, so neither can be cleanly attributed to the results. The defining observation is the within-draw vapor pattern: thick at draw start, wispy through the length of the draw, consistently every draw across both cycles. This hasn't appeared in FW106's prior history on Rig 5. Most parsimonious explanation is single-pearl thermal behavior: one ruby pearl loses heat faster under convective and vaporization cooling during a draw than two can sustain. At draw start the pearl is at setpoint → dense vapor; by mid-draw the pearl has shed heat below effective vaporization temperature → vapor thins. Rig 5's dual pearl provides more thermal capacity to hold temperature through the full draw. Dark golden swab and heavy reclaim follow from the same mechanism: less efficient per-draw vaporization means more material condenses as reclaim rather than being inhaled. FW106 on Rig 5 consistently runs beige; Runs 1–2 on Rig 4 at 416°F baseline ran ultra-clean — the dark golden here may reflect the 8s fast ramp (peak thermal demand concentrated in the first 8 seconds) combined with reduced pearl support. Runny load geometry is an unresolved confound throughout. Harshness building across draws with heavy reclaim rules out depletion. Consistent with accumulated airway exposure across a multi-draw session. Effect landed high — chatty, creative, body tension — despite the suboptimal vaporization pattern. One run; rig and load changed simultaneously. Within-draw thinning is directional for the single-pearl hypothesis, not established.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 6, 12),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 6, 13, 3, 30, tzinfo=timezone.utc),
        waypoints=FW106_FASTER_420_60S,
        equipment=RIG_5,
        duration_seconds=60,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s ramp; 60s hold &nbsp;|&nbsp; <strong>Note:</strong> Rig 5; same curve as Run 16 (Rig 4)',
        swab='Dark golden.',
        intensity='High',
        dab_notes='I could taste some lime notes maybe.',
        analysis="Run 17 on Rig 5 (dual pearl), matching Run 16's curve exactly — 8s ramp to 420°F, 60s hold. Dark golden swab is consistent with Run 16's, making this the first same-curve, same-duration cross-rig swab comparison: swab stayed dark golden across the Rig 4→Rig 5 swap, consistent with swab tracking material rather than rig. Session character wasn't captured this run, so the within-draw thick-to-wispy question from Run 16 remains open. Lime note is consistent with Key Limeade lineage (limonene inferred); single-session flavor observations are noisy.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 6, 15),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 15, 22, 2, tzinfo=timezone.utc),
        waypoints=FW106_FASTER_425_60S,
        equipment=RIG_5,
        duration_seconds=60,
        endpoint_note='<strong>Endpoint:</strong> 425°F — 8s ramp; up 5°F from operating point &nbsp;|&nbsp; <strong>Note:</strong> Second cycle added',
        swab='Golden with amber spots — more amber than golden.',
        session_char='Short draw technique; tasty first few draws, flavor faded. Very little harshness in back quarter of first cycle. Visible within-draw density drop throughout first cycle. Second cycle: vapor density held longer, more harshness.',
        intensity='Quite high.',
        dab_notes='Used the short draw technique from yesterday. Tasty first few draws, then it faded. Very very little harshness but in the back quarter. Lots of vapor but it was visible wispy intra draw. Ran a second cycle and the vapor density held up longer for some reason. But also the harshness. So there\'s a possible connection between density and harshness. Swabs were golden with amber spots, more amber spots though. Each cycle was 60 seconds. Intensity is quite high!',
        analysis="Deviated from the planned 420°F pearl-count isolation test in favor of 425°F — Rig 4 vs. Rig 5 same-endpoint comparison is still open. The within-draw wispy pattern appeared at 425°F on Rig 5, which puts FW106 in direct contradiction with LHBH Run 2 and papzp22 Run 2, both of which resolved the density drop at exactly this endpoint on the same rig. Short draw technique is a plausible confound — shorter draws sample the early-draw dense phase more than the wispy tail — but 'visible wispy intra-draw' suggests the pattern was legible regardless. More likely this is material-specific: FW106's vapor density at this endpoint drops off faster within a draw than LHBH or papzp22 did. The second cycle is the more interesting data point: density held up longer, but harshness increased. The insert was already at temperature when the second cycle started, eliminating the cold-ramp phase and delivering sustained heat from the first draw — more sustained density, more harshness. The sequencing is the cleanest within-session evidence for the vapor density hypothesis yet: same material, same rig, same endpoint, more density in cycle two, more harshness in cycle two. Accumulated airway exposure across two cycles is an unresolved confound — 'denser vapor caused the harshness' and 'second cycle, airways already worked' predict the same outcome. Swab came back golden with more amber than golden — darker than FW106's typical Rig 5 beige on 40s runs, consistent with Run 17's dark golden at the same 60s duration. Duration looks like the swab driver on this strain: 40s runs at 420°F ran consistently beige; 60s runs at 420°F (Run 17) and 425°F (Run 18) both show darker results.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 6, 15),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 6, 16, 0, 21, 12, tzinfo=timezone.utc),
        waypoints=FW106_FASTER_425_60S,
        equipment=RIG_5,
        duration_seconds=56,
        endpoint_note='<strong>Endpoint:</strong> 425°F — 8s ramp; 60s hold &nbsp;|&nbsp; <strong>Note:</strong> Normal draws; stopped 4s early',
        swab='Golden.',
        session_char='Three draws, single cycle; draw 1 no harshness, tasty, decent density; draw 2 no taste, slight harshness, lots of density; draw 3 lots of harshness, lots of density — stopped 4s early.',
        intensity='Very hard.',
        dab_notes="Three draws in a single cycle. First one no harshness, tasty, decent amount of vapor density. Second one, no taste, slight harshness, lots of density, third one lots of harshness lots of density. I stopped with 4 seconds left cause too harsh. Didn't notice intra draw, wasn't even looking. When I exhaled it was a LOT of visible vapor. Couple theories: it matters how hard I draw, and/or the pearl's thermal mass and the circumference of the insert versus velocity of the pearls spinning is in the equation. Swabs golden, hit very hard.",
        analysis="Run 19: 425°F, 8s ramp, 60s hold, Rig 5, normal draws, single cycle — 3 draws, stopped 4s early. Harshness escalated draw-by-draw: none on 1, slight on 2, lots on 3, with density present throughout all three. The stopping condition was harshness, not depletion — dense vapor was still coming when bailing. That pairing — dense vapor and lots of harshness on the same draw — is the clearest same-session evidence yet that density and harshness are traveling together at 425°F on Rig 5. Consistent with Run 18's second-cycle finding (pre-warmed insert, sustained density, more harshness), but now confirmed without the cross-cycle confound. Within-draw thinning question unresolved — user wasn't tracking it, but visible exhaled vapor suggests material was making it through. Taste faded after draw 1 despite density remaining through draw 3; first time that sequence is legible in FW106's log — terpene fraction possibly exhausting before cannabinoid fraction, or palate saturation. Swab golden, consistent with the 60s duration pattern (R17–R18 also dark; 40s runs consistently beige). Second dab of the day is a confound for harshness severity; the draw-1 clean result is the least confounded read. Draw velocity noted as an uncontrolled variable — draw effort affects both convective cooling rate and pearl spin rate; not tracked across runs.",
    ),
    CompletedRun(
        strain='Fire Water #106',
        run_date=date(2026, 6, 17),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 18, 0, 47, tzinfo=timezone.utc),
        waypoints=FW106_FASTER_425_60S,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Endpoint:</strong> 425°F — 8s ramp; 60s hold &nbsp;|&nbsp; <strong>Equipment:</strong> Inaugural Rig 6 (Wym Stick Piston joystick, no pearls)',
        swab='Dark golden, ordinary reclaim.',
        session_char='Four draws, full 60s; massive vapor density throughout. Harshness entered on draw 2, escalated through draw 4. Stopped on harshness — dense vapor still present at close.',
        intensity='Very hard.',
        dab_notes="Swabs were dark golden, ordinary amount reclaim. Joystick hits hard as fuck, so much harder than the spinner. This wasn't me misremembering, Claude. Harshness present earlier in the cycle than we expect, like second draw. And stayed, and got heavier. But holy shit was it dense. Full 60 seconds, Paige says it was 4 draws. It was still super dense when I stopped, I could have kept going but it was too harsh. I think this material has a larger particle size in it because it supports particle accumulation theory.",
        analysis="Run 20 on Rig 6 (inaugural — sapphire + Wym Stick Piston joystick, no pearls): massive intensity step-up from Rig 5 at the same endpoint and curve — first dab of the day, user confirmed not misremembering. Dense vapor throughout all 60s with material clearly present at close; dark golden swab consistent with the 60s duration pattern (all 60s runs dark golden; all 40s runs beige). Harshness arrived on draw 2 — one draw earlier than Rig 5's draw-3 pattern across Runs 18–19 at the same endpoint — and escalated through draw 4. Stopping condition was harshness, not depletion: dense vapor still coming at 60s. Density-harshness pairing holds: high vapor density and escalating harshness co-present throughout, not sequential. Earlier draw-2 onset relative to Rig 5 is consistent with higher per-draw efficiency on the Piston — if the joystick delivers more material per draw, the harshness threshold crosses one draw earlier for the same reason intensity is higher: more complete vaporization per draw. Dark golden swab matches all prior 60s FW106 runs (R17, R18) regardless of rig — duration remains the most parsimonious swab driver, not rig configuration. User proposed particle accumulation as a contributing mechanism: larger aerosol particles deposit in upper airways causing harshness independent of temperature — plausible aerosol physics, distinct from the three existing hypotheses (vapor density, heat exposure, airway sensitization), untestable with current setup. Captured as user-suggested at single-data-point weight.",
    ),
]

# ── Status ──
STATUS = StrainStatus(
    name='Fire Water #106',
    profile_anchor='#fw106-profile',
    next_text='Run 21: 420°F on Rig 6, 60s — test whether joystick efficiency delivers comparable intensity at lower endpoint without draw-2 harshness',
    accent=None,
    slug='fw106',
    info=[
        ('Strain', 'Fire Water #106 (Firewood × Key Limeade — Umami Seed Co., seed hunted)'),
        ('Consistency', 'Cold cure badder'),
        ('Producer', '710 Labs'),
        ('Nose', 'Prominent berry; gassy underneath'),
    ],
    terpene_note='<strong>Terpene inference:</strong> Limonene inferred from Key Limeade lineage (citrus character); caryophyllene inferred secondary, consistent with gassy nose; myrcene inferred (earthy, berry character); linalool minor — possible berry note contributor. Firewood parent not well-documented; inferences lean on Key Limeade side. Not measured. See <a href="#terpene-ref">Terpene Reference</a>.',
    next_dab_notes='',
    next_ai_analysis="Rig 6 delivers significantly more intensity than Rig 5 at 425°F, with harshness arriving one draw earlier. The efficiency advantage is real. Two directions: (1) drop to 420°F on Rig 6 — if the joystick advantage carries, you may get Rig 5's 425°F intensity at the lower endpoint, potentially without draw-2 harshness; this tests whether the endpoint map shifts on Rig 6. (2) 2-draw limit at 425°F to test whether draw discipline holds harshness off. Option 1 is recommended — it probes whether the joystick reshapes the working range for this strain.",
    next_waypoints=FW106_FASTER_420_60S,
    jar_index='',
)
