"""The Hive #1 — jar file (slug: hive1)."""
from datetime import date, datetime, timezone
from Dabby_Core import *

# ── Waypoint constants (local to this jar) ──
HIVE1_RUN1 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=15, temp_f=390, note='Early ascent'),
    Waypoint(time_s=35, temp_f=410, note='Mid ascent'),
    Waypoint(time_s=65, temp_f=440, note='Endpoint'),
]
HIVE1_RUN2 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=15, temp_f=390, note='Early ascent'),
    Waypoint(time_s=35, temp_f=410, note='Mid ascent'),
    Waypoint(time_s=65, temp_f=440, note='Endpoint — repeated from Run 1'),
]
HIVE1_RUN3 = [
    Waypoint(time_s=0, temp_f=430, note='Steady hold — flat 430°F from session open'),
    Waypoint(time_s=45, temp_f=430, note='Endpoint'),
]
HIVE1_RUN4 = [
    Waypoint(time_s=0, temp_f=430, note='Steady hold — flat 430°F from session open'),
    Waypoint(time_s=60, temp_f=430, note="Endpoint — extended from Run 3's 45s"),
]
HIVE1_RUN5 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=15, temp_f=390, note='Early ascent'),
    Waypoint(time_s=35, temp_f=410, note='Mid ascent'),
    Waypoint(time_s=65, temp_f=430, note='Endpoint — 430°F with ramp (down from 440°F in Runs 1–2)'),
]
HIVE1_NEXT = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=4, temp_f=400, note='Steep early climb'),
    Waypoint(time_s=8, temp_f=425, note='Endpoint — up 5°F from baseline'),
    Waypoint(time_s=60, temp_f=425, note='Hold'),
]
HIVE1_DESCENT_GENTLE = [
    Waypoint(time_s=0,  temp_f=440, note='Session open — hot open, gentle descent start'),
    Waypoint(time_s=30, temp_f=420, note='Gentle descent midpoint'),
    Waypoint(time_s=60, temp_f=400, note='Floor'),
]

# ── Runs (chronological; run numbers assigned positionally by the generator) ──
RUNS = [
    CompletedRun(
        strain='The Hive #1',
        run_date=date(2026, 5, 7),
        sessions_prior_today=0,
        utc_logged_at=None,
        waypoints=HIVE1_RUN1,
        equipment=RIG_1,
        endpoint_note='<strong>Endpoint:</strong> 440°F',
        swab='Light golden — clean. No darkening.',
        session_char='Nice flavors on the way up through the arc. Heavy indica effect.',
        analysis='Clean swab on first run — curve appears well-matched to this material. Repeated as Run 2 to confirm.',
    ),
    CompletedRun(
        strain='The Hive #1',
        run_date=date(2026, 5, 7),
        sessions_prior_today=1,
        utc_logged_at=None,
        waypoints=HIVE1_RUN2,
        equipment=RIG_1,
        endpoint_note='<strong>Endpoint:</strong> 440°F — identical to Run 1',
        swab='Very light — cleaner than Run 1.',
        session_char='Really nice. Consistent with Run 1.',
        analysis='Two clean runs, consistent character, swab lighter on repeat. 440°F endpoint may be higher than needed — material is fully expressing before the endpoint. Run 3: trying steady 430°F flat hold (no ramp) to test whether curve shape affects the result.',
    ),
    CompletedRun(
        strain='The Hive #1',
        run_date=date(2026, 5, 8),
        sessions_prior_today=0,
        utc_logged_at=None,
        waypoints=HIVE1_RUN3,
        equipment=RIG_1,
        duration_seconds=45,
        endpoint_note='<strong>Setpoint:</strong> 430°F steady (no ramp)',
        swab='Light golden — clean.',
        session_char='First half: lots of flavor, low throat irritation. Second half: irritation increased, flavor faded to generic dab vapor — never harsh or burnt, just less distinct. Effect notably strong.',
        analysis='At a flat 430°F from the open, all terpene fractions (pinene through linalool, all below 430°F) are available simultaneously — first hit may be the full palette combining at once rather than staged. The ramp climbs through each fraction sequentially, which may be what gives those runs more distinct flavor progression across the arc. 45 seconds was too short — vapor was still producing at session end. Not a temperature issue, just cut off early. One data point. Directionally supports the ramp producing more distinct staged flavor vs. the flat hold combining everything at once. If revisiting the flat hold, extend to 60 seconds. Next planned: repeat the Run 1–2 ramp (380→390→410°F) with 430°F endpoint to compare directly on the same endpoint.',
    ),
    CompletedRun(
        strain='The Hive #1',
        run_date=date(2026, 5, 8),
        sessions_prior_today=1,
        utc_logged_at=None,
        waypoints=HIVE1_RUN4,
        equipment=RIG_1,
        duration_seconds=60,
        endpoint_note="<strong>Setpoint:</strong> 430°F steady (no ramp) — extended from Run 3's 45s",
        swab='Light golden — clean. Consistent with Run 3.',
        session_char='Similar to Run 3. Extended hold confirmed vapor was still producing at 45s in Run 3 — 60s felt more complete.',
        analysis='Two flat-hold data points, both clean swabs, consistent character. Next: ramp to 430°F endpoint (380→390→410→430°F) — the original planned experiment — to compare curve shape on the same endpoint.',
    ),
    CompletedRun(
        strain='The Hive #1',
        run_date=date(2026, 5, 8),
        sessions_prior_today=2,
        utc_logged_at=None,
        waypoints=HIVE1_RUN5,
        equipment=RIG_1,
        endpoint_note='<strong>Endpoint:</strong> 430°F (ramp — same shape as Runs 1–2, endpoint reduced from 440°F)',
        swab='Light golden — a tad lighter than the flat-hold 430°F runs (Runs 3–4). Clean.',
        session_char='Nice distinct flavors through the first two-thirds. Harsh in the last ~10 seconds. Effects quite potent.',
        extra_rows=[
            ('Next:', 'Try 420–425°F endpoint on Run 6. Keep ramp shape unchanged.'),
        ],
        analysis='Distinct staged flavor character is consistent with the ramp — each terpene fraction vaporizes as the curve climbs through it, rather than all at once as in the flat hold. Swab difference vs. Runs 3–4 is within noise (too many uncontrolled variables). Harshness at session tail is a directional signal that 430°F may still be slightly above ideal for this material on the ramp.',
    ),
    CompletedRun(
        strain='The Hive #1',
        run_date=date(2026, 6, 19),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 19, 19, 28, 13, tzinfo=timezone.utc),
        waypoints=BASELINE_CURVE,
        equipment=RIG_6,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s ramp; first run on Rig 6',
        swab='Beige — clean.',
        session_char='Dense vapor throughout to ~50s depletion. Harshness entered at ~43s with vapor still dense; water at 43s resolved it; next draw through active vapor clean; depletion signal (vapor drop visible through glass) at end of that draw; two post-depletion draws confirmed no harshness. Very intense. Chatty, creative, uplifting.',
        dab_notes='I was reminded what incredible quality this jar is. The rosin is so incredibly clean. Swabs were beige. Harshness showed up with 17 seconds left. A drink of water and it went away. Maybe a support for particulate accumulation? Very nice very intense high. Feels like the chatty creative and uplifting energy I wanted. Vapor was still dense when harshness showed up, but the material was depleted before the end of 60 seconds, I\'d guess around the 50 second mark. That may be why the harshness resolved, the material ran out so no more particles. Next draw had dense vapor and right at the end of draw showed depletion in drop in vapor observed through stock glass.',
        analysis='First run on Rig 6, first run on sapphire for this jar — all five prior runs were on Rig 1 quartz. Beige swab consistent with this strain\'s historical light-golden-to-very-light pattern and with Rig 6\'s documented efficient vaporization. Harshness entered at ~43s with dense vapor and material still present. User drank water; next draw through active dense vapor was clean — harshness did not return. Depletion signal (vapor drop visible through glass) appeared at end of that draw; two subsequent draws of hot air produced no harshness, consistent with Session 106 (hot air alone at 420°F does not cause harshness). Whatever water reset — particulate load, mucosal sensitization, or thermal sensitization — it held through the remaining material exposure. Mechanism remains open. User notes this as possible support for more percolating glass — more water contact in the vapor path could filter particles before they reach the airway, potentially delaying harshness onset. Tradeoff: more percolation also strips desirable compounds alongside particles. Effects — chatty, creative, uplifting, very intense — matched the occasion and the strain\'s terpene inference exactly.',
    ),
    CompletedRun(
        strain='The Hive #1',
        run_date=date(2026, 6, 19),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 6, 19, 22, 42, 22, tzinfo=timezone.utc),
        waypoints=BASELINE_CURVE,
        equipment=RIG_6,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s ramp; repeat of Run 6 curve',
        swab='Beige — clean.',
        session_char='Clean throughout, no harshness, full 60s. Proactive water sip mid-session. Vapor wispy in last 2. Medium intensity.',
        dab_notes='Cold nose has a floral note on jar today. Super clean run. No harshness with a sip of water in the middle — just a proactive sip. Finished whole 60 seconds, saw vapor wispiness in last 2.',
        analysis='Run 7 on Rig 6 at 420°F — clean throughout, full 60s, no harshness. Beige swab consistent with Run 6 and this jar\'s history. Water sip was proactive, not reactive — the clean outcome stands on its own without water as an intervention. Vapor wispy in the last 2 (seconds or draws — reported ambiguously) is consistent with depletion near session end, parallel to Run 6\'s ~50s depletion signal. Two runs at 420°F on Rig 6 now give opposite harshness outcomes: Run 6 had harshness at ~43s (first dab, very intense); Run 7 was clean to 60s (second dab, medium intensity). Session order goes the wrong direction to explain it — second dab should accumulate more airway exposure, not less. The intensity gap is the live confound: medium vs. very intense suggests Run 7 may have been a lighter load, and lower vapor density may have kept the harshness threshold uncrossed throughout. Pre-session cold nose note (floral) logged; different character from prior spice-forward descriptions, consistent with the jar continuing to develop in the fridge.',
    ),
    CompletedRun(
        strain='The Hive #1',
        run_date=date(2026, 6, 20),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 20, 23, 1, 34, tzinfo=timezone.utc),
        waypoints=BASELINE_CURVE,
        equipment=RIG_6,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s ramp; second cycle (1 draw); first dab of day, larger load',
        swab='Golden — second cycle (one draw) attributed as driver; beige expected without it.',
        session_char='Very little harshness late in draw 2 (~30s remaining), never escalated. Heavy terpene-load coughing throughout. Mildew, fruitiness, and savory/cheese notes in early draws. Second cycle: one draw. Medium-high intensity, still building post-session.',
        dab_notes='Swabs golden but I did run 1 draws worth of a second cycle so darker makes some sense. Very little harshness, which showed up late in the second draw, maybe 30 seconds left. I didn\'t have water handy but through the rest of the draws it never really increased. Flavor in first couple draws had that mildew quality, also some fruitiness, and maybe something savory? Cheese? It produced a lot of coughing which is interesting to get that effect but not a lot of harshness. Maybe it\'s because first dab of the day. Intensity medium high and building.',
        analysis='Run 8 on Rig 6 at 420°F — first dab of day, deliberate larger load. Functionally clean: very little harshness, appeared late in draw 2 (~30s remaining), never escalated. Swab golden — user attributes to the second cycle (one draw), consistent with the established cycle-count swab pattern (second cycles drive darker swabs regardless of material or endpoint; beige is the likely baseline without it). Coughing throughout with little harshness is consistent with terpene-load cough at dense vapor delivery — FW106 R1 on Rig 4 documented the same signature (terpene-load cough without harshness at 416°F); a larger load through Rig 6\'s efficient joystick delivery produces denser early vapor that can trigger a cough reflex before the harshness threshold is crossed.\n\nThree runs at 420°F on Rig 6 now: R6 (first dab, uncertain/smaller load, harsh at ~43s); R7 (second dab, lighter suspected load, clean); R8 (first dab, larger load, very little non-escalating harshness). R8 matches R6\'s session-order condition and gives a meaningfully cleaner result — load size is the most parsimonious explanation for R6\'s divergence. Smaller load in R6 likely brought material to depletion or the harshness threshold earlier; R6 depleted at ~50s with harshness entering 7s prior, which is consistent with either hot-insert exposure or density crossing at the load\'s margin. R8\'s second cycle confirms material was still present well into the session.\n\nFlavor notes — mildew, fruitiness, savory/cheese — are new for this jar. Prior runs noted spice (R1–5) and a floral cold nose (R7). Worth tracking whether this profile stabilizes on R9 or reflects the jar\'s current fridge state.\n\n420°F is the working point on Rig 6 for this jar with adequate load. R6 is now the outlier, explained by load, not a ceiling signal.',
    ),
    CompletedRun(
        strain='The Hive #1',
        run_date=date(2026, 7, 3),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 7, 3, 17, 43, 51, tzinfo=timezone.utc),
        waypoints=HIVE1_DESCENT_GENTLE,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Open:</strong> 440°F &nbsp;|&nbsp; <strong>Floor:</strong> 400°F — first descent curve for this jar; gentle descent (440→420@30s→400@60s)',
        swab='Golden — minimal reclaim.',
        session_char='Cycle 1 (3 draws): good flavor draw 1; mild throat harshness end of draw 2 (~15s left); eased on short draw 3. Cycle 2: depleted on first draw, terminated ~48s left. Load slightly larger than normal (self-report imprecise). Minimal reclaim, golden swab. Medium intensity, confirmed never escalated beyond medium.',
        intensity='Medium — confirmed final read, never went above medium',
        dab_notes='Three draws in first cycle. Plenty of taste on first one. Second one had mild throat harshness show up at end of draw 2 (15 seconds left). Harshness seemed to resolve in short draw three. Going to run second cycle. Depleted during first draw on second cycle. Terminated at 48 seconds left. Very minimal amount of reclaim, golden in color on swabs. Intensity is medium. Right now at least. Load was slightly larger than normal or so I thought, we know this part is unreliable. This one never went above medium intensity.',
        analysis='Run 9 — first descent-curve run for this jar (all eight priors were ramp or flat-hold); an intentional swap from the planned 425°F ramp, not a confound.\n\nCycle 1 (3 draws): good flavor on draw 1, mild throat harshness at end of draw 2 (~45s mark, curve already down near 410°F), eased off on a short draw 3. Not fully clean like FW106 R23/WM R16/bp4rw13 R5 on this curve, but matches FW106 R26\'s late-cycle-1 harshness — this run lands inside the range the curve has already shown across four strains, not outside it. Harshness clearing on a short draw without water is new for the log; a shorter draw delivering less material is the simpler read than the threshold reversing on its own.\n\nCycle 2 depleted in one draw (terminated ~12s in) despite a load reported as slightly larger than normal — counterintuitive, and it matches bp4rw13 R11\'s identical pattern on this same curve and rig. Load self-report is acknowledged as imprecise, so treat it as directional. Golden swab, minimal reclaim: consistent with this jar\'s cycle-count pattern (Run 8: second cycle drives golden), not a new signal about curve or material.',
    ),
    CompletedRun(
        strain='The Hive #1',
        run_date=date(2026, 7, 3),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 7, 3, 18, 36, 11, tzinfo=timezone.utc),
        waypoints=HIVE1_DESCENT_GENTLE,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Open:</strong> 440°F &nbsp;|&nbsp; <strong>Floor:</strong> 400°F — gentle descent (440→420@30s→400@60s); same as Run 9',
        swab='Golden — minimal reclaim.',
        session_char='Cycle 1 (3 draws): mild throat-and-chest harshness end of draw 2 (~15s left), both eased by draw 3 — same timing as Run 9. Cycle 2 (deliberate second pull): 1.5 draws before depletion, no harshness on return, hint of toast. Golden swab, minimal reclaim. Moderate-to-high intensity (immediate read).',
        intensity='Moderate to high (immediate read)',
        dab_notes='Ok that was weird. Exact same pattern. Gonna fire a second cycle just to see… I got one and a half draws on second cycle before it depleted. Harshness never returned. Hint of toast. Yes on cycle 1. I also noticed some mild chest harshness alongside the throat. Both resolved in third draw. Swabs were golden and minimal. Moderate to high intensity. Let\'s see how it feels at the pool. That\'s a dumb read on the toast. It\'s likely from some sort of thermal process on whatever is still left at bottom of cycle.',
        analysis='Run 10 repeats Run 9\'s curve and, in cycle 1, its timing almost exactly: 3 draws, mild harshness at end of draw 2 (~15s left), eased on a short draw 3. New: chest harshness alongside throat this time, both resolving by draw 3 — consistent with bp4rw13 R9/R11 (throat-and-chest, resolves) rather than papzp22 R7/bp4rw13 R8\'s chest-only/persists framing. A second strain now counters that original read.\n\nCycle 2 depleted fast — 1.5 draws — with a hint of toast on the return. More likely a thin residue scorching under continued heat once the bulk of the material was gone than any session-order signal — consistent with FW106 R11-12\'s degradation-flavor pattern from material sitting in a hot insert past clean vaporization.\n\nSwab (golden, minimal reclaim) matches Run 9 — expected, same second-cycle driver. Intensity stepped up to moderate-to-high from Run 9\'s medium despite being the second dab (tolerance usually cuts the other way) — extra cycle-2 draw time is the simpler explanation than session order. Load size wasn\'t pinned down, the live confound here.',
    ),
    CompletedRun(
        strain='The Hive #1',
        run_date=date(2026, 7, 3),
        sessions_prior_today=2,
        utc_logged_at=datetime(2026, 7, 3, 22, 27, 14, tzinfo=timezone.utc),
        waypoints=HIVE1_DESCENT_GENTLE,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Open:</strong> 440°F &nbsp;|&nbsp; <strong>Floor:</strong> 400°F — gentle descent (440→420@30s→400@60s); same as Runs 9–10',
        swab='Golden — minimal reclaim.',
        session_char='Single cycle, 4 draws, full 60s. Bitter citrus with a creamier undertone. Mild throat harshness at ~25s remaining, faded during draw 3. Quick fourth draw at the end; material depleted. Load slightly larger than normal, not big. Minimal reclaim, golden swab. Medium to medium-high intensity.',
        intensity='Medium to medium-high',
        dab_notes='Ok! Single cycle, tasty. Bitter citrus note, something a little creamier in there. Around 25 seconds left there was mild harshness in throat. I felt it fade during third draw. Quick fourth draw at the end and it looked like it was depleted. Swabs had minimal reclaim, golden. Intensity medium to medium high. Cause it seemed depleted. Load size was slightly larger than normal but not big.',
        analysis='Run 11 continues the gentle descent curve for a third consecutive time this same day (R9 first dab, R10 second, R11 third) — the planned first-dab repeat from R10\'s note didn\'t happen since all three landed same-day; that clean test still hasn\'t run. Single cycle this time: a slightly-larger-than-normal load fully depleted across four draws, unlike R9 and R10, both of which left material for a deliberate second cycle. Harshness arrived at ~25s remaining (curve near 417°F) — earlier in session time than R9/R10\'s ~15s-remaining onset (curve near 410°F), despite the higher temperature at onset, and despite this being the day\'s third dab. That\'s directionally consistent with the accumulated-exposure question R10\'s analysis flagged as open, though device heat carried over from two prior dabs this session is an equally live candidate alongside airway exposure — a warmer-than-programmed insert could also explain the full single-cycle depletion on a slightly larger load. No toast this run, but there was no second cycle to produce the residue-scorch condition that generated toast on R10, so this isn\'t a counter-finding. Golden swab with minimal reclaim continues across all three descent runs — but R11 had no second cycle at all, which counters the cycle-count framing established at R8 (second cycle attributed as the golden driver); across this descent series golden may track with the curve or load rather than cycle count specifically. Bitter citrus with a creamier undertone is new for this jar (priors: spice, floral, mildew/fruit/savory-cheese) and, given Honey Banana × Papaya\'s inferred myrcene/terpinolene profile has no citrus association, this is a more surprising instance of the cross-strain bitter-citrus pattern (MB9ZST, MBD, OC, FW106, bp4rw13) than the citrus-genetics strains already in that group.',
    ),
]

# ── Status ──
STATUS = StrainStatus(
    name='The Hive #1',
    profile_anchor='#hive1-profile',
    next_text='Run 12: repeat the gentle descent as a genuine first dab on a fresh day — the session-order-clean test that still hasn\'t happened',
    accent=None,
    slug='hive1',
    info=[
        ('Strain', 'The Hive #1 (Honey Banana × Papaya — Bloom Seed Co)'),
        ('Consistency', 'Cold cure'),
        ('Producer', 'Myxed Up (washed and pressed)'),
        ('Input', '159–73 micron ice water hash'),
        ('Nose', 'Very fragrant at cold nose. Spice noticeable (consistent with caryophyllene — weak secondary signal only).'),
    ],
    terpene_note='<strong>Terpene inference:</strong> Myrcene and terpinolene inferred from tropical fruit character; Honey Banana × Papaya lineage (Bloom Seed Co). Terpene ratios not inferable from genetics — standard palette as orientation only. See <a href="#terpene-ref">Terpene Reference</a>.',
    next_dab_notes='Genuine first dab of a fresh day, same gentle descent curve. Watch whether cycle 1 harshness onset moves back later (toward or past the ~45s-remaining mark seen on R9/R10) without today\'s accumulated exposure, or whether it still lands near ~25–35s remaining like R11.',
    next_ai_analysis='Three same-day runs on the gentle descent now show harshness onset creeping earlier with each successive dab — R9 and R10 both ~15s remaining, R11 ~25s remaining — the clearest same-day session-order gradient the log has for this curve. The genuine test is still open: a first dab on a fresh day, free of today\'s accumulated exposure, to see whether cycle 1 comes back clean like FW106 R23 / WM R16 / bp4rw13 R5\'s first-dab descent runs, or whether ~15–25s-remaining harshness is a real ceiling for this curve independent of session order.',
    next_waypoints=HIVE1_DESCENT_GENTLE,
    jar_index='',
)
