"""Lemon Heads + Blueberry Haze — jar file (slug: lhbh)."""
from datetime import date, datetime, timezone
from Dabby_Core import *

# ── Waypoint constants (local to this jar) ──

LHBH_425 = [
    Waypoint(time_s=0,  temp_f=380, note='Session open'),
    Waypoint(time_s=4,  temp_f=400, note='Steep early climb'),
    Waypoint(time_s=8,  temp_f=425, note='Endpoint — up 5°F from Run 1'),
    Waypoint(time_s=60, temp_f=425, note='Hold'),
]

LHBH_DESCENT_450 = [
    Waypoint(time_s=0,  temp_f=450, note='Session open — hot open'),
    Waypoint(time_s=10, temp_f=450, note='Hold at peak — one draw at 450°F'),
    Waypoint(time_s=30, temp_f=425, note='Gentle descent midpoint'),
    Waypoint(time_s=45, temp_f=410, note='Floor — shorter cycle'),
]

LHBH_HOLD15_DESCENT_440 = [
    Waypoint(time_s=0,  temp_f=440, note='Session open — hot open'),
    Waypoint(time_s=15, temp_f=440, note='Hold at peak — extended 15s hold'),
    Waypoint(time_s=35, temp_f=430, note='Shallow first descent leg — below sapphire passive decay'),
    Waypoint(time_s=60, temp_f=400, note='Floor'),
]

# ── Runs (chronological; run numbers assigned positionally by the generator) ──

RUNS = [
    CompletedRun(
        strain='Lemon Heads + Blueberry Haze',
        run_date=date(2026, 6, 13),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 13, 23, 14, 36, tzinfo=timezone.utc),
        waypoints=BASELINE_420,
        equipment=RIG_5,
        duration_seconds=65,
        endpoint_note='<strong>Endpoint:</strong> 420°F — baseline first run',
        swab='dark golden',
        session_char='Flavorful, no specific notes on character. No harshness throughout. Dense-then-wispy within-draw pattern both cycles. Draws cut out fast with material remaining. Two cycles: 60s baseline + ~40s second pass.',
        intensity='High — body tension, lots of creative thoughts; effects built over ~30 minutes.',
        dab_notes='Cold nose: predominantly gassy, with some fruit underneath. Interesting nutty note as well. Not super loud but jar is fresh from fridge. Run: interesting, flavorful but no specific notes. Draws never got harsh throughout entire cycle. Vapor had same dense then wispy nature to it we\'ve seen before. After cycle ended ran it again (second cycle, ~40s) and continued getting the dense then quickly wispy pattern. Swab dark golden, lots of reclaim. Draws cutting out fast — good hit then quickly nothing. It got heavier for sure, I\'d put it in high. Some body tension, lots of creative thoughts.',
        analysis='The defining observation on Run 1 is the dense-then-wispy within-draw pattern appearing on Rig 5 — the same pattern documented on Rig 4 (single pearl) on FW106 R16, where the hypothesis was single-pearl thermal loss during draws. That pattern was expected to be reduced on Rig 5\'s dual pearls; LHBH Run 1 shows it regardless. Either the dual-pearl thermal advantage is material-dependent — this material makes heavier demands on pearl heat maintenance than FW106 or BB36 #2 — or the pearl-count hypothesis was overclaiming. One run, can\'t distinguish. Dark golden swab and heavy reclaim are consistent with incomplete vaporization. No harshness across both cycles puts 420°F comfortably within range. Intensity landed high despite the inefficiency. Flavor was present but no specific character noted — the citrus/gas/haze profile 710 describes didn\'t come through distinctly on Run 1.',
    ),
    CompletedRun(
        strain='Lemon Heads + Blueberry Haze',
        run_date=date(2026, 6, 13),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 6, 14, 0, 57, 0, tzinfo=timezone.utc),
        waypoints=LHBH_425,
        equipment=RIG_5,
        duration_seconds=60,
        endpoint_note='<strong>Endpoint:</strong> 425°F — up 5°F from Run 1',
        swab='golden',
        session_char='Lemon on first draw. Solid vapor through the whole cycle — no within-draw dropoff. Harshness on third draw with vapor still flowing and material remaining. Single cycle.',
        intensity='High',
        dab_notes='That was great. Got a hint of lemon in the first draw. Got some harshness in third draw. I was getting solid vapor through the whole cycle. I think there\'s more in there. Swabs are golden, roughly same amount of reclaim which is weird. Overall it was much improved. Intensity is pretty big. High. [Q: draw 3 harshness — vapor hadn\'t thinned.] Couldn\'t do a second pass — swabbing eliminated the ability to do it. But the lighter color maybe points to I was right that there was more to vape.',
        analysis='Run 2 answers the main Run 1 question: the within-draw dense-to-wispy dropoff was endpoint-sensitive. Solid vapor through the whole cycle at 425°F vs. the pronounced drop at 420°F across both of Run 1\'s cycles. Ramp was identical both runs (8s), so the 5°F endpoint bump is the more likely lever. Cross-strain context: FW106 Run 16 (June 12, Rig 4) showed the same within-draw thick-then-wispy pattern — hypothesis there was single-pearl heat loss during draws. LHBH Run 1 complicated that by showing the same pattern on Rig 5\'s dual pearls. Run 2 at 425°F resolving it on Rig 5 points at endpoint temperature, not pearl count, as the driver. BB36 #2 Run 6 and OC Run 14 showed the same wispy-to-solid shift when endpoint went up, but those changed ramp and endpoint together. LHBH is the cleanest isolation yet: same 8s ramp, only endpoint moved. Flavor broke through for the first time: lemon on draw 1 — Run 1 had nothing specific. Lighter golden swab at a higher endpoint is consistent with better vaporization efficiency. Harshness on draw 3 with vapor still flowing and material present is a clean temperature signal — not depletion. 420°F was clean across two cycles in Run 1; 425°F brought harshness on draw 3. The boundary sits in that 5°F band.',
    ),
    CompletedRun(
        strain='Lemon Heads + Blueberry Haze',
        run_date=date(2026, 6, 18),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 18, 21, 44, 7, tzinfo=timezone.utc),
        waypoints=LHBH_425,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Endpoint:</strong> 425°F — first run on Rig 6',
        swab='dark golden',
        session_char='Dense vapor throughout until depletion at ~55s. Mild harshness entered at ~40s with vapor still thick. Sparse reclaim. Slight lemon candy note on cold nose and during run. Suspected smaller-than-normal load; low intensity.',
        intensity='Low — possibly still building at logging time.',
        dab_notes='Swabs were dark golden, sparse reclaim. Depletion of material based on vapor production drop was around 55 seconds. Very mild harshness showed up around the 40 second mark. Intensity is low right now, can\'t tell if it\'s building. I think maybe this load was less than normal. Also I think it was mostly lemon heads. I got a very slight lemon heads candy note on cold nose of jar and I tasted some of it in the run. So maybe for next time a larger load, and 425? 430? Vapor was very dense until depletion.',
        analysis='Defining observation is the vapor density sequence: dense throughout until depletion at ~55s, with mild harshness entering at ~40s while vapor was still thick. Harshness preceding depletion by 15s and co-occurring with dense vapor weakens the depletion framing — if material were running thin, vapor would be thinning too. This looks like a cumulative exposure or endpoint ceiling rather than an empty-insert signal. Cross-run context: Run 2 on Rig 5 also had harshness arrive with vapor flowing and material present — same pattern, different rig. The boundary is somewhere in the 40–50s range at 425°F on this strain across both rigs. Sparse reclaim with dark golden swab is consistent with the joystick vaporizing more completely; 60s duration is driving the swab color, matching the duration-swab pattern across all 60s FW106 runs on Rigs 4, 5, and 6. Lemon candy note on cold nose and during the run — two consecutive runs now with lemon character (Run 2: lemon on draw 1; Run 3: lemon candy in the run), directional confirmation that the outer-ring Lemon Heads character is there when that portion loads. Intensity low this run is load-size driven; Rig 6 delivery on this strain is otherwise confirmed — dense vapor throughout the session.',
    ),
    CompletedRun(
        strain='Lemon Heads + Blueberry Haze',
        run_date=date(2026, 6, 18),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 6, 18, 23, 0, 0, tzinfo=timezone.utc),
        waypoints=LHBH_425,
        equipment=RIG_6,
        duration_seconds=35,
        endpoint_note='<strong>Endpoint:</strong> 425°F — larger load, stopped early (~35s estimated)',
        swab='golden with amber spots',
        session_char='Heavy vapor throughout. Harshness entered at ~30s; stopped early — exact stop time unknown, estimated ~35s. Larger than normal load.',
        intensity='Medium',
        dab_notes='Heavy vapor, a lot of harshness starting around 30 seconds. Swabs were golden with some amber spots. Medium intensity. Stopped early but didn\'t see the time. [Time: 5:00 PM MDT]',
        analysis='Key result: harshness arrived 10 seconds earlier on the larger load (~30s) than on the smaller load (~40s on Run 3) — same curve, same rig. Depletion predicts the opposite: more material means the load runs thin later, so harshness threshold should shift back. Earlier onset with more material cuts against that and aligns with vapor density or particle accumulation as the driver — bigger load, heavier vapor per draw, threshold crossed sooner. The two-run load-size comparison is one of the cleaner within-strain contrasts in the log; session-order confound (Run 3: first of day, Run 4: second) is real but unlikely to account for a 10-second directional shift. Golden swab with amber spots is a departure from Run 3\'s solid dark golden — amber spots may indicate patchy vaporization on a larger load, or load placement geometry. Medium intensity is load-consistent vs. Run 3\'s low. 425°F on Rig 6 has a ceiling around 30s on a loaded session; stopping early was the right call.',
    ),
    CompletedRun(
        strain='Lemon Heads + Blueberry Haze',
        run_date=date(2026, 6, 18),
        sessions_prior_today=2,
        utc_logged_at=datetime(2026, 6, 19, 0, 32, 40, tzinfo=timezone.utc),
        waypoints=BASELINE_420,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Endpoint:</strong> 420°F — back to baseline on Rig 6',
        swab='light golden with amber spots on tip',
        session_char='Light golden swab with amber spots on tip. Harshness entered on draw 3 and kept building. Full 60s cycle completed; material felt present at close — second cycle skipped. Very high intensity.',
        intensity='Very high',
        dab_notes='Swab was light golden, a few amber spots on tip. Harshness started in third draw and kept building. Finished the cycle and felt like there was more to hit but I didn\'t fire it again. I\'m glad I didn\'t, in realllllly high.',
        analysis='420°F on Rig 6 produced draw-3 harshness — not the clean floor this strain found on Rig 5 at the same endpoint. Run 1 on Rig 5 at 420°F ran two full cycles with no harshness, first dab of the day; Run 5 on Rig 6 at 420°F arrived at draw-3 harshness, third dab of the day. The session-order confound (third dab following Runs 3 and 4 earlier today) is the most plausible single explanation — cumulative airway exposure from the day may be lowering the harshness threshold independent of endpoint or rig. However, the rig difference (Rig 5 vs. Rig 6) changed simultaneously, so the two explanations can\'t be separated from this run alone. A first-dab run at 420°F on Rig 6 is the test that isolates them. Lightest swab in this jar\'s history — lower endpoint is the obvious driver vs. Runs 3 and 4 at 425°F. Amber spots on the tip consistent with Run 4; may reflect load geometry or insert contact pattern. Intensity very high — strongest read in this jar across five runs, third dab of the day. Skipping the second cycle was the right call.',
    ),
    CompletedRun(
        strain='Lemon Heads + Blueberry Haze',
        run_date=date(2026, 6, 23),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 24, 0, 42, 6, tzinfo=timezone.utc),
        waypoints=BASELINE_420,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Endpoint:</strong> 420°F — first-dab on Rig 6, session-order confound resolved',
        swab='golden with amber spots',
        session_char='Dense, cloudy vapor throughout first cycle; no within-draw dropoff. Harshness entered at ~40s, grew to medium by end. Bitter note at session open. Heavy terpene-load coughing throughout. Second cycle: two draws (swab confounded by second cycle).',
        intensity='Medium-high — possibly still building at logging time',
        dab_notes='Vapor stayed dense and cloudy through the run. Harshness in last 20 seconds, growing to medium by end. Not a ton of taste but that bitter note in the beginning we\'ve seen in other strains was there. A lot of coughing from terp load though, interesting without a lot of flavor. Took two more hits on a second cycle — swabs aren\'t a great read. They were golden with amber spots. Intensity medium-high, maybe still building.',
        analysis='The key result: harshness entered at ~40s on a first-dab run at 420°F on Rig 6 — dramatically later than Run 5\'s draw-3 harshness under third-dab conditions. Session order was the primary driver in Run 5, not the endpoint or the rig. 420°F is workable on Rig 6 first-dab.\n\nDense, cloudy vapor throughout the first cycle with no within-draw dropoff — the Rig 5 wispy pattern doesn\'t appear on Rig 6 at 420°F. The joystick\'s directed airflow sustains vapor delivery where Rig 5\'s spinner/pearl setup didn\'t. Swab is second-cycle driven and not a clean read on the first 60s; not entered as a temperature signal.\n\nBitter note at session open is consistent with the cross-strain bitter citrus pattern in the wisdom layer — likely limonene-forward, not strain-specific character. Terpene-load cough without distinct flavor has appeared on Rig 6 across other strains (Hive #1 R8, papzp22 R4) at this temperature range. Medium-high intensity building is expected on a first-dab run with good vapor density throughout.\n\nOne notable comparison: Run 3 (425°F on Rig 6, first dab, suspected small load) also showed ~40s harshness onset. Two first-dab runs at different endpoints showing similar onset timing suggests the practical ceiling on Rig 6 for this strain is around 40s regardless of whether the endpoint is 420 or 425. Load size is an unresolved variable between those two runs.',
    ),
    CompletedRun(
        strain='Lemon Heads + Blueberry Haze',
        run_date=date(2026, 6, 23),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 6, 24, 4, 36, 58, tzinfo=timezone.utc),
        waypoints=BASELINE_420,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Endpoint:</strong> 420°F — second dab of day, large load',
        swab='golden with amber streaks',
        session_char='Two big draws on first cycle — fruit/lemon on draw 1, possibly blueberry; harshness on draw 2. Second cycle: one medium draw, mild harshness, toasty flavor. Accidentally large load; heavy reclaim.',
        intensity='Medium-high',
        dab_notes='Got two big draws on first cycle. First draw gave a ton of fruit, definitely got some lemon, maybe a hint of blueberry. Harshness in second draw and then the cycle was over. Second cycle: only took one medium length draw. Mild harshness but tasted toasty. Depletion doesn\'t make sense, swabs had a lot of reclaim, I must have accidentally loaded large. So the toasty could be the cooking effect of material being near 420 but not yet booking into vapor…eventually maybe the prolonged slow heat changes something. Swabs were golden with a few amber streaks. More reclaim than typical. Intensity medium-high.',
        analysis='Run 7\'s standout result is the flavor: lemon and fruit clearly on draw 1 — the most distinct character this jar has produced across all six prior runs. Both first-dab Rig 6 runs (R3 and R6) returned terpene-load cough with little specific flavor; the earlier lemon on Run 2 was also a second dab. This run is second dab and an accidentally large load, so session order and load size both changed from the first-dab reads simultaneously — can\'t isolate which drove it.\n\nHarshness arriving on draw 2 is earlier than Run 6\'s ~40s onset at the same endpoint and rig. Second-dab accumulated airway exposure is the most parsimonious explanation, consistent with the pattern across other strains.\n\nSecond cycle: toasty flavor, mild harshness, heavy reclaim. Depletion ruled out. User proposed a prolonged-heat mechanism — material near the insert at 420°F that isn\'t yet vaporizing undergoes slow thermal change over the extended session, altering flavor before going into vapor. One data point; logged as a user hypothesis at single-data-point weight.\n\nAmber component in the swab (golden with amber streaks) now appears across all three second-cycle runs in this jar — R4, R6, R7 all show amber where single-cycle runs don\'t. Amber appears to be a second-cycle marker for this strain, not a temperature signal.',
    ),
    CompletedRun(
        strain='Lemon Heads + Blueberry Haze',
        run_date=date(2026, 7, 17),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 7, 17, 19, 44, 50, tzinfo=timezone.utc),
        waypoints=LHBH_DESCENT_450,
        equipment=RIG_6,
        duration_seconds=45,
        endpoint_note='<strong>Open:</strong> 450°F &nbsp;|&nbsp; <strong>Floor:</strong> 410°F — 10s hold at 450°F then gentle descent; first hot open on this strain. 3.5 cycles on one large load; final cycle stopped about halfway.',
        swab='dark golden',
        session_char='Heavy terpene-load coughing throughout; flavor held across all 3.5 cycles. Throat harshness, hard to distinguish from the coughing. Deliberate big load; stopped halfway through the fourth cycle on satiety, reclaim suggesting material remained.',
        intensity='Moderate — daytime, upright, functional character.',
        dab_notes='This is a big load and I want to do it 450 descent. [Post-run:] Whoa that was a huge one. I coughed so much and it was so big that I had to run 3.5 cycles. Swabs weren\'t too dark though, dark golden. It never got less tasty. A bit of harshness but it was hard to distinguish from the term coughing. [Q: intensity; stopped early?] Moderate. For all that terp drama (and it did have nice flavor) it didn\'t deliver a ton of effect. Yes, stopped halfway through as I\'d had enough. Reclaim on the swab suggests I could have kept going. [Q: harshness location — throat or chest?] Throat harshness. This was the kind of high I was expecting from this jar. Very daytime energy, very upright and functional. I sometimes think I\'m not high at all but then something will happen to remind me I\'m very high.',
        analysis='First hot open in this jar\'s history. Flavor held across 3.5 cycles — the longest it has held in eight runs — but the planned load isolation only half-ran: load and curve changed together (big load, 450°F descent instead of the 420°F ramp), so this run can\'t separate them. Pair-wise: Run 7\'s flavor came on a large load at the 420°F ramp (2nd dab); Run 8 on a large load at the 450°F descent (1st dab). Flavor has tracked load across two curves and two session orders — directional for load as the flavor lever, with curve shape the live confound. Intensity read moderate, with a daytime/functional character the user flags as easy to underread. Session ended on satiety with material remaining — consistent with the descent-curve pattern where the stopping condition moves off harshness; LHBH is a sixth strain context, first-dab instance. Harshness was throat-located and not limiting, hard to distinguish from terpene-load coughing (the same separation Sour Tangie R7 made at a 450°F open); no chest on this jar\'s first hot open, post-session window not stated. Dark golden swab after 3.5 cycles is not a floor signal — multi-cycle swabs darken independent of endpoint.',
    ),
    CompletedRun(
        strain='Lemon Heads + Blueberry Haze',
        run_date=date(2026, 7, 28),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 7, 28, 19, 12, 44, tzinfo=timezone.utc),
        waypoints=LHBH_HOLD15_DESCENT_440,
        equipment=RIG_8,
        duration_seconds=60,
        endpoint_note='<strong>Open:</strong> 440°F &nbsp;|&nbsp; <strong>Floor:</strong> 400°F — 15s hold at 440°F, then descent through 430°F at 35s; the jar\'s first 440°F curve and the first run on Rig 8 (Calibear Fab Recycler top). Three cycles.',
        swab='beige to light golden',
        session_char='Heavier pull than the previous wet top; flavor read better. No harshness at any point — throat or chest, during the session or after. Three cycles on a slightly-larger-than-normal load: full first cycle, one good draw on the second, one thinner draw on the third. Beige to light golden swab with minimal residue after three trips to 440°F.',
        intensity='Big',
        dab_notes='new top, Calibear Fab Recycler. This top has a known design defect that shouldn\'t affect dab performance but rather necessitates special handling to reduce risk of damaging the sapphire insert due to water flow back. I bought it to test how the top a recycler (and similar multiple straight flow functions in glass) would differ from the rbr design, and if I like it I will buy a better design. [On the defect:] to adjust your understanding, the much bigger issue than experimental confounds is the thermal shock a good slug of water would do to a very hot and very thin piece of machined sapphire crystal. This design is obsolete, but in stock and available for me to test. [Post-run:] I ran the 440 15s bounded hold then descent to 400 at 60s. Is it called amber color? Orange? The pull is very clearly heavier than the rbr, the flavor seemed better than rbr, and no harshness noticed at all. There\'s a lot of water in the piece so I kind of wonder why it would perform better than the rbr in these respects. Effect is pretty big too. I ran a second cycle and got one nice hit from that. And a third cycle got one more nice but thin hit. And even with three trips to 440 the swabs were beige to light golden, pretty minimal. Load was maybe a tad larger than normal [Q: middle waypoint of the curve] Middle waypoint is 430 at 35s. I am open to suggested smoothing of this curve [Q: did "no harshness" cover chest/heartburn, both during and after?] Yes no harshness at all',
        analysis='Run 9 is the second run in nine with no harshness at all — the first was Run 1 (420°F ramp, Rig 5, first dab, two cycles); Runs 2 through 8 all produced it somewhere. It arrived on the jar\'s longest per-cycle dwell in the high band, which is what makes it worth attention.\n\nThe curve\'s stated shape understates its thermal history. The 440°F-to-430°F leg spans 20 seconds — 0.5°F/s, below sapphire\'s roughly 1°F/s free-decay rate — so the controller was holding heat up through it rather than letting the insert fall. Functionally the run held at or above 430°F for 35 seconds before the real descent began, against roughly 26 seconds for Run 8\'s 450°F bounded hold. This is the case the curve-design guidance names directly: a descent leg gentler than passive decay re-creates a flat hold rather than descending. Thirty-five seconds in that band, three cycles over, with no harshness and no floor signal.\n\nSwab came back beige to light golden with minimal residue after three cycles. Cycle count darkens swabs independent of endpoint, so three trips staying light is worth noting — but the color sits inside the clean range where swab cannot resolve small differences, so it is not a fine-grained read. Residue quantity is the more informative half: minimal reclaim on a larger-than-normal load is consistent with fairly complete vaporization, against Run 8\'s dark golden swab and remaining reclaim after 3.5 cycles at a 450°F open.\n\nEquipment is the dominant confound. This is Rig 8\'s first run, and this jar has never run on the RBR — so "heavier pull, better flavor than the RBR" compares across strain, curve, session order, and top simultaneously, against papzp22 R10 (450°F grey, large load) and BB36 #2 R7 (430°F purple, 4th dab). The RBR\'s own taste read is already split and unmatched across those two runs. Three tops are now in rotation with no matched-load matched-curve comparison between any pair. The impression is recorded as an impression, not a measurement.\n\nUser asked why a piece holding more water would read better on both flavor and draw weight, which inverts the expectation that water costs terpenes and adds drag. Recorded as an open question at single-data-point weight. Worth noting only that a recycler and a bell move air along different paths, so water volume may not be the operative variable even where it is the visible one — the inputs are not isolable from one run on new glass.\n\nLoad ran slightly larger than normal. This jar carries the larger-load-to-earlier-harshness direction in the cross-strain load record (Run 3\'s ~40s against Run 4\'s ~30s at 425°F), and Run 9 cuts against that within-strain direction — bigger load, hotter band, no harshness. Curve shape moved at the same time, so this does not isolate load; it does mean the jar\'s load signal came from 425°F ramps and may not carry to bounded-hold descents.\n\nNo chest signal, during or after, explicitly checked in both windows — the jar\'s first clean negative on both (Run 8\'s post-session window was never asked). It does not discriminate much: this was a first dab, and the standing counter-reading on the chest pattern is that it may track within-session cumulative exposure rather than the hot open itself. Session ended on thinning vapor across the third cycle rather than harshness, consistent with the descent pattern across seven strains and its first instance on Rig 8.',
    ),
    CompletedRun(
        strain='Lemon Heads + Blueberry Haze',
        run_date=date(2026, 7, 28),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 7, 28, 23, 12, 1, tzinfo=timezone.utc),
        waypoints=LHBH_HOLD15_DESCENT_440,
        equipment=RIG_8,
        duration_seconds=48,
        endpoint_note='<strong>Open:</strong> 440°F &nbsp;|&nbsp; <strong>Floor:</strong> 400°F — Run 9\'s curve unchanged, second run on Rig 8. Moderate load, single cycle, stopped on depletion with about 12 seconds left.',
        swab='beige',
        session_char='Single cycle, stopped when the material went dry with about 12 seconds left on the curve. Delicious but not especially terpy; no coughing. No harshness at any point — throat or chest. Beige swab with next to no reclaim. Moderate load.',
        intensity='Creeping up to a medium.',
        dab_notes='ok that was a good one, moderate load. It was depleted by about 12 seconds left. Delicious but not too terpy. No coughing. No harshness. I Fredrick creeping up to a medium. Swabs were beige and next to no reclaim. I hate to say it because this is cheap lazy glass but the function might be my favorite so far. Too early to say without trying other strains. Maybe it makes it taste better when there\'s a fear that it will blow up your insert at any moment [Q: stopped at the dry point or rode the cycle to 60; single cycle only?] Yes stopped. But I\'m curious why that\'s interesting to you? And yes no harshness, even in chest',
        analysis='Curve and rig held from Run 9; load moved down to moderate but session order moved with it — second dab against Run 9\'s first, so the load isolation this jar has dodged three times is still not clean.\n\nIt is the jar\'s first second-or-later dab with no harshness anywhere. Runs 2, 4, 5 and 7 all produced it, at lower endpoints. Two clean runs on the 440°F bounded hold, one first dab and one second, is directional for the curve — against which Run 10 was the milder run in every other dimension: one cycle, less material, and it went dry before the descent reached its floor.\n\nFlavor split in a way worth recording: "delicious but not too terpy," no coughing at all, against heavy terpene-load coughing on Runs 8 and 9. Quality held, volume dropped. Terpene volume has now tracked load in the same direction across Runs 7 through 10 — directional for load as the volume lever, silent on quality.\n\nBeige swab off a single cycle is expected, not a result — cycle count drives swab color independent of endpoint. Minimal reclaim is close to tautological here: the material ran out at ~48s, and that is what a spent load looks like. Run 9\'s minimal residue after three cycles remains the informative version.\n\nSession ended on depletion, not harshness — the descent pattern\'s second instance on Rig 8. The material was gone before the run left the 430°F leg, so the floor and any smoothing of it went unused. Rig 8\'s second run and the user\'s read strengthened ("the function might be my favorite so far"), with their own hedge attached that it is too early without other strains; both Rig 8 runs are this strain on this curve, so nothing yet isolates the glass. Intensity at a creeping medium against Run 9\'s big, with load and session order both moving that way.',
    ),
]

# ── Status ──
STATUS = StrainStatus(
    name='Lemon Heads + Blueberry Haze',
    profile_anchor='#lhbh-profile',
    next_text='Run 11: same 440°F bounded-hold descent, moderate load, second dab — but with the SAML RBR back on (Rig 7), so the glass is the only thing that moves',
    accent=None,
    slug='lhbh',
    info=[
        ('Strains', 'Lemon Heads (Lemon G × Face Off OG BX) + Blueberry Haze (Blueberry × Haze)'),
        ('Format', 'Close Friends Persy Thumbprint — two strains: outer ring cold cure badder (Lemon Heads), center jam (Blueberry Haze). 90μ persy-tier. Load position not reliably distinguishable.'),
        ('Producer', '710 Labs'),
        ('710 Notes', 'Lemon Heads brings one of our favorite Lemon G profiles with a hint of gas. Blueberry Haze starts with a forward blueberry zing, then lets the haze linger. Bright citrus up front, haze on the backend.'),
        ('Nose', 'Predominantly gassy, with some fruit underneath. Interesting nutty note. Not loud on fresh jar — consistent with cold-cure-in-fridge pattern; may open up over time.'),
    ],
    terpene_note='<strong>Terpene inference:</strong> Limonene inferred dominant from Lemon Heads (Lemon G × Face Off OG BX) — Lemon G is known for strong citrus/lemon character; myrcene and terpinolene inferred from Blueberry Haze (Blueberry × Haze). Not measured. See <a href="#terpene-ref">Terpene Reference</a>.',
    next_dab_notes='',
    next_ai_analysis='Another Rig 8 rerun buys a load data point on a question this jar keeps confounding, while the live decision — whether the recycler function is worth a better piece — has no matched evidence at all. Run 11: same strain, curve, load class and dab slot as Run 10, with the SAML RBR back on. That would be the first pair in this log differing only by the top. Drop the 415°F-at-37s smoothing — a moderate load never survives to that part of the curve. Expected: the heavier pull and better flavor don\'t reproduce on the RBR, harshness absent either way. Surprising: the RBR reads identical on both — which puts Runs 9 and 10 on the curve and the load rather than the glass, and kills the case for upgrading.',
    next_waypoints=LHBH_HOLD15_DESCENT_440,
    jar_index='',
)
