"""Orange Candy — jar file (slug: oc)."""
from datetime import date, datetime, timezone
from Dabby_Core import *

# ── Waypoint constants (local to this jar) ──
OC_RUNS12 = [
    Waypoint(time_s=0, temp_f=375, note='Session open'),
    Waypoint(time_s=15, temp_f=378, note='Flat phase'),
    Waypoint(time_s=40, temp_f=395, note='Mid ascent'),
    Waypoint(time_s=65, temp_f=450, note='Endpoint — raised to compensate for estimated thermal offset'),
]
OC_RUN3 = [
    Waypoint(time_s=0, temp_f=375, note='Session open'),
    Waypoint(time_s=15, temp_f=378, note='Flat phase'),
    Waypoint(time_s=35, temp_f=410, note='Steeper climb — faster progression through mid terpene zones'),
    Waypoint(time_s=65, temp_f=440, note='Endpoint — reduced; flatter tail allows insert surface to approach equilibrium'),
]
OC_RUN4 = [
    Waypoint(time_s=0, temp_f=380, note='Session open — raised 5°F to increase opening vapor density'),
    Waypoint(time_s=15, temp_f=390, note='Halfway between open and mid waypoint'),
    Waypoint(time_s=35, temp_f=410, note='Halfway between open and endpoint'),
    Waypoint(time_s=65, temp_f=440, note='Endpoint — unchanged'),
]
OC_RUN5 = [
    Waypoint(time_s=0, temp_f=350, note='Session open — lower opening setpoint under exploration'),
    Waypoint(time_s=30, temp_f=410, note='Mid ascent'),
    Waypoint(time_s=50, temp_f=440, note='Upper zone'),
    Waypoint(time_s=65, temp_f=460, note='Endpoint'),
]
OC_RUN6 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=15, temp_f=390, note='Early ascent'),
    Waypoint(time_s=35, temp_f=410, note='Mid ascent'),
    Waypoint(time_s=65, temp_f=430, note='Endpoint — down 10°F from Runs 3–4'),
]
OC_RUN7 = [
    Waypoint(time_s=0, temp_f=430, note='Steady hold — flat 430°F from session open'),
    Waypoint(time_s=60, temp_f=430, note='Endpoint'),
]
OC_RUN8 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=10, temp_f=400, note='Fast early climb'),
    Waypoint(time_s=20, temp_f=420, note='Endpoint — 420°F in 20s, 2°F/sec'),
    Waypoint(time_s=50, temp_f=420, note='Hold'),
]
OC_RUN9 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=10, temp_f=400, note='Fast early climb'),
    Waypoint(time_s=20, temp_f=415, note='Endpoint — down 5°F from Run 8'),
    Waypoint(time_s=50, temp_f=415, note='Hold'),
]
OC_RUN11 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=10, temp_f=400, note='Fast early climb'),
    Waypoint(time_s=20, temp_f=417, note='Endpoint — up 2°F from Runs 9–10'),
    Waypoint(time_s=50, temp_f=417, note='Hold'),
]
OC_RUN12 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=10, temp_f=400, note='Fast early climb'),
    Waypoint(time_s=20, temp_f=416, note='Endpoint — 416°F in 20s, 2°F/sec'),
    Waypoint(time_s=50, temp_f=416, note='Hold'),
]
OC_RUN14 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=4, temp_f=400, note='Steep early climb'),
    Waypoint(time_s=8, temp_f=420, note='Endpoint — 8s ramp; up 4°F from baseline'),
    Waypoint(time_s=40, temp_f=420, note='Hold'),
]

# ── Runs (chronological; run numbers assigned positionally by the generator) ──
RUNS = [
    CompletedRun(
        strain='Orange Candy',
        run_date=None,
        sessions_prior_today=None,
        utc_logged_at=None,
        waypoints=OC_RUNS12,
        equipment=RIG_1,
        too_hot=True,
        endpoint_note='<strong>Endpoint:</strong> 450°F',
        swab='Not recorded.',
        extra_rows=[
            ('Result:', 'Working well but first 40 seconds felt too flat and slow. Low vapor density in opening phase. Same result on Run 2.'),
        ],
        date_label='May 2026',
    ),
    CompletedRun(
        strain='Orange Candy',
        run_date=None,
        sessions_prior_today=None,
        utc_logged_at=None,
        waypoints=OC_RUNS12,
        equipment=RIG_1,
        too_hot=True,
        endpoint_note='<strong>Endpoint:</strong> 450°F — same as Run 1',
        swab='Not recorded.',
        extra_rows=[
            ('Result:', 'Same as Run 1 — opening too flat, low vapor density first 40s.'),
            ('Diagnosis:', 'Opening too flat — low vapor density in first 40s. Steeper climb 15–35s drives earlier vapor production. Flatter tail 35–65s closes the offset — a slowly-arrived-at 440°F delivers more heat to the material than a steeply-arrived-at 450°F.'),
        ],
        date_label='May 2026',
    ),
    CompletedRun(
        strain='Orange Candy',
        run_date=None,
        sessions_prior_today=None,
        utc_logged_at=None,
        waypoints=OC_RUN3,
        equipment=RIG_1,
        endpoint_note='<strong>Endpoint:</strong> 440°F',
        swab='Light golden/tan. Clean. Minimal peripheral darkening at tip edge — consistent with insert wall cooling, not degradation.',
        session_char='Very nice. Strong effects. Opening draws wispy but flavorful. Good progression through session.',
        intensity='Strong',
        analysis='Clean swab, strong result. Wispy opening draws suggest opportunity to raise opening setpoint slightly to improve vapor density at session start without affecting the clean tail.',
        date_label='May 2026',
    ),
    CompletedRun(
        strain='Orange Candy',
        run_date=date(2026, 5, 5),
        sessions_prior_today=1,
        utc_logged_at=None,
        waypoints=OC_RUN4,
        equipment=RIG_1,
        endpoint_note='<strong>Endpoint:</strong> 440°F',
        swab='Light golden. Clean both times.',
        session_char='Fine. Not noticeably different from Run 3. Run repeated twice on May 5, 2026 — consistent results across both.',
        analysis='Clean swab. Results stable. Lower opening setpoint (350°F) under exploration for Run 5 as next variable to test.',
    ),
    CompletedRun(
        strain='Orange Candy',
        run_date=date(2026, 5, 6),
        sessions_prior_today=0,
        utc_logged_at=None,
        waypoints=OC_RUN5,
        equipment=RIG_1,
        too_hot=True,
        endpoint_note='<strong>Open:</strong> 350°F &nbsp;|&nbsp; <strong>Endpoint:</strong> 460°F',
        swab='Darker than target — direction consistent with endpoint too hot.',
        session_char='Last portion tad harsh, consistent with elevated endpoint. Effect notably stronger than prior runs.',
        extra_rows=[
            ('Observation:', "User's hypothesis: higher temperature produced stronger effect. Logged as stated — one data point, not a confirmed finding. Confounders include session-to-session variability in tolerance, load size, and conditions."),
            ('Next:', 'Returned to ramp curve for Run 6 — see results below.'),
        ],
    ),
    CompletedRun(
        strain='Orange Candy',
        run_date=date(2026, 5, 9),
        sessions_prior_today=3,
        utc_logged_at=None,
        waypoints=OC_RUN6,
        equipment=RIG_1,
        endpoint_note='<strong>Endpoint:</strong> 430°F',
        swab='Light golden. Clean.',
        session_char='Very nice.',
        extra_rows=[
            ('Next:', 'Repeat to confirm, or test 350°F open / 460°F endpoint curve when ready.'),
        ],
    ),
    CompletedRun(
        strain='Orange Candy',
        run_date=date(2026, 5, 9),
        sessions_prior_today=4,
        utc_logged_at=None,
        waypoints=OC_RUN7,
        equipment=RIG_1,
        duration_seconds=60,
        endpoint_note='<strong>Setpoint:</strong> 430°F steady (no ramp)',
        swab='Plain amber — clean.',
        session_char='Pleasant overall. Not as tasty as the ramp from lower temp. Harsh in the last 20 seconds.',
        extra_rows=[
            ('Next:', 'Ramp curve (Run 6 shape) is outperforming the flat hold at 430°F. Repeat Run 6 ramp to confirm, or try 420°F flat hold to find the flat-hold ceiling.'),
        ],
        analysis='Swab is clean, so harshness is a session character signal, not a floor indicator. Comparing to Run 6 (ramp to 430°F, light golden, very nice) — the flat hold at the same endpoint produces clearly more harshness and less flavor character. Consistent with the pattern seen on Fembot #3: flat holds at 430°F track hotter in session feel than ramps to the same endpoint, even with a clean swab.',
    ),
    CompletedRun(
        strain='Orange Candy',
        run_date=date(2026, 5, 22),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 5, 22, 23, 36, tzinfo=timezone.utc),
        waypoints=OC_RUN8,
        equipment=RIG_3,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 420°F — fast ramp (20s, 2°F/sec); 30s hold &nbsp;|&nbsp; <strong>Equipment:</strong> Inaugural Rig 3 (sapphire) run',
        swab='Ultra clean — essentially white/cream, no visible coloration.',
        session_char='Smooth and flavorful first draw through ~23s. Harshness in throat starting at ~31s (11s into 420°F hold), built through end.',
        intensity='Very very intense, delayed ~5 min onset.',
        dab_notes="Big cold nose orange note just now as I opened jar. Swabs look ultra clean to me. Hit was flavorful and smooth up for first draw which lasted until timer showed 27 seconds left. Next draw got harsh in throat at 19 left on timer and that built through the end. I probably could have stopped hitting it earlier, which maybe points to loading bigger dabs and not trying to be super efficient about vaporizing it, just vaporize the sweet spot and leave the rest to the swab. Which would mean that swab color doesn't matter anymore. Would maybe be a difficult habit to break, the thinking is to not waste any of this precious and expensive stuff. Very very intense after about 5 mins.",
        analysis="Inaugural Rig 3 run on OC — first sapphire data point in the log. Ultra-clean swab and very strong delayed effect are consistent: sapphire extracting efficiently, 420°F delivering more than 420°F on quartz would. If sapphire runs 10–20°F hotter in effective temperature (per methodology note), this sits in the 430–440°F equivalent zone — which maps onto OC's quartz history: Run 6 (ramp to 430°F) was clean but at the edge. Ramp phase smooth; harshness entered 11 seconds into the 420°F hold. Shape working — this is a hold-temperature issue. Strong cold nose orange note at jar open; flavor in vapor was 'flavorful and smooth' without named character — whether the orange came through in vapor is unresolved. User suggested loading bigger and stopping at the sweet spot rather than riding the tail, noting this would make swab color less meaningful as a floor indicator — logged as a hypothesis, not a finding.",
    ),
    CompletedRun(
        strain='Orange Candy',
        run_date=date(2026, 5, 22),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 5, 23, 2, 45, tzinfo=timezone.utc),
        waypoints=OC_RUN9,
        equipment=RIG_3,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 415°F — down 5°F from Run 8',
        swab="Golden clean — not as light as Run 8's near-white.",
        session_char='First draw ~25s clean but wispy; second draw ~10s, trace harshness as load ran out. Load done after ~35s.',
        intensity='Mild',
        dab_notes="First draw went 25 seconds, no harshness, kind of wispy vapor. Second draw was about 10 seconds, felt like it was knocking on the harshness but was just barely there. And then the load was definitely done. I think I probably loaded less rather than more. See it's going to be a hard habit to break. Swabs were golden clean but not as light as previous run. Effects mild so far but that would also fit with smaller dab load. It stayed mild.",
        analysis="OC Run 9 on sapphire at 415°F — directionally cleaner than Run 8. Run 8 (420°F) had harshness entering 11 seconds into the hold; Run 9 had a clean 25-second first draw and trace harshness only as the load ran out. That's a meaningful difference, but the small load is a confound — less material vaporizes over a shorter window, which means less time at endpoint temperature before the load is spent. Can't attribute the cleaner tail to 415°F alone. Wispy vapor on the first draw is consistent with a small load; could also suggest 415°F is slightly below the sapphire's vapor production sweet spot. Swab came back golden clean — slightly darker than Run 8's near-white, which may just be run-to-run variation, or slightly more material left at the lower endpoint. Intensity mild, consistent with smaller load.",
    ),
    CompletedRun(
        strain='Orange Candy',
        run_date=date(2026, 5, 23),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 5, 23, 19, 24, tzinfo=timezone.utc),
        waypoints=OC_RUN9,
        equipment=RIG_3,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 415°F — same as Run 9; ~25% larger load',
        swab='Very light golden — a bit more reclaim than prior runs.',
        session_char='No harshness on two full draws across 50 seconds.',
        intensity='Medium (delayed onset ~5 min).',
        dab_notes='Very light golden, maybe a bit more reclaim than prior runs. Harshness never really entered on two big draws across 50 seconds. Effect right after is very light. It grew to a medium I think. This is maybe why increase in temp is warranted.',
        analysis='415°F on Rig 3 with a ~25% larger load — clean across two full draws, no harshness. This resolves Run 9\'s load-size confound: a fuller load at 415°F still produced no harshness, supporting 415°F as within the clean range on the sapphire. Run 8 (420°F, normal load) had harshness at 11s into the hold — 5°F made the difference. Swab came back very light golden with slightly more reclaim than prior runs, consistent with slightly less complete vaporization at the lower endpoint. Effect grew from very light to medium over ~5 minutes — delayed onset pattern consistent with Run 8. Medium ceiling vs. Run 8\'s "very very intense" may reflect the lower endpoint, but run-to-run variability and tolerance are real confounders; single data point. User flagged this as a reason to inch the temperature up.',
    ),
    CompletedRun(
        strain='Orange Candy',
        run_date=date(2026, 5, 23),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 5, 23, 23, 38, tzinfo=timezone.utc),
        waypoints=OC_RUN11,
        equipment=RIG_3,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 417°F — up 2°F from Runs 9–10',
        swab='Very light golden, slightly more reclaim than Run 10.',
        session_char='Clean through first draw; harshness entered at exactly 417°F (end of first draw, ~20s), mild but present and slowly building through the hold.',
        intensity="Very hard — eyes blurring, body feels like it's vibrating ~14 minutes post-session.",
        dab_notes="Same golden as last time, maybe more reclaim than last time too. Harshness hit exactly at the end of the first draw which was also exactly when temp hit 417. It was mild but present and slowly increasing through rest of the draw. Very hard. Eyes are blurring, body feels like it's vibrating — about 14 minutes after session open.",
        analysis="417°F on Rig 3, slightly larger load than Run 10. Harshness appeared at exactly the moment the temperature reached 417°F — end of the first draw (~20s), immediate on endpoint arrival, not a hold-duration accumulation effect. Mild but present and building through the hold. Run 10 (415°F, comparable load) was clean across two full draws. Two-degree difference, clean outcome vs. immediate harshness onset: the ceiling may sit somewhere in the 415–417°F range on this rig. Swab came back very light golden with slightly more reclaim than Run 10 — consistent with less complete vaporization at a lower endpoint, though the read is noisy at this level of difference. Effect landed very hard — a meaningful potency step up from Run 10's medium.",
    ),
    CompletedRun(
        strain='Orange Candy',
        run_date=date(2026, 5, 23),
        sessions_prior_today=2,
        utc_logged_at=datetime(2026, 5, 24, 4, 21, tzinfo=timezone.utc),
        waypoints=OC_RUN12,
        equipment=RIG_3,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — up 1°F from Runs 9–10, down 1°F from Run 11',
        swab='Light golden.',
        session_char='First draw flavorful with bitter citrus note; harshness entered ~35s in (15s into 416°F hold), mild and never acute.',
        intensity='Medium.',
        dab_notes='Got harsh at about 15 seconds left on the timer, and never got super harsh. Swabs were light golden. Intensity medium right now. First draw was flavorful, that increasingly familiar bitter citrus note came through from the beginning.',
        analysis="416°F on Rig 3 — between Run 10's clean 415°F and Run 11's immediate-harshness 417°F. Harshness entered at ~35s, 15 seconds into the hold, mild and never acute. For comparison, Run 11 (417°F) had harshness at endpoint arrival (~20s, immediately). The gradient is directionally consistent across three adjacent endpoints: 415°F clean, 416°F mild harshness entering mid-hold, 417°F immediate on arrival. Swab light golden, consistent with the sapphire OC pattern. Intensity medium — same read as Run 10 at 415°F, though this was the third session of the day, so the lack of intensity gain over 415°F is hard to read cleanly. Bitter citrus note from the first draw — consistent with OC's orange lineage expressing in vapor; the same cross-strain citrus note has appeared in MB9ZST R1 (tangerine) and MBD R4 (citrus rind), though the connection is not established.",
    ),
    CompletedRun(
        strain='Orange Candy',
        run_date=date(2026, 6, 3),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 3, 22, 49, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_5,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve &nbsp;|&nbsp; <strong>Equipment:</strong> Inaugural Rig 5 (sapphire + dual ruby pearls) run',
        swab='Dark golden — noticeably darker than Rig 3 OC runs; not brown. Second cycle context: ran a second cycle when first ended, denser vapor but getting toasty — extra residue likely from the second pass, not the first cycle running hot.',
        session_char='First draw: distinct orange peel note — closest flavor-name match OC has shown. Wispy vapor throughout first cycle; material left at 50s. Second cycle: denser vapor, toasty taste, stopped there.',
        intensity='Very very very stoned.',
        dab_notes="Dark golden swabs, noticeably darker than what we've been smoking but not at all into brown. First short draw and I got an interesting orange peel note, closest I've had to any flavor that would match the name. Vapor was wispy through the whole session, so much so that I ran a second cycle when it ended, and that cycle produced denser vapor but a taste that it was getting toasty. That explains the darker swabs. But I got very very very stoned. Not much else going on flavor wise, I believe this was an older jar when I got it.",
        analysis="First OC run on Rig 5 (sapphire + dual ruby pearls). The intensity question from Run 12 is directionally answered — first dab of the day at 416°F, very very very stoned, clearly above the medium read at 415°F on Run 10. The rig variable is a confound: Rig 5's dual ruby pearls carry more thermal mass than Rig 3's 6mm quartz pearl, so some of the intensity bump may reflect rig rather than endpoint temperature. Wispy vapor throughout the first cycle is consistent with Rig 5's pattern on BB36#2 — this rig appears to underperform on vapor density at the baseline curve for some strains. Material remained at 50s (second cycle confirmed it: denser vapor, toasty signal, residue left over). Darker swabs are most likely explained by the second cycle: the toasty taste on the rerun indicates re-heated residue, not a floor signal from the first cycle. Orange peel note on first draw is the most name-accurate flavor OC has shown — this specific character is new. User notes this jar was older when acquired, which may relate to the restrained flavor profile across most runs. Next: repeat 416°F on Rig 5 — if wispy vapor and leftover material persist, that's a Rig 5 / OC pattern, not a one-off; Alternatively, one Rig 3 repeat at 416°F isolates the rig question cleanly.",
    ),
    CompletedRun(
        strain='Orange Candy',
        run_date=date(2026, 6, 4),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 4, 22, 37, tzinfo=timezone.utc),
        waypoints=OC_RUN14,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s ramp; up 4°F from baseline',
        swab='Very beige, minimal reclaim.',
        session_char='Vapor ran out before 40s (suspected light load); very very mild harshness in second draw toward the end.',
        intensity='Medium, built to medium-to-high.',
        dab_notes="I suspect I loaded a light load without meaning to. Vapor ran out even before the 40 seconds curve. Very very mild harshness in second hit towards the end, a point for depletion theory. Very beige and minimal reclaim on swabs. Maybe effect is going to grow but I'd say medium intensity right now. Without the finicky business of measuring out the loads, I'm not sure how we will ever isolate this particular variable well enough. Effect is medium to high right now, so it rose up. Got the very clear orange rind note again on first draw.",
        analysis="OC Run 14 on Rig 5, 8s ramp to 420°F, 40s session — first dab of the day. Two variables changed from Run 13 simultaneously: ramp speed (20s→8s) and endpoint (416→420°F), same situation as BB362 Run 6. The swab and session pattern shifted clearly in the same direction as BB362 Run 6: very beige with minimal reclaim vs. Run 13's dark golden and material remaining at 50s requiring a second cycle. These signals match the BB362 pattern on a second strain. Harshness: very very mild in the second draw toward the end, user-attributed to depletion — the load ran out before 40s, and harshness arrived at session end consistent with hot insert contact after the material was spent. User noted suspecting a lighter-than-intended load. This is distinct from OC's Rig 3 pattern, where 417°F produced immediate harshness on endpoint arrival (temperature threshold, not depletion). The depletion read is plausible; a fuller load that fills the 40s session would confirm it. Intensity built from medium to medium-to-high as a first dab. Direct comparison to Run 13's 'very very very stoned' is confounded — Run 13 included a second cycle and this run had a lighter load. Both ramp speed and endpoint changed simultaneously; neither can be isolated as the driver of the swab and vapor shift. Orange rind note appeared again on the first draw — second consecutive run showing this character after Run 13's first instance; too few runs to call it consistent but tracking in the same direction.",
    ),
]

# ── Status ──
STATUS = StrainStatus(
    name='Orange Candy',
    profile_anchor='#oc-profile',
    next_text='Run 15: repeat 8s ramp to 420°F with normal load — clean read on temperature ceiling',
    accent=None,
    slug='oc',
    info=[
        ('Strain', 'Orange Candy (Philosopher Seeds lineage: Naran J × Tropimango — unconfirmed)'),
        ('Producer', 'Nikka T'),
        ('Input', '90 micron full melt bubble hash'),
        ('Consistency', 'Cold cure'),
        ('Nose', 'Strong orange note at cold nose'),
    ],
    terpene_note='<strong>Terpene inference:</strong> Limonene inferred dominant from orange character (Naran J × Tropimango lineage — unconfirmed). See <a href="#terpene-ref">Terpene Reference</a>.',
    next_dab_notes="I suspect I loaded a light load without meaning to. Vapor ran out even before the 40 seconds curve. Very very mild harshness in second hit towards the end, a point for depletion theory. Very beige and minimal reclaim on swabs. Maybe effect is going to grow but I'd say medium intensity right now. Without the finicky business of measuring out the loads, I'm not sure how we will ever isolate this particular variable well enough. Effect is medium to high right now, so it rose up.",
    next_ai_analysis='Before isolating ramp speed from endpoint, repeat this exact curve (8s to 420°F, 40s session) with a deliberate normal or slightly heavier load. A load that fills the session gives a clean temperature-ceiling read — if harshness stays absent or depletion-only through 40s, 420°F is within range on Rig 5 for OC. That unlocks variable isolation: hold 420°F and try the baseline 20s ramp to separate endpoint from ramp speed.',
    next_waypoints=OC_RUN14,
    jar_index='',
)
