"""Sour Tangie — jar file (slug: sourtangie)."""
from datetime import date, datetime, timezone
from Dabby_Core import *

# ── Waypoint constants (local to this jar) ──
SOURTANGIE_HOLD10_DESCENT_GENTLE = [
    Waypoint(time_s=0,  temp_f=440, note='Session open — hot open'),
    Waypoint(time_s=10, temp_f=440, note='Hold at peak — one draw at 440°F'),
    Waypoint(time_s=35, temp_f=420, note='Gentle descent midpoint'),
    Waypoint(time_s=60, temp_f=400, note='Floor'),
]

SOURTANGIE_430 = [
    Waypoint(time_s=0,  temp_f=380, note='Session open'),
    Waypoint(time_s=4,  temp_f=400, note='Steep early climb'),
    Waypoint(time_s=8,  temp_f=430, note='Endpoint'),
    Waypoint(time_s=60, temp_f=430, note='Hold'),
]

SOURTANGIE_HOLD10_DESCENT_GENTLE_430 = [
    Waypoint(time_s=0,  temp_f=430, note='Session open — hot open'),
    Waypoint(time_s=10, temp_f=430, note='Hold at peak — one draw at 430°F'),
    Waypoint(time_s=35, temp_f=415, note='Gentle descent midpoint'),
    Waypoint(time_s=60, temp_f=400, note='Floor'),
]

SOURTANGIE_HOLD_DESCENT_450 = [
    Waypoint(time_s=0,  temp_f=450, note='Session open — hot open'),
    Waypoint(time_s=10, temp_f=450, note='Hold at peak — one draw at 450°F'),
    Waypoint(time_s=30, temp_f=425, note='Gentle descent midpoint'),
    Waypoint(time_s=45, temp_f=410, note='Floor — shorter cycle'),
]

# ── Runs (chronological; run numbers assigned positionally by the generator) ──
RUNS = [
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 10),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 7, 11, 1, 5, 3, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD10_DESCENT_GENTLE,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Open:</strong> 440°F &nbsp;|&nbsp; <strong>Floor:</strong> 400°F — 10s hold at 440°F, then gentle descent; jar opener, baseline skipped',
        swab='dark amber',
        session_char='Dark amber swab with minimal reclaim; small taffy load, first dab of the day, full 60s; strong effect, no harshness reported.',
        intensity='strong',
        dab_notes='I\'m gonna run the 440 hold descent curve on this. The format is super sticky, it reminds me of taffy, so hard to precisely portion load. But I\'m pretty sure I loaded a small one. [Report:] I did my dab at the 440 hold descent. [Swab, both runs:] dark amber, minimal. Both swabs, I thought it was weird too. [Intensity:] strong strong. [Full 60 on both.]',
        analysis='First read on the Sour Tangie jar — the bounded 440°F hold into the gentle descent to 400°F, small taffy load, first dab of the day. Strong effect, no harshness, full 60s. Strong on a deliberately modest load validates the 710 first-run potency caution: the jar is potent and the small load was the right call. The dark amber swab is the surprise on a load this small — but the minimal reclaim says the material delivered rather than cooked in place (contrast FW106 R31, where dark amber came with heavy reclaim from sustained peak cooking material uninhaled). Swab is a within-strain signal only and this is the jar\'s first data point, so dark amber isn\'t yet a floor signal to act on — with only hot-curve runs so far, strain/material character and a hot 440°F open can\'t be separated. Same rig as recent runs (Rig 6). No flavor read this session, so the inferred limonene/bitter-citrus signature is still untested solo.',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 10),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 7, 11, 1, 10, 0, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_430,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Endpoint:</strong> 430°F — 380→430 fast ramp (8s), hold to 60s',
        swab='dark amber',
        session_char='Dark amber swab (a shade darker than Run 1, same to a casual eye), minimal reclaim; bigger-than-normal load, second dab of the day, full 60s; strong effect. Loaded for a big-draw-first, occasional-user opener who coughed/gagged at the 380°F open and tapped out; remainder finished on the 430°F hold.',
        intensity='strong',
        dab_notes='I had most of Sarah\'s dab running on a 380 to 430 ascent curve we ran before, a baseline variation. I did the majority of the 430 part. Sarah is my wife, I loaded her a dab and switched the curve to the ascent to 430 curve. She took a big draw starting at 380 and coughed and gagged. Didn\'t want any more so I finished the rest on that curve. [Load:] bigger than normal but I wouldn\'t say large. [Swab:] dark amber, minimal — Sarah\'s dab maybe slightly darker but casual observer would say same. [Intensity:] strong strong. [Full 60.]',
        analysis='Second dab of the day, on the 380→430 fast-ramp ascent — a bigger-than-normal (but not large) load, opened with a big draw right at the 380°F open by an occasional user who coughed and gagged and tapped out; the majority was finished on the 430°F hold. Strong again, full 60s, swab dark amber with minimal reclaim — maybe a shade darker than Run 1, but same to a casual eye. The dark-amber / minimal-reclaim pairing now shows on two different hot curves (the 440-hold-descent and this 430 ascent) — directional, within this jar, that the color tracks strain/material rather than either specific curve, since the shape differed and the swab didn\'t. Same rig both runs (Rig 6); equipment controlled. The cough/gag on a big draw at the 380°F open is hard to read: a big first draw into a fast-ramping cold start delivers dense vapor quickly, so terpene-load cough (documented on Rig 6 — Hive #1 R8, FW106 R1) is as consistent as harshness — and an occasional user taking an unusually big draw leaves technique and tolerance uncontrolled. Not weighted as a curve signal. Run 2 vs. Run 1 can\'t isolate anything — curve, load, and session order all differ.',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 11),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 7, 11, 20, 5, 2, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD10_DESCENT_GENTLE,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Open:</strong> 440°F &nbsp;|&nbsp; <strong>Floor:</strong> 400°F — 10s hold at 440°F, then gentle descent; same curve as Run 1, ran two cycles',
        swab='dark amber, reddish tint',
        session_char='Dark amber swab with a reddish, dark-BBQ-sauce tint — darker than Runs 1–2, but a two-cycle run (second cycles darken independent of endpoint); minimal reclaim. First dab of the day, full 60s cycle 1 then a cashed second cycle; strong, energetic, functional, a tad racy. Delicious throughout, with a read of a fresh-press terpene difference. Mild throat-and-chest harshness in cycle 1 that resolved by the second cycle and did not return on the spent-material hot-air draw.',
        intensity='strong',
        dab_notes='440 descent, I ran a full cycle, then a second cycle but it was cashed and majority of the long draw (I was already feeling the first cycle) was empty. A point for the accumulation not thermal hypothesis of harshness. The swabs came back dark amber, almost a reddish tint to it-reminded me a little of a dark bbq sauce. Minimal amount. Intensity was quite high at first very energetic, very functional, a tad racy. [Flavor:] It was really delicious throughout, I think I can tell the difference in the fresh press terpenes. A little harshness in throat and chest very mild. [Resolved by the second cycle and did not return on that empty draw.]',
        analysis='Run 3 repeats Run 1\'s bounded 440°F hold into the gentle descent to 400°F — first dab of the day, the jar\'s first daylight run and its first flavor read. Delicious throughout, with a read of a fresh-press terpene difference; that\'s a subjective single-session impression (palate is a weak signal and this is the jar\'s first flavor data), so it\'s noted, not weighted — the inferred limonene/bitter-citrus character still isn\'t specifically confirmed. Mild throat-and-chest harshness appeared in cycle 1 (material present), resolved by the second cycle, and did not return on the cashed second-cycle draw — a long pull through spent material and hot air. That within-session structure (harshness with material, gone on the hot-air-only draw) is a cleaner point for accumulation over thermal than Run 1 offered, and is consistent with the empty-insert control — hot air alone doesn\'t cause harshness; material presence is the necessary condition (Session 106) — at single-instance weight. Chest location adds another instance to the hot-open Rig 6 group (papzp22 R7, bp4rw13 R8, LunarZ R1); no persistence reported and it resolved before session end, so this is chest-location in-session only, not the chest-and-lingers conjunction. Swab dark amber with a reddish, dark-BBQ-sauce tint — darker than Runs 1–2\'s dark amber, but this was a two-cycle run and second cycles darken swabs independent of endpoint (bp4rw13 R5–R8, FW106 R27), so the darker read is cycle-confounded, not a new floor signal; reclaim stayed minimal, so material delivered rather than cooked (the deliver-vs-cook read comes off reclaim and effect, not color). Strong — energetic, functional, a tad racy. Same rig throughout (Rig 6); load not stated this run.',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 11),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 7, 12, 0, 0, 49, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD10_DESCENT_GENTLE,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Open:</strong> 440°F &nbsp;|&nbsp; <strong>Floor:</strong> 400°F — 10s hold at 440°F, then gentle descent; same curve as Runs 1 &amp; 3, over-load carried a second cycle',
        swab='dark amber, dark-BBQ-sauce tint',
        session_char='Dark amber / dark-BBQ-sauce swab; normal reclaim, up from the minimal of Runs 1–3, tracking a bigger (unintentional) load. Second dab of the day, full 60s cycle 1 into a second cycle that cashed partway; dense and flavorful throughout, toast on the exhale of the final ~75%-of-a-draw once material was spent. Strong, energetic and functional (a "yoga strain"); delicious, same fresh-press terpene read as Run 3. No harshness reported.',
        intensity='strong',
        dab_notes='Wow, so good. I\'m going to be really interested in seeing the difference in this when it\'s cured. There\'s something really scrumptious to it as it is now. But so hard to load. I thought I loaded normal but it hit dense and flavorful all the way through first cycle and a bit draw of the second cycle. Second draw of second cycle it depleted at maybe 75% of a draw, and toast on the exhale of that one. So, a few thoughts. I loaded a bit more than the first run today. But I didn\'t mean to. It\'s just not easily controlled. So part of our question on how best to use this device expands to considering which curves balance performance with fault tolerance. [Swab:] that bbq sauce color, normal reclaim. Pretty high intensity. Still have a strong sense of "yummyness". [Effect:] This is definitely a yoga strain. I\'m glad I have 4 grams. If only it wasn\'t in taffy format.',
        analysis='Fourth hot-curve run, 2nd dab of the day, and the first clear load-overshoot — a bit more than the day\'s first dab, unintentional (the taffy resists portioning). The curve absorbed it: dense and flavorful through cycle 1 and most of a second, with toast only on the final cashed draw once material was spent — residue-scorch on depletion (same read as Hive #1 R10), not session order; the fast-depletion timing fits scorch before any accumulated-exposure framing. Reclaim came back normal, up from Runs 1–3\'s minimal, consistent with the bigger load leaving more residue; with the strong effect and dense vapor it still reads deliver-side, not cooked-in-place (contrast FW106 R31\'s dark amber with heavy reclaim from sustained peak). Swab dark amber / dark-BBQ-sauce again, but this was a two-cycle run and second cycles darken swabs independent of endpoint (bp4rw13 R5–R8, FW106 R27) — cycle-confounded like Run 3, and within-strain only. Strong and energetic (a "yoga strain"), matching Run 3\'s energetic/functional/racy read — two consistent daylight reads, directional for this jar running up rather than sedating; flavor delicious with the same fresh-press terpene impression, noted at weak-signal weight, so the inferred limonene/bitter-citrus still isn\'t specifically confirmed. No harshness this run, unlike Run 3\'s mild chest-and-throat. Same rig (Rig 6); against Runs 1/3 order and load both differ, so no isolation. As a single supporting observation, the over-load carrying into a second cycle rather than cooking is consistent with the descent-curve limiting-factor pattern and the load-fault-tolerance read — opening hot and descending puts peak heat where material is densest and the cool floor where depletion lands.',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 12),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 7, 12, 20, 23, 14, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD10_DESCENT_GENTLE_430,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Open:</strong> 430°F &nbsp;|&nbsp; <strong>Floor:</strong> 400°F — 10s hold at 430°F, then gentle descent (teal); cooler open than Runs 1/3/4, ran two cycles',
        swab='dark golden, minimal',
        session_char='Dark golden swab with minimal reclaim — the jar\'s first lighter read after four dark-amber runs; bigger-than-normal load (the taffy resists portioning), second dab of the day, two full 60s cycles. Terp-forward, tasty, dense vapor; strong. Harshness escalated mild→medium at the bottom of the throat and in the chest, and a water sip did not clear it. Stopped on a lot of hits plus the harshness turning unpleasant.',
        intensity='strong',
        dab_notes='Holy shit that first cycle was kicking. So much terps. [Going for another round.] Second cycle just kept delivering. Tasty hits dense vapor, mild and then medium harshness at bottom of throat and in chest. Water didn\'t mediate. I\'m stopping because I\'ve had a lot of hits and also the harshness is unpleasant. [Swab:] Swabs were dark golden, pretty minimal. [Load:] Bigger than normal load cause of the format.',
        analysis='Run 5 is the jar\'s first teal run — the 430°F bounded-hold descent, a 10°F cooler open than the 440°F curve of Runs 1/3/4 — taken to test whether the persistent dark-amber swab is heat-driven or strain character. Not the clean measurement planned (first-dab, single-cycle baseline 420°F ramp): this was a 2nd dab, two full 60s cycles, bigger-than-normal load (the taffy resists portioning — Run 4\'s standing problem). The swab is the payoff: dark golden, minimal reclaim — the jar\'s first read lighter than its four dark-amber runs, and lighter despite being a two-cycle run, where second cycles darken independent of endpoint (bp4rw13 R5–R8, FW106 R27). That the darkening confound points the other way makes the lightening a real directional signal that the color is at least partly heat-driven — but it\'s one run, curve/order/load all differ from the amber runs, and swab is within-strain only, so it\'s an observation, not settled. Bigger load, minimal reclaim, strong, dense = deliver-side, not cooked — the descent absorbing an over-load, as on Run 4. Harshness escalated mild→medium at the bottom of the throat and chest, and a water sip didn\'t clear it — the log\'s first full water non-response (six prior were full resets, LunarZ R3 partial). Vapor density and cumulative exposure are the leading, inseparable candidates: the bigger load draws denser vapor, and 2nd dab + two cycles + a lot of hits is a session-long airway load a single sip wouldn\'t reset — the accumulation-over-thermal read the user flagged on Run 3, single-instance weight. Chest location adds to the hot-open Rig 6 group (papzp22 R7, bp4rw13 R8, LunarZ R1–R3, Sour Tangie R3), here at a 430°F open like LunarZ R2/R3; no persistence reported, so in-session location only, not the chest-and-lingers conjunction. Terp-forward and tasty, consistent with the R3–R4 fresh-press read (weak signal). Rig 6 throughout; strong.',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 12),
        sessions_prior_today=2,
        utc_logged_at=datetime(2026, 7, 13, 1, 8, 4, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD10_DESCENT_GENTLE_430,
        equipment=RIG_6,
        duration_seconds=60,
        endpoint_note='<strong>Open:</strong> 430°F &nbsp;|&nbsp; <strong>Floor:</strong> 400°F — 10s hold at 430°F, then gentle descent (teal); same curve as Run 5, ran two cycles',
        swab='amber, normal',
        session_char='Amber swab with normal reclaim — lighter than the four 440°F-open runs (R1–R4) and in line with Run 5\'s dark-golden read at the same cooler open. Third dab of the day, full 60s cycle 1 into a second cycle stopped after the second draw; tasty and dense throughout, strong (quite high). Harshness built from ~20s left in cycle 1 to a solid medium by the second draw of cycle 2, throat-and-chest; no water taken. Stopped on the harshness.',
        intensity='strong',
        dab_notes='Ok, I did it. Tasty and dense throughout. It wasn\'t done at first cycle so did a second. Harshness building from maybe 20 seconds left in first cycle to a solid medium in second draw of second cycle. I stopped after that. Swabs are Amber, normal amount. Intensity is quite high. I think my intuition is building for shorter cycle at a 450 hold and gentle descent. [Harshness location:] both throat and chest. [Water:] no.',
        analysis='Run 6 repeats the teal 430°F bounded-hold descent (same curve as Run 5), a 3rd dab of the day over two cycles — full 60s cycle 1 into a second cycle stopped after the second draw. Like Run 5, not the clean first-dab single-cycle isolation the plan called for; that read has now failed to happen two runs running. Swab amber with normal reclaim. Both 430°F-open runs (R5 dark golden, R6 amber) came in lighter than the four 440°F-open runs (R1–R4, all dark amber) — and R6 stayed lighter despite being a two-cycle run, where second cycles darken independent of endpoint (bp4rw13 R5–R8, FW106 R27). Two consistent runs with the darkening confound pointing the other way is directional, within this jar, that the swab color is at least partly heat-driven (cooler open → lighter swab); load and session order still differ across the amber and lighter runs, and swab is within-strain only, so directional, not settled. Normal reclaim with strong, dense vapor reads deliver-side, not cooked (contrast FW106 R31\'s dark amber with heavy reclaim from sustained peak). Harshness built from ~20s left in cycle 1 to a solid medium by the second draw of cycle 2, throat-and-chest; no water was taken. That escalation matches Run 5 (also 430 teal, later dab, two cycles, escalating mild→medium chest-and-throat) — two consistent runs now that this curve under heavy cumulative load throws escalating chest-and-throat harshness. Vapor density and cumulative exposure stay the leading, inseparable candidates: dense vapor plus a 3rd dab carried across two cycles is a session-long airway load. Because no water was taken, Run 6 doesn\'t extend Run 5\'s water non-response — whether a sip resets this curve under lighter load stays open. Chest location adds to the hot-open Rig 6 group (papzp22 R7, bp4rw13 R8, LunarZ R1–R3, Sour Tangie R3/R5), here at a 430°F open like LunarZ R2/R3 and Sour Tangie R5; no persistence reported, so in-session location only, not the chest-and-lingers conjunction. Tasty and dense throughout, consistent with the R3–R5 terp-forward reads (weak palate signal). Same rig (Rig 6); load not stated. Against Runs 1/3/4/5, order and cycle count differ — no clean isolation.',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 13),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 7, 13, 21, 36, 47, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD_DESCENT_450,
        equipment=RIG_6,
        duration_seconds=45,
        endpoint_note='<strong>Open:</strong> 450°F &nbsp;|&nbsp; <strong>Floor:</strong> 410°F — 10s hold at 450°F, then shorter gentle descent (grey); hottest open logged, ran two cycles',
        swab='dark golden/amber, normal',
        session_char='Dark golden/amber swab with normal reclaim — not the darkest despite the hottest open logged (450°F) and a two-cycle run. Bigger-than-modest load (the taffy resists portioning), first dab of the day, two cycles at ~1.5 draws each (~3 draws total). 25-second first draw: first ~10s super tasty with a specific sweet tangerine note, the top end a near-gag terpene-load cough with tears. Strong but functional and creative (yoga-strain character); terp-forward and delicious throughout. Throat-and-chest harshness present alongside the terp cough — distinct mechanisms, both present this run.',
        intensity='strong',
        dab_notes='[Load, pre-dab:] Normal ish not modest load on the 450 descent. [Report:] Ok, that cycle was a punch of terps! Almost gagging, coughing, tears. I could barely take a second rip and that was small as the cycle ended. I\'m going to run a second cycle to see how much material is left, because that was at most 1.5 regular hits. Btw the first 10 seconds of the 25 second first rip were super tasty, and the coughing was producing a very specific sweet tangerine note. This feels like useful data for trying to design the curve. [Second cycle:] About 1.5 draws left in second cycle. So if I had modulated myself better I might have finished it in one 45 cycle. [Next-run thought:] right, so i\'m thinking shorter but higher frequency rips on same curve before messing with it. [Swab / intensity / mechanisms:] swabs were dark golden/amber, normal amount. it hit hard, but was still the functional and creative energy expected, definitely different mehcanisms. sometimes they\'re happening at same time but sometimes they arent. [Harshness — both throat and chest:] yes, both were present, thorat and chest.',
        analysis='Run 7 is the grey 450°F bounded-hold + shorter-descent\'s debut — the hottest open logged for this jar — first dab of the day, two cycles (~45s each), a normal-ish load (bigger than the plan\'s modest call; the taffy resists portioning, the jar\'s standing problem). It deviated from the planned modest single-cycle isolation, and the deviation is itself data: the load ran ~1.5 draws per cycle, ~3 draws total, and the user ran the second cycle to gauge what was left. The top of the 25-second first draw was a terpene-load cough — dense terp-forward vapor, coughing and tears — which the user explicitly distinguishes from harshness as a separate airway mechanism (both were present this run, sometimes co-occurring, sometimes not). That distinction is the cleaner framing the log has been trying to hold. The first ~10 seconds carried a specific sweet tangerine note — the first solo flavor read that names the inferred Tangie character (California Orange lineage), rather than the generic "delicious/fresh-press" reads of R3–R5; weak-palate, single-instance, and it arrived mid-cough, so noted, not confirmed. No selective-delivery mechanism is implied: at 450°F terpenes and cannabinoids are all above boiling, so the front-loaded flavor is the dense bolus at peak temperature, not fractional distillation. Throat-and-chest harshness was present alongside the cough. R7 adds a first-dab instance to R5/R6\'s throat-and-chest runs — three now — but across different curves (R5/R6 teal 430°F, R7 grey 450°F) and conditions: R7\'s first-dab status removes the later-dab confound R5/R6 carried, while two cycles, the bigger load, and the hotter 450°F open all keep within-session cumulative exposure and peak temperature live, so it isn\'t clean isolation. Chest location adds to the hot-open Rig 6 group (papzp22 R7, bp4rw13 R8, LunarZ R1–R3, Sour Tangie R3/R5/R6), here at the hottest open logged; no persistence reported, so in-session location only, not the chest-and-lingers conjunction. Swab dark golden/amber, normal reclaim — notably not the darkest swab despite the hottest open and a two-cycle run (second cycles darken independent of endpoint), but color-call overlap and the differing confounds mean it\'s within-strain noise, not a floor signal to act on; normal reclaim up from R1/R3\'s minimal tracks the bigger load, and with strong dense delivery it reads deliver-side, not cooked. Strong but functional and creative — the "yoga strain" character now across R3/R4/R7, directional for this jar running up rather than sedating. Rig 6 throughout; against R5/R6, curve and order differ, so no clean isolation.',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 13),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 7, 14, 2, 40, 1, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD_DESCENT_450,
        equipment=RIG_6,
        duration_seconds=45,
        endpoint_note='<strong>Open:</strong> 450°F &nbsp;|&nbsp; <strong>Floor:</strong> 410°F — 10s hold at 450°F, then shorter gentle descent (grey); same curve as Run 7, large load, ran two cycles',
        swab='golden to brown',
        session_char='Golden-to-brown swab across four swabs — double the usual — on the heaviest reclaim this jar has thrown; most reclaim ever logged here. Large load (the taffy resists portioning), second dab of the day, two full ~45s cycles on the grey 450°F bounded-hold descent, no third. Very tasty and very dense both cycles; mild harshness about halfway through cycle 1 building to medium-high mostly in the chest, cycle 2 nearly identical. Very very hard — past the functional "yoga" register of the modest-load runs. Shorter draws helped control the terpene-load coughing.',
        intensity='strong',
        dab_notes='It\'s so hard to load just a little cause it so sticky and stringy. A real pain in the ass. No getting around it, this was a large load. [After first cycle:] Very tasty, very dense. Got mildly harsh about halfway through and built from there. Ended at medium high mostly in chest. Could this be load related? Accumulated over days of dabbing? Over 2 days in a row of this fresh press deliciousness? Short sips did definitely help me keep sipping. I\'m gonna do a second cycle because 1) it was a big load and 2) I\'m curious what\'s left. There was a full second cycle in there, almost identical pattern as first. I\'m still curious about the end but not so much that I\'m running a third cycle. Hey the most reclaim ever on that one — set a note to do a full clean before next run. [Swab:] ranged from golden to brown. Enough reclaim that I used double the normal amount of swabs to clean the insert (four). Hitting very very hard. I don\'t think I could do yoga with this dose. [Short sips = draws:] Draws. It goes against my body memory not to draw long but shorter is better for controlling the coughing.',
        analysis='Run 8 is the grey 450°F bounded-hold descent again (same curve as Run 7), and it deviated hard from the planned clean read: a large load, second dab of the day, two full ~45s cycles instead of the modest first-dab single cycle. The deviation is the data — this is the load-fault-tolerance thread at its limit. The headline is reclaim: the heaviest this jar has thrown, four swabs to clean an insert that usually takes two. Material clearly delivered — it hit very very hard, past the functional "yoga" register of the modest-load runs (R3/R4/R7) — so the heavy reclaim reads as too much material for two cycles to clear, not material failing to vaporize (contrast FW106 R31\'s heavy reclaim from an under-drawn sustained peak). Clearest sign yet the load outran the curve\'s capacity: the descent absorbed the overshoot on R4/R5, but this load found the ceiling. Swab golden-to-brown — the brown end is the darkest logged here, but it\'s a cleanup artifact of scrubbing the heaviest reclaim across four swabs on a two-cycle run (second cycles darken independent of endpoint — bp4rw13 R5–R8, FW106 R27), not a clean floor signal to act on; swab is within-strain only. Intensity scaling with load past the functional window is a within-strain, directional read (R3/R4/R7 functional at modest/normal → R8 flattening at large), though load is imprecise on this taffy and order differs. Harshness went mild about halfway through cycle 1, built to medium-high mostly in the chest, and cycle 2 was nearly identical — dense vapor throughout with the heaviest reclaim means this wasn\'t depletion-driven (material remained). Vapor density and cumulative session exposure are the leading, inseparable candidates: a large load draws denser vapor, and a 2nd dab across two cycles is a session-long airway load. The user raised load and multi-day accumulation ("2 days in a row of this fresh press") as candidates — load/density is the stronger within-session read; the multi-day version is weakened by the FW106 R15 precedent (identical conditions the next day ran dramatically better) and by this jar throwing chest harshness on genuine first dabs (R3, R7), so it doesn\'t need a running start; captured at user-suggested weight. Chest location adds to the hot-open Rig 6 group (papzp22 R7, bp4rw13 R8, LunarZ R1–R3, Sour Tangie R3/R5/R6/R7); mostly-chest here, no persistence reported, so in-session location only, not the chest-and-lingers conjunction. One technique data point: shorter draws helped control the terpene-load cough (distinct from the harshness — the R7 distinction holding), against the user\'s body-memory pull to draw long — an observation toward the draw-pacing lever, though under a large load, not the clean modest test. Same rig throughout (Rig 6); against Runs 5–7, load, order, and cycle count all differ, so no clean isolation.',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 14),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 7, 15, 0, 8, 14, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD_DESCENT_450,
        equipment=RIG_6,
        duration_seconds=45,
        endpoint_note='<strong>Open:</strong> 450°F &nbsp;|&nbsp; <strong>Floor:</strong> 410°F — 10s hold at 450°F, then shorter gentle descent (grey); modest load, single cycle depleted ~10s early',
        swab='beige, minimal',
        session_char='Beige swab with minimal reclaim — the lightest read the jar has logged, at the hottest open (450°F) and a single cycle. Deep-cleaned insert; modest load, first dab of the day, one ~45s cycle that depleted ~10s before the end (the drawn-out empty tail gave no vapor, cough, or harshness). Terp-forward but slightly less tasty than prior runs (material starting to cure after two days out of the fridge). Mild. A hint of base-of-throat harshness, no chest, not heartburn-quality — the first hot-open run on this jar without the chest/heartburn component.',
        intensity='mild',
        dab_notes='Rig has been deep cleaned. I left the fresh press out for past couple days and it\'s slowly starting to cure. Easier to load today, I\'m pretty sure I got a modest one. I also put it back in the fridge to try and stop the curing, that fresh press taste! [Report:] modest load was depleted before end of first cycle, maybe 10 second left when no more vapor but I tried hitting it till the end. No vapor, no coughing, no harshness. Slightly less tasty than previous runs, but plenty of terps and coughing. Just a hint of harshness at base of throat. Swabs were beige and minimal. [Chest:] no chest and throat harshness didn\'t feel like heartburn. [Intensity:] revised to mild.',
        analysis='The clean modest single-cycle first-dab read Runs 5–8 all missed: deep-cleaned insert, modest load, one 45s cycle depleted ~10s early, the empty-tail draw giving nothing back (no vapor/cough/harshness — material-presence-necessary again). Beige/minimal swab, the lightest the jar\'s logged — at the hottest open and a single cycle, the strongest within-jar case yet that cycle count, not endpoint, drives swab color here (second cycles darken independent of endpoint — bp4rw13 R5–R8, FW106 R27). Mild intensity tracks the modest load. Harshness fell to a hint at the base of the throat — no chest, not heartburn-quality, the first hot-open run on this jar to shed the chest/heartburn component R3/R5/R6/R7/R8 all carried. A clean modest first dab losing the chest at a still-450°F peak points that signal away from peak temperature toward load/draw factors; tracked against the user\'s esophageal anatomy as the candidate locus. Slightly-less-tasty-but-terp-forward fits the material starting to cure. Rig 6.',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 14),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 7, 15, 1, 6, 59, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD_DESCENT_450,
        equipment=RIG_6,
        duration_seconds=45,
        endpoint_note='<strong>Open:</strong> 450°F &nbsp;|&nbsp; <strong>Floor:</strong> 410°F — 10s hold at 450°F, then shorter gentle descent (grey); same curve as Runs 7–9, larger load carried a one-draw second cycle',
        swab='dark gold, slightly more than normal reclaim',
        session_char='Dark gold swab with slightly-more-than-normal reclaim, tracking a larger-than-intended load — the taffy is harder to portion cold from the fridge. Second dab of the day, full ~45s first cycle on short draws plus one long draw into an all-but-depleted second cycle. Medium. Base-of-throat harshness, not heartburn, no chest — despite the bigger load and a second cycle. Terp-forward.',
        intensity='medium',
        dab_notes='The sourtangie jar is back out of the fridge. MUCH harder to load refrigerated. I tried for modest, it\'s closer to normal I think. [Report:] Definitely wasn\'t modest. Didn\'t finish it with 1 cycle. Base of throat harshness, not heartburn. [Second cycle:] It was all but depleted, one draw only in second cycle. [Short draws?] Yes on first cycle no on second. [Swab:] Dark gold. Slightly more than normal amount of reclaim on swabs. It was maybe larger than even I thought. It hit medium I think.',
        analysis='Grey 450°F again, 2nd dab, larger-than-intended load — cold-from-the-fridge taffy resisted portioning (inverse of R9\'s cure-softened load). Short draws through the dense first cycle, one long draw into a spent second cycle. Signal: this hit R7/R8\'s chest conditions — bigger load, two cycles — and the chest/heartburn still didn\'t appear, only base-of-throat harshness. Directional with R9 that draw technique through the material-present phase gates the chest/heartburn leg, not load or cycle count — but not clean, since the only long draw came on an all-but-empty insert, so a hard pull on a full load stays untested. Tracked against the user\'s esophageal anatomy; the throat harshness is the separate airway-mucosal signal. Dark gold swab, slightly-more reclaim, tracks the bigger load and the long second-cycle draw. Medium, up from R9\'s mild. Rig 6.',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 15),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 7, 15, 19, 31, 25, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD_DESCENT_450,
        equipment=RIG_6,
        duration_seconds=45,
        endpoint_note='<strong>Open:</strong> 450°F &nbsp;|&nbsp; <strong>Floor:</strong> 410°F — 10s hold at 450°F, then shorter gentle descent (grey); same curve as Runs 7–10, modest load, single cycle depleted ~2s early',
        swab='light golden, minimal',
        session_char='Light golden swab with minimal reclaim — the lightest since Run 9\'s beige; modest load, first dab of the day, long draws (the planned short draws were forgotten), one ~45s cycle that depleted with ~2 seconds left. Mild-to-medium intensity; a "great get-shit-done strain and dose," functional. Clean — no chest and no throat harshness, the payoff of long draws through a present modest cycle.',
        intensity='mild-to-medium',
        dab_notes='Ok modest load and 450 curve. [Report:] beautiful run but i forgot to do short draws! Depleted with 2 seconds left in cycle. Light golden swabs, minimal reclaim. Great get shit done strain and dose. Mild to medium intensity. [Chest?] First one was cleeeeeeean.',
        analysis='The planned clean modest first-dab read — but with long draws instead of the short ones the plan called for (the user forgot), which makes the deviation the more informative run: modest load with long draws is the cell Run 9 (short draws) and Run 10 (bigger load, one real cycle) never isolated. It came back clean — no chest, no throat. That weakens the draw-technique-as-lever read carried from Runs 9–10 (the working position was that short draws were gating the chest): drawing long through a present, modest single cycle did not bring the chest, so draw length isn\'t what gates it here — directional, one run. Light golden / minimal-reclaim swab, the lightest since Run 9\'s beige, consistent with the within-jar read that cycle count (not endpoint) drives swab color here — a single modest cycle runs light, and second cycles darken independent of endpoint (bp4rw13 R5–R8, FW106 R27); within-strain only. Mild-to-medium intensity tracks the modest load; the "get-shit-done" functional character continues the R3/R4/R7 yoga-strain read. Single-cycle depletion with material spent reads as delivered, not cooked. Same rig throughout (Rig 6); equipment controlled. Third straight run without the chest leg (R9–R11).',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 15),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 7, 15, 22, 0, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD_DESCENT_450,
        equipment=RIG_6,
        duration_seconds=45,
        endpoint_note='<strong>Open:</strong> 450°F &nbsp;|&nbsp; <strong>Floor:</strong> 410°F — 10s hold at 450°F, then shorter gentle descent (grey); same curve as Run 11, larger load, two cycles',
        swab='dark golden',
        session_char='Dark golden swab (darker than Run 11\'s light golden, consistent with two-cycle darkening), reclaim not recorded; larger-than-expected load (the taffy resists portioning) across two cycles. Second dab of the day, ~45s cycles. Lots of terpene-load coughing, separated from harshness; mild harshness in the last third of cycle 1, throat only — no chest. Tasty; medium intensity, still functional ("still ready for yoga").',
        intensity='medium',
        dab_notes='[4:00pm dab, from "at 4:00 and another now, still on that sour tangie".] Load was larger than expected, ran two cycles. Lots of terp coughing. Mild harshness in last third of the first cycle. Tasty. Medium intensity, still ready for yoga. [Swab:] Swab was dark golden. [Harshness location:] Throat harshness.',
        analysis='Same grey 450°F curve, 2nd dab of the day, larger-than-expected load carried across two cycles (the taffy\'s standing portioning problem). Lots of terpene-load coughing — again separated from harshness, the R7 distinction holding. Mild harshness in the last third of cycle 1, throat only, no chest — notable against R7/R8, which ran this same 450°F curve at bigger loads over two cycles and both threw chest. R12 sits in that load/cycle territory and stayed chest-free with only mild throat harshness. Session order differs across those comparisons (R12 2nd dab vs. R7 1st, R8 2nd) and load is imprecise on this taffy, so it isn\'t clean isolation — but it extends the post-Run-9 chest absence to a fourth straight run, now including a larger two-cycle load. Dark golden swab, darker than Run 11 and consistent with two-cycle darkening (bp4rw13 R5–R8, FW106 R27) rather than a floor signal; within-strain only, reclaim not recorded. Medium intensity, still yoga-capable — functional character holding. Same rig (Rig 6). Against Run 11, load, session order, and cycle count all differ — no clean isolation.',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 15),
        sessions_prior_today=2,
        utc_logged_at=datetime(2026, 7, 16, 0, 56, 28, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD_DESCENT_450,
        equipment=RIG_6,
        duration_seconds=45,
        endpoint_note='<strong>Open:</strong> 450°F &nbsp;|&nbsp; <strong>Floor:</strong> 410°F — 10s hold at 450°F, then shorter gentle descent (grey); same curve as Runs 7–12, normal load, second cycle stopped after one hit',
        swab='dark golden into amber',
        session_char='Dark golden into amber swab (the amber edge cycle-confounded on a two-cycle run), reclaim not recorded; normal load, third dab of the day. Full ~45s cycle 1 into a second cycle stopped after one hit — a "had enough" stop, not depletion (material remained). Medium-high intensity, up from Runs 11–12. Throat harshness building, read as day-accumulation; no chest. Terp-forward.',
        intensity='medium-high',
        dab_notes='still on that sour tangie. Same curve, normal load, 2 cycles but only 1 hit from second cycle because I\'d had enough. Swabs were dark golden into amber. Harshness building in throat definitely feels like accumulation the day. Intensity was medium high.',
        analysis='Grey 450°F again, 3rd dab of the day, normal load, two cycles but the user stopped one hit into the second — a "had enough" stop, not depletion (material remained). Dark golden into amber swab; the amber edge is cycle-confounded (second cycles darken independent of endpoint — bp4rw13 R5–R8, FW106 R27), within-strain only, reclaim not recorded. Medium-high intensity, up from Runs 11–12, tracking the third-dab cumulative position more than the normal load. Throat harshness built, which the user read as day-accumulation ("definitely feels like accumulation the day") — captured at user-suggested weight, and today\'s three same-curve, same-rig dabs line up with it: R11 clean → R12 mild throat (last third, cycle 1) → R13 throat building, a within-day escalation of the throat/mucosal leg. Directional for within-day cumulative airway exposure driving the throat harshness; loads varied across the three (modest/larger/normal) so it isn\'t clean, and the multi-day version of this hypothesis was weakened before (FW106 R15 ran identical conditions the next day and was better) — this is the within-day form, which is more plausible and matched by today\'s monotonic climb. Distinct from the chest leg, which stayed absent: R13 is the fifth straight run without chest (R9–R13). Across those five, the two things that flipped at Run 9 and held are the insert deep-clean and the material beginning to cure — they changed together, so which (if either) matters can\'t be separated, and intermittent chest is also consistent with noise (R4, pre-clean, was itself chest-free, so the boundary isn\'t absolute). The load-bearing update: R11 drew long and stayed clean, so draw length — the lever the Run 9–10 read proposed — isn\'t what is holding the chest away; the deep-clean/curing coincidence is the live candidate now, at observation weight with the confounds named. Tracked against the user\'s esophageal anatomy as candidate locus for the chest facet. Terp-forward/tasty character continues (weak palate signal). Same rig throughout (Rig 6); against R11/R12, session order and load differ — no clean isolation.',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 16),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 7, 16, 16, 24, 50, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD_DESCENT_450,
        equipment=RIG_6,
        duration_seconds=45,
        endpoint_note='<strong>Open:</strong> 450°F &nbsp;|&nbsp; <strong>Floor:</strong> 410°F — 10s hold at 450°F, then shorter gentle descent (grey); same curve as Runs 7–13, slightly-larger load, one extra draw into a second cycle',
        swab='dark golden to amber',
        session_char='Dark golden to amber swab with more reclaim than normal, tracking a slightly-larger-than-normal load (the taffy resists portioning). First dab of the day, full ~45s first cycle plus one extra draw into a second cycle; that final draw came off spent material with an off, scorched flavor. Terp-forward and tasty up front with heavy terpene-load coughing, tears, and watering, and no in-session harshness; chest discomfort, heartburn-quality, onset a few minutes after the session ended. Medium-to-high intensity and still climbing toward very high — strong enough to derail the day\'s plans, past the functional "yoga" register of the modest-load runs.',
        intensity='medium-to-high',
        dab_notes='It\'s a slightly larger than normal load, so not modest. But gonna run it on the 450. [Report:] goddamn. First cycle so tasty so terpy lots of coughing, some tears, mouth watering. No harshness until a few minutes afterward and it\'s chest and feels like heartburn. [Second cycle:] There was one more draw on second cycle. That one was better left for the swab, tasted a bit like Chinese restaurant grease dumpster smells. Swabs were dark golden to amber, more reclaim than normal. Intensity is medium to high. Heading to very high it seems…maybe I\'m not getting the cleaning done I was planning. [Clarified: cleaning the house, which I\'d planned — i.e. the dose derailing my plans, not an insert observation.]',
        analysis='Run 14 — grey 450°F bounded-hold + shorter descent again (same curve as Runs 7–13), first dab of the day, a slightly-larger-than-normal load carried through a full first cycle plus one extra draw into a second cycle. The headline: the chest came back. Absent five straight (R9–R13), it reappeared here — but in its post-session-onset form, not in-session. The session itself was clean of harshness, just the terpene-load coughing, tears, and watering the user keeps separate as its own airway mechanism (the R7 distinction holding); the chest, heartburn-quality, arrived a few minutes after the session ended. That shape matches Hive #1 R13/R14 (post-session onset, in-session harshness resolved by end) more than this jar\'s earlier in-session chest runs (R3/R5/R6/R7). Tracked against the user\'s esophageal anatomy as candidate locus. What returned it isn\'t cleanly isolable — load rose past modest, the run went two cycles, insert residue has been rebuilding since the R9 deep-clean, and the material has kept curing, all together. The chest returning on the run where load rose is directionally consistent with both the load and the still-open insert-residue candidates from the R9–R13 stretch, but isolates neither. The one extra second-cycle draw came back scorched on spent material: residue-scorch on depletion, same read as R4\'s cashed draw and Hive #1 R10, not a curve signal. Swab dark golden to amber with more reclaim than normal, tracking the bigger load; the amber edge is cycle-confounded on a two-cycle run (second cycles darken independent of endpoint — bp4rw13 R5–R8, FW106 R27), within-strain only, not a floor signal to act on. Medium-to-high intensity and still climbing toward very high — strong enough the user expected it to derail the day\'s plans, past the functional "yoga" register of the modest-load runs and echoing R8\'s "couldn\'t do yoga with this dose"; effect scaled with the bigger load. Same rig throughout (Rig 6); against R11\'s clean modest first dab, load and cycle count both differ, so no clean isolation.',
    ),
    CompletedRun(
        strain='Sour Tangie',
        run_date=date(2026, 7, 19),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 7, 19, 19, 16, 25, tzinfo=timezone.utc),
        waypoints=SOURTANGIE_HOLD_DESCENT_450,
        equipment=RIG_6,
        duration_seconds=45,
        endpoint_note='<strong>Open:</strong> 450°F &nbsp;|&nbsp; <strong>Floor:</strong> 410°F — 10s hold at 450°F, then shorter gentle descent (grey); same curve as Runs 7–14, normal load, single cycle full 45s',
        swab='golden, minimal',
        session_char='Golden swab with minimal reclaim; normal load (taffy hard to portion smaller than that), first dab of the day, one full ~45s cycle. Perfect flavor throughout, lots of terps and taste, heavy terpene-load coughing. Medium intensity. Chest harshness, heartburn-quality, onset about halfway through the session and persisting after it ended — the jar\'s first clean in-session-plus-lingering instance.',
        intensity='medium',
        dab_notes='Great hit, perfect throughout. Lots of terps and taste, lots of coughing, slight heartburn about halfway through. And intensity was medium. [Heartburn timing:] In session and after. [Swab, load, cycle, curve:] Swab was golden, minimal. Load size was normal, 1 curve, yep 450. [Normal load vs. planned modest:] Hard to portion.',
        analysis='Run 15 — grey 450°F bounded-hold + shorter descent, first dab of the day, single cycle, full 45s. The plan called for a modest load to give a clean read against Run 14; it came in normal instead, the taffy\'s standing portioning problem recurring rather than a deliberate choice. Golden, minimal swab — consistent with the jar\'s established read that cycle count, not endpoint, drives swab color (single-cycle runs read lighter; bp4rw13 R5–R8, FW106 R27 the cross-strain instances). Medium intensity, perfect flavor throughout, lots of terps and taste, heavy terpene-load coughing (the R7-established mechanism, distinct from harshness). The chest came back for a second straight run, but this time both in-session (about halfway through) and persisting after the session ended — this jar\'s first clean instance of the chest-and-lingers conjunction the wisdom layer has been tracking since bp4rw13 R8 and LunarZ R1 (both user-verbatim; this makes a third). Against Run 14, load moved down while insert residue state didn\'t change (unclean since the Run 9 deep-clean) — a small point toward residue over load as the driver, though load wasn\'t at the plan\'s modest target so this isn\'t clean isolation. Also notable: this is a first dab of a new day and still threw chest, which cuts against same-day cumulative exposure as sufficient — Run 13\'s 3rd-dab normal load stayed chest-free. Tracked against the user\'s esophageal anatomy as candidate locus; mechanism otherwise unresolved. Rig 6.',
    ),
]

# ── Status ──
STATUS = StrainStatus(
    name='Sour Tangie',
    profile_anchor='#sourtangie-profile',
    next_text='Run 16: deep-clean the insert, then rerun the grey 450°F curve at the best achievable modest load, single cycle, first dab — the direct residue test.',
    accent=None,
    slug='sourtangie',
    info=[
        ('Strain', 'Sour Tangie (East Coast Sour Diesel × Tangie — DNA Genetics / Crockett; Tangie: California Orange × Skunk #1; Sour Diesel: Chemdawg \'91 × Super Skunk, disputed)'),
        ('Consistency', 'Live rosin (Persy tier)'),
        ('Producer', '710 Labs'),
        ('Nose', 'Super faint — jar cold from dispensary freezer; no distinct notes yet. Weak secondary signal; expect it to open as it warms.'),
    ],
    terpene_note='<strong>Terpene inference:</strong> Limonene inferred dominant from the Tangie side (California Orange × Skunk #1 — citrus/orange lineage); caryophyllene and myrcene from the Sour Diesel side (Chemdawg \'91 × Super Skunk — diesel/gas, though DNA hedges this cross and a competing "DNL" origin exists). Consistent with the limonene-forward bitter-citrus/tangerine character logged when Sour Tangie ran as a layer in the closed Mango Banana #9 + Z + Sour Tangie jar. Not measured. See <a href="#terpene-ref">Terpene Reference</a>.',
    next_dab_notes='',
    next_ai_analysis='Two straight runs with chest now — Run 14 post-session-only, Run 15 both in-session and lingering, the jar\'s first clean chest-and-lingers instance. Between the two, load moved down while insert residue state stayed constant since the Run 9 clean — a small point toward residue over load, and Run 15 landing on a first dab of a new day cuts against same-day accumulation as sufficient (Run 13 stayed clean on a comparable load). Deep-clean the insert again before Run 16, then run the same curve at the best achievable modest load, single cycle, first dab — the direct repeat of the test the Run 9 clean already ran once. Load stays hard to pin exactly on this taffy, so it won\'t be fully clean, but a repeat clean-after-clean pattern would make residue the leading operational read. Expected: chest clears again like it did after Run 9. Surprising: chest persists even right after a fresh clean — that would move the leading candidate back toward load or the material itself.',
    next_waypoints=SOURTANGIE_HOLD_DESCENT_450,
    jar_index='',
)
