"""Watermellos — jar file (slug: watermellos)."""
from datetime import date, datetime, timezone
from Dabby_Core import *

# ── Waypoint constants (local to this jar) ──
FW106_FASTER = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=4, temp_f=400, note='Steep early climb'),
    Waypoint(time_s=8, temp_f=416, note='Endpoint — 8s to 416°F'),
    Waypoint(time_s=40, temp_f=416, note='Hold — 40s session'),
]
WM_RUN9 = [
    Waypoint(time_s=0, temp_f=460, note='Session open — descent mode setpoint (hottest at open)'),
    Waypoint(time_s=40, temp_f=420, note='Endpoint — assumed ~1°F/sec cooling (device rate unmeasured)'),
]
FW106_FASTER_420 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=4, temp_f=400, note='Steep early climb'),
    Waypoint(time_s=8, temp_f=420, note='Endpoint — 8s ramp; up 4°F from operating point'),
    Waypoint(time_s=40, temp_f=420, note='Hold'),
]
WM_RUN15_NEXT = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=4, temp_f=400, note='Steep early climb'),
    Waypoint(time_s=8, temp_f=420, note='Endpoint — 8s ramp'),
    Waypoint(time_s=60, temp_f=420, note='Hold — extended from 40s; single cycle, no second'),
]

# ── Runs (chronological; run numbers assigned positionally by the generator) ──
RUNS = [
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 5, 25),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 5, 25, 17, 12, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_4,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve',
        swab="Clean, golden — warmer than Rig 4's ultra-clean light beige on FW106.",
        session_char='Multiple draws; harshness minimal during session, appeared pronounced post-session and lingered.',
        intensity='Pretty intense. Van Halen sounds amazing.',
        dab_notes="I totally did more draws than I should have and felt the harshness afterward. Throat is sore 10 minutes later. Swabs were clean, more on the golden side than we've been seeing but nothing dark. Effects is pretty intense. Van Halen sounds amazing. [Clarification: harshness didn't show up too intense during but afterward it was pronounced for a long time]",
        analysis="First run of Watermellos on Rig 4, baseline curve. Multiple draws, more than intended. Harshness was minimal during the session but appeared pronounced post-session and persisted — throat still sore at 10+ minutes. This is a distinct presentation from FW106 R2's in-session escalation (draw-by-draw buildup to nearly unbearable on draw 3); the post-session onset here suggests cumulative mucosal exposure that crossed a threshold after the session ended rather than registering acutely during it. Draw count correlates, but the underlying mechanism is unresolved — no baseline exists yet for how this strain behaves at 1–2 draws. Swab came back clean but golden — distinctly warmer than FW106's ultra-clean light beige on the same Rig 4 setup. Whether that's Watermellos' residue character or a temperature signal is unclear from one run. Effects landed pretty intense.",
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 5, 25),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 5, 25, 20, 15, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_5,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve &nbsp;|&nbsp; <strong>Equipment:</strong> Inaugural Rig 5 (sapphire + dual ruby pearls) run',
        swab="Beige — cleaner than Run 1's golden.",
        session_char='Two draws; no in-session harshness, terp cough. Mild post-session throat harshness.',
        intensity='Pretty big — mind racy, not yet to paranoia.',
        dab_notes="First run with Rig 5. Baseline curve, only 2 draws. First draw to 17s remaining, second draw started at 10 seconds remaining and went till end of cycle. Never got harsh but got terp cough. Afterward I can feel some harshness in my throat but it's mild. Maybe this is decent support for the number of draws hypothesis? Swabs are cleaner than last run, into beige territory. Hit is pretty intense right now, I want to go lay down. Effect is pretty big, mind is a bit racy, not to paranoia yet.",
        analysis="Run 2 on Rig 5 (inaugural), two controlled draws. Post-session harshness dropped meaningfully from Run 1 (pronounced soreness at 10+ minutes) to mild — directional support for the draw-count hypothesis. But two things changed simultaneously: draw count (many → 2) and equipment (Rig 4 → Rig 5, second ruby pearl added). The harshness reduction can't be cleanly attributed to either variable alone. Swab came back beige — lighter than Run 1's golden, closer to FW106's ultra-clean light beige on Rig 4. Whether the lighter swab reflects Rig 5's dual pearl vaporizing more completely, or fewer draws extracting less material, is unclear. No in-session harshness with terp cough is a cleaner presentation than Run 1. Intensity still landed big on two draws.",
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 5, 25),
        sessions_prior_today=2,
        utc_logged_at=datetime(2026, 5, 25, 21, 48, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_5,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve',
        swab='Ultra clean beige.',
        session_char='Two big draws; no harshness. Immediate big effect.',
        intensity='Immediate and big.',
        dab_notes='Ultra clean beige swabs, no harshness across two big draws. Immediate big effect. If anything maybe faster climb and 5-10 seconds shorter',
        analysis="Run 3 repeats Run 2's setup exactly — Rig 5, 2 controlled draws, baseline curve. Result was consistent: ultra clean beige swab, no harshness. Second consecutive 2-draw run on Rig 5 without harshness. Post-session harshness that appeared mild on Run 2 wasn't mentioned, suggesting it dropped further or was within noise on the third session of the day. Intensity came on immediately and big — a delivery-speed step up from Run 2's 'mind racy' build, though tolerance confound applies as the third dab of the day. The draw-count pattern holds: Run 1 (many draws, Rig 4) produced pronounced post-session soreness; Runs 2–3 (2 draws, Rig 5) produced no or minimal harshness. The Rig 4→5 change remains an unresolved confound — cross-rig comparison at the same draw count hasn't happened yet.",
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 5, 25),
        sessions_prior_today=3,
        utc_logged_at=datetime(2026, 5, 26, 3, 44, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_5,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve',
        swab='Ultra clean beige.',
        session_char='Three draws; draws 1–2 clean, harshness entered on third draw (starting at 14s remaining). Immediate big effect.',
        intensity='Big, immediate onset.',
        dab_notes='Ultra clean beige swabs. Big flavor on first draw. Harshness at third draw which started at 14 seconds left. Big effect hit fast. No harshness in second draw, flavor was changing by then, still flavorful but less than first draw which started',
        analysis='Run 4 on Rig 5, three draws, baseline curve. Harshness timing is clear on this run: draws 1–2 clean, harshness entered on draw 3 (starting at 14s remaining, ~36s into the 50s session). Flavor tracked depletion across the arc — big and distinct on draw 1, shifting but still present on draw 2, threshold crossed on draw 3. Swab ultra clean beige, consistent across Runs 2–4 on Rig 5. Harshness entered on draw 3, with draws 1–2 clean. Effect immediate and big — consistent with the Rig 5 pattern. Cross-run: FW106 R2 on Rig 4 showed the same draw-by-draw escalation to harshness; harshness entering around draw 3 is now directionally consistent across two strains and two rigs — the underlying mechanism is unresolved.',
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 5, 29),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 5, 30, 0, 56, tzinfo=timezone.utc),
        waypoints=FW106_FASTER,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 416°F — faster ramp (8s), 40s session',
        swab='Beige.',
        session_char='Terp cough on draw 1, no harshness; mildewy note on exhale of draw 2.',
        intensity='Medium high.',
        dab_notes='Beige swabs, no harshness, little terp cough on first draw. Not so tasty, only thing that came through was a mildewy type flavor on exhale of second draw. Medium high intensity. Kept it to 2 draws — gap between them, short second draw at the tail. Load just a bit larger than normal.',
        analysis='Faster ramp (8s to 416°F, 40s session) — first clean first-dab read for Watermellos on the new curve shape. Beige swab consistent with the WM Rig 5 pattern across Runs 2–4. Two draws with a gap between them, no harshness — draw-count ceiling held. Slightly larger load than normal. Terp cough on draw 1 without harshness. Flavor subdued overall; a mildewy note on the exhale of draw 2 — not seen on prior WM runs. Intensity medium high. First dab of the day, no session-order confound.',
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 5, 29),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 5, 30, 2, 6, tzinfo=timezone.utc),
        waypoints=FW106_FASTER,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 416°F — faster ramp (8s), 40s session — same as Run 5',
        swab='Super clean beige.',
        session_char='Two draws; no harshness; flavor subdued; mildewy note from Run 5 absent.',
        intensity='Light to medium; felt like short duration.',
        dab_notes='Swabs super clean beige, not a lot of flavor, light medium intensity feels like short duration, no harshness. No mildewy note obvious.',
        analysis='Run 6 on the faster ramp (same as Run 5), Rig 5, 2nd dab of the day. Super clean beige swab — consistent with WM\'s Rig 5 pattern. No harshness, 2-draw ceiling intact. Mildewy note from Run 5 didn\'t recur — two runs is enough to call it noise. Flavor subdued again: "not so tasty" on Run 5, "not a lot of flavor" on Run 6. Intensity light to medium with a short-duration feel — step down from Run 5\'s medium high, consistent with session order. The subdued flavor across both faster-ramp runs is worth noting in context: baseline Runs 2–4 on Rig 5 didn\'t flag flavor as a problem, and Run 4 specifically had "big flavor on first draw" at the same 416°F endpoint. The faster ramp concentrates delivery in the opening seconds — it suits FW106 ("very very tasty") but may be flattening WM\'s expression.',
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 5, 29),
        sessions_prior_today=2,
        utc_logged_at=datetime(2026, 5, 30, 5, 13, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_5,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve',
        swab='Beige.',
        session_char='First draw ~30s, second draw smaller; earthy note on second-draw exhale; tiny harshness at ~6s left; distinct watermelon note from bubbler residue.',
        intensity='Mild (3rd dab of the day).',
        dab_notes='Beige swabs, first draw 30 seconds, second draw smaller. Tasty first draw, maybe a bit of the mildew on the exhale but this time it tasted more earthy than mildewy. Tiny bit of harshness at 6 seconds left. Just pulled the cooked vapor that was sitting in the bubbler and it had a distinct watermelon note. Effect just mild right now.',
        analysis='Baseline curve, Rig 5, 3rd dab of the day. Beige swab — consistent with WM\'s Rig 5 pattern. Tasty first draw; earthy note on second-draw exhale — similar to Run 5\'s mildewy note but described differently. Run 5 (faster ramp, 1st dab): mildewy. Run 6 (faster ramp, 2nd dab): none. Run 7 (baseline, 3rd dab): earthy. The note may be a second-draw exhale trait that varies by session rather than a curve signal — session order is an unresolved confound. Tiny harshness at 6s left (session tail); absent on Runs 5–6 — could be session order or the 10 extra seconds of hold, not conclusively curve-driven. Distinct watermelon note from residual bubbler vapor — first time this strain character has been named. Flavor comparison to faster ramp inconclusive: "maybe" better — too much noise on the 3rd dab to read clearly.',
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 5, 30),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 5, 30, 22, 0, tzinfo=timezone.utc),
        waypoints=BASELINE_416,
        equipment=RIG_5,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 416°F — baseline curve',
        swab='Clean beige.',
        session_char='2 draws; slight harshness in draw 2 around 12s left (difficult to read); slight mildew note in draw 2, otherwise not a ton of flavor.',
        intensity='Medium high.',
        dab_notes='Swabs were clean beige, slight harshness in draw 2 around 12 seconds left. Little bit of mildew note in draw 2, otherwise not a ton of flavor. Medium high intensity.',
        analysis='Baseline curve, Rig 5, first dab of the day — the clean first-dab read Run 7 called for, resolving the session-order confound on the baseline-vs-faster-ramp flavor comparison. Beige swab, consistent with WM\'s Rig 5 pattern across Runs 2–7. Two draws, slight harshness near the tail of draw 2 (~12s left) — user reports it was difficult to read, so weight is low; directionally consistent with the material-depletion framing (harshness as the load winds down near session end). Flavor subdued again — "not a ton of flavor," matching faster-ramp Run 5 ("not so tasty," also a first dab). With both curve shapes now read clean as first dabs and both subdued, the faster-ramp-flattens-flavor idea floated on Run 6 is not supported — subdued flavor may be the strain\'s character at 416°F rather than a curve-shape signal. The mildewy draw-2 exhale note returned (mildew R5, earthy R7, mildew R8 — 3 of 4 faster-ramp/baseline runs): looking more like a recurring second-draw exhale trait than noise. Intensity medium high, matching Run 5\'s first-dab read.',
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 5, 30),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 5, 31, 2, 13, tzinfo=timezone.utc),
        waypoints=WM_RUN9,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Open:</strong> 460°F &nbsp;|&nbsp; <strong>Endpoint:</strong> 420°F — descent mode (~1°F/sec, assumed)',
        swab='Clean beige.',
        session_char='2 draws; harshness onset ~halfway through draw 1, never got really harsh; load finished with ~10s left. Significant post-session throat soreness.',
        intensity='Medium.',
        dab_notes="Swabs were clean and beige, harshness started about halfway through first draw but never got really harsh. Finished the load with about 10 seconds left on the timer. Intensity was medium. Significant throat soreness after — odd, because I've done higher temp dabs without soreness before.",
        analysis="First descent-mode run for Watermellos and the first in the log — 460°F open descending ~1°F/sec to 420°F over 40s (cooling rate assumed, not measured). Clean beige swab, consistent with WM's Rig 5 pattern — no darkening despite the 460°F open, the hottest this jar has run. Harshness onset halfway through draw 1 is the earliest in WM's history (all prior runs: tail of draw 2 or session tail). One reading is that the descent front-loads the hottest vapor at session open, so early harshness would track opening temperature — but this is a single confounded data point and shouldn't be treated as established; the load also finished early (~10s left, spent ~30s), so depletion can't be cleanly separated either, though harshness here preceded the load running thin. User reported significant post-session throat soreness and noted it as odd against prior higher-temp dabs without soreness — captured as an open observation, not explained. It echoes Watermellos Run 1 (Rig 4), which also showed pronounced post-session soreness distinct from mild in-session harshness; two instances now of a post-session throat signal that doesn't track in-session severity, both on this jar. Whether that's descent-shape, opening-temperature, cumulative airway exposure (2nd dab of the day), or strain-specific is unresolved. Intensity medium — no step up over the 416°F runs despite the much higher open.",
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 6, 9),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 9, 23, 20, tzinfo=timezone.utc),
        waypoints=FW106_FASTER_420,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s fast ramp; up 4°F from prior runs',
        swab='Beige.',
        session_char='3 draws first cycle — almost no vapor and mildewy taste draw 1; pine sol and cough draw 2; toasted flavors draw 3; re-ran for 2 draws, less toasted and less harsh second cycle; no post-session throat soreness; intense.',
        intensity='Intense.',
        dab_notes='First draw to about 21 seconds left. Almost no vapor. Tasted the mildewy taste. Second draw was only about 5 seconds and then I tasted some pine sol and coughed. So third draw finished it. In third draw I tasted some toasted flavors. I had sense there was more so I reran the cycle and did indeed get a nice two more draws that were somehow less toasted and less harsh. What! Beige swabs, intense high. No post-session throat soreness.',
        analysis="Fast ramp to 420°F, first dab of the day — the designed control against Run 9's confounded descent. Three findings: The wispy opening draw is the most surprising result against cross-strain expectations — the 8s fast ramp resolved the low-vapor-density opening on FW106 and BB36 #2 on Rig 5, but it didn't here. Almost no vapor on draw 1 despite the fast ramp; whether this is WM-specific material behavior or something else is unresolved. Toasted flavor on draw 3 is consistent with the pattern of harshness entering around draw 3 at 416°F — draw 3 pushes into depletion territory, and 420°F likely tightens that ceiling marginally. The second cycle coming in cleaner — less toasted, less harsh — is hard to explain; the insert would have cooled during the pause, so remaining material hit a lower starting temperature on re-ramp; plausible but speculative, one data point. No post-session throat soreness is the most significant result relative to WM's history: Runs 1 and 9 both produced it, today didn't. Opening temperature tracks most clearly with soreness across these three runs — Run 1 (Rig 4, rapid heat), Run 9 (460°F descent open), today (380°F ascending, none). Session order is a partial confound on Run 9 (2nd dab). Directional: the throat signal appears linked to high opening temperature, not the 420°F endpoint or Rig 5 itself. Beige swab, intense high — consistent with WM's Rig 5 pattern.",
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 6, 9),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 6, 10, 2, 3, tzinfo=timezone.utc),
        waypoints=FW106_FASTER_420,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s fast ramp; same as Run 10',
        swab='Dark golden.',
        session_char='2 cycles, 2 draws each; mild harshness end of draw 2, throughout draws 3–4; dark golden swab; very hard intensity.',
        intensity='Really hard.',
        dab_notes='Dark golden swabs, ran it two cycles two draws each. Harshness at end of draw 2 and throughout draws 3 and 4. Pretty mild. More than anything I think it points to substandard quality of the rosin. Hit really hard.',
        analysis="Same curve and equipment as Run 10, second dab of the day. The swab shift is the headline — dark golden where Runs 2–10 were consistently beige on Rig 5. Within the floor-indicator framing, dark golden isn't a floor signal, but it's a meaningful departure from WM's established pattern at this endpoint. Whether it reflects jar/material character changing as the jar ages (user's read: substandard quality), extended session heat from the second cycle, or run-to-run variation is unresolved. A 2-draw-only run without a second cycle would separate cumulative heat exposure from material character. Harshness entered at end of draw 2 — slightly earlier than Run 10's clean 2-draw limit but described as mild. Draws 3–4 (second cycle) had persistent mild harshness throughout, consistent with depleted material in the second cycle. The pattern tracks: second cycle scrapes the bottom on a hotter insert. Intensity very hard, consistent with WM's Rig 5 pattern at 420°F. User's quality read logged as stated — a consistent swab and harshness shift across the next few runs would add weight; a single run doesn't establish it.",
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 6, 10),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 10, 23, 4, tzinfo=timezone.utc),
        waypoints=FW106_FASTER_420,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s fast ramp; same as Run 11',
        swab='Dark gold.',
        session_char='2 cycles, 2 draws each; mildew on draw 1; watermelon hint + harshness at tail of draw 2; draws 3–4 (second cycle) tasty, slight throat harshness, toasted by end of draw 4.',
        intensity='Heavy, fast onset.',
        dab_notes='Hit it same as yesterday, 2x2. First draw had the mildew, second had a little hint of watermelon! Harshness peeked through at the very end. Third and fourth were tasty, a tiny bit harsh in throat, toasted by end of 4th. Heavy effect pretty fast. Swabs dark gold.',
        analysis="Run 12 matched Run 11's structure (2x2) and returned the same dark gold swab. Two consecutive dark gold runs now, breaking the streak of beige across Runs 2–10 on Rig 5. The second-cycle-heat isolation still hasn't happened — this run also went two cycles, so the planned single-cycle test didn't land. What's consistent: dark gold appeared on both consecutive 2x2 sessions. Draw-count pattern held — harshness crept in at the tail of draw 2 and escalated through draws 3–4, consistent with the late-session harshness pattern. Mildew on draw 1 is a recurring WM flavor character (Runs 5, 6, 7, 8, 10). Watermelon note on draw 2 is the strain's namesake showing up clearly. Heavy fast-onset effect consistent with WM's history on Rig 5.",
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 6, 10),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 6, 11, 3, 25, tzinfo=timezone.utc),
        waypoints=FW106_FASTER_420,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s fast ramp; same as Runs 11–12',
        swab='Dark gold.',
        session_char='2 cycles, 2 draws each; harsh on 4th draw, second cycle terminated early; not very tasty.',
        intensity='Very hard.',
        dab_notes="2x2. Dark golden swabs, got harsh in 4th draw and terminated only about halfway through second cycle. Nice effect even if it ain't so tasty.",
        analysis="Three consecutive dark gold swabs on 2x2 sessions (Runs 11–13). Single-cycle isolation still hasn't happened, but the streak is now three runs — dark gold is now a three-run pattern. Harshness on the 4th draw with the second cycle cut short fits the pattern from prior runs: second cycle is scraping the bottom on a hot insert. 'Not very tasty' is a new note — Runs 10–12 all had flavor present (mildew, watermelon). Diminished flavor alongside persistent dark gold is directionally consistent with the quality-shift read from Run 11. Very hard effect.",
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 6, 11),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 6, 11, 23, 22, tzinfo=timezone.utc),
        waypoints=FW106_FASTER_420,
        equipment=RIG_5,
        duration_seconds=40,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s fast ramp; same as Runs 11–13',
        swab='Dark golden.',
        session_char='2x2; dark golden swab; harshness at tail of draw 2, medium through draws 3–4; fast onset; very hard effect.',
        intensity='Very hard — fast onset; light eating day (confound).',
        dab_notes="2x2 draws. Harshness in last 2 seconds of second draw and through draws 3 and 4. But not too bad, medium at most. Effects pretty fast but I haven't had much to eat today. Feel pretty big intensity wise. Cold nose on this jar is great but it doesn't at all deliver that flavor when vaped. Jar is probably continuing to cure in the fridge. Always seems like there's lots more to hit at end of 40s.",
        analysis="Fourth consecutive dark golden swab on a 2x2 session. [Color calibration note: photo read as lighter than prior runs by AI; user confirmed dark gold, consistent with Runs 11–13 — a shared color reference session is warranted.] Harshness entered at the very tail of draw 2 and held medium through draws 3–4, consistent with the second-cycle heat pattern but milder than Run 13's early termination. Fast onset, very hard effect; light eating day is a confound on intensity. The single-cycle isolation test remains undone across four consecutive 2x2 sessions. User's consistent observation of material remaining at 40s reframes what the next test should be: a longer single cycle (60s, device ceiling) is more informative than 2-draws-only — removes the reheat while giving the load time to fully express.",
    ),
    CompletedRun(
        strain='Watermellos',
        run_date=date(2026, 6, 11),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 6, 12, 3, 11, tzinfo=timezone.utc),
        waypoints=WM_RUN15_NEXT,
        equipment=RIG_5,
        duration_seconds=60,
        endpoint_note='<strong>Endpoint:</strong> 420°F — 8s ramp; 60s hold (extended from 40s), single cycle',
        swab='Beige.',
        session_char='Many draws; vapor dense throughout; harshness in second half of 60s session.',
        intensity='Very intense.',
        dab_notes='Beige swabs, harshness in the second half of cycle, many draws. Very intense. Vapor was dense throughout. No indication of depletion of material. But the throat harshness was real!',
        analysis="Single cycle, 60s hold — beige swab after four consecutive dark gold 2x2 sessions. The hypothesis was direct: if the swab lightens on single cycle, the reheat was driving dark gold. It lightened. The second cycle was the culprit, not the material. Harshness entered in the second half of the 60s session with vapor dense throughout — user confirmed no depletion. That takes depletion off the table as the mechanism. This is directional support for the heat exposure / airway sensitization hypothesis: continuous draws at 420°F, thermal load accumulating in the airways, harshness crossing the threshold somewhere past 30s with material still present. Consistent with FW106 R14 (first dab, 2 draws, material confirmed remaining, harshness at session tail) — both share the same signature: load intact, harshness arrives as session length accumulates. Very intense, consistent with WM's Rig 5 pattern.",
    ),
]

# ── Status ──
STATUS = StrainStatus(
    name='Watermellos',
    profile_anchor='#watermellos-profile',
    next_text='Run 16: same 60s single cycle at 420°F, larger load — test whether harshness timing tracks load size',
    accent=None,
    slug='watermellos',
    info=[
        ('Strain', 'Watermellos ((Melonade × Gushers) × Purple Ice Water)'),
        ('Consistency', 'Cold cure badder'),
        ('Washer', "Malek's Melts"),
        ('Nose', 'Great cold nose — more fragrant than initial impression; jar appears to be actively cold-curing in fridge post-purchase.'),
        ('Flavor', 'Cold nose does not translate to vapor — flavor in vapor notably muted relative to cold nose intensity.'),
    ],
    terpene_note='<strong>Terpene profile:</strong> Alpha-pinene and beta-pinene label-reported as dominant; caryophyllene label-reported secondary. Label-reported terps are not measured from this batch — treat as directional. Myrcene and limonene inferred from Melonade and Gushers lineage. See <a href="#terpene-ref">Terpene Reference</a>.',
    next_dab_notes='Beige swabs, harshness in the second half of cycle, many draws. Very intense. Vapor was dense throughout. No indication of depletion of material. But the throat harshness was real!',
    next_ai_analysis="Second cycle was the dark gold driver — settled. Harshness with dense vapor in the second half of 60s is directional support for the heat exposure / airway sensitization hypothesis. Run 16: same curve (8s ramp to 420°F, 60s single cycle), larger load. If harshness enters in the same place regardless, load size isn't the variable and heat exposure is the more parsimonious explanation. If the timing shifts — earlier, later, or absent — vapor density is back in play.",
    next_waypoints=WM_RUN15_NEXT,
    jar_index='',
)
