"""WW Z — jar file (slug: wwz)."""
from datetime import date, datetime, timezone
from Dabby_Core import *

# ── Waypoint constants (local to this jar) ──
WWZ_RUN1 = [
    Waypoint(time_s=0, temp_f=375, note='Session open'),
    Waypoint(time_s=15, temp_f=378, note='Extended flat — low-boiling terpene zone (~311°F pinene region)'),
    Waypoint(time_s=40, temp_f=395, note='Mid ascent — mid-range terpene zone (~334°F myrcene region)'),
    Waypoint(time_s=65, temp_f=440, note='Endpoint — upper terpene zone + THC completion'),
]
WWZ_RUN2 = [
    Waypoint(time_s=0, temp_f=375, note='Session open'),
    Waypoint(time_s=15, temp_f=400, note='Faster mid climb'),
    Waypoint(time_s=30, temp_f=420, note='Endpoint — fast ramp, down 20°F from Run 1'),
    Waypoint(time_s=60, temp_f=420, note='Hold'),
]
WWZ_RUN3 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=15, temp_f=410, note='Steeper mid climb'),
    Waypoint(time_s=30, temp_f=430, note='Endpoint — fast ramp, up 10°F from Run 2'),
    Waypoint(time_s=50, temp_f=430, note='Hold'),
]
WWZ_RUN7 = [
    Waypoint(time_s=0, temp_f=380, note='Session open'),
    Waypoint(time_s=10, temp_f=400, note='Fast early climb'),
    Waypoint(time_s=20, temp_f=420, note='Endpoint — 420°F in 20s, 2°F/sec'),
    Waypoint(time_s=50, temp_f=420, note='Hold'),
]

# ── Runs (chronological; run numbers assigned positionally by the generator) ──
RUNS = [
    CompletedRun(
        strain='WW Z',
        run_date=date(2026, 5, 2),
        sessions_prior_today=0,
        utc_logged_at=None,
        waypoints=WWZ_RUN1,
        equipment=RIG_1,
        endpoint_note='<strong>Rate:</strong> ~0.6°F/sec',
        swab='Light golden/amber. Clean. No dark coloration.',
        extra_rows=[
            ('Vapor:', 'Spectacular. Full session expressed well across the arc.'),
            ('Verdict:', 'Clean on first run. Baseline curve well-matched to this material.'),
        ],
    ),
    CompletedRun(
        strain='WW Z',
        run_date=date(2026, 5, 18),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 5, 19, 2, 52, tzinfo=timezone.utc),
        waypoints=WWZ_RUN2,
        equipment=RIG_2,
        duration_seconds=60,
        endpoint_note='<strong>Endpoint:</strong> 420°F — fast ramp; down 20°F from Run 1',
        swab='Wheat — very clean.',
        dab_notes="Sneaky — felt light at first, enough that I finished the last 20 seconds of Sarah's dab when she didn't want it. But 5 minutes after that I was stoned as a bat. Having a hard time sitting up. Harsh in the throat in mine but interestingly not in finishing Sarah's. Maybe the harshness comes from the terpene mass up front? And not the heat? No real flavors coming through, Sarah says she hates the taste and is almost gagging. I don't find it tasty but I don't mind the taste.",
        analysis="Run 1 (spinner, 6mm pearl, slow ramp to 440°F) and Run 2 (Gemlock, no pearl, fast ramp to 420°F) differ on equipment, curve shape, and endpoint — no isolation is possible between them. Swab came back wheat-clean, lighter than Run 1's golden/amber, consistent with the Gemlock running lighter swabs across other strains. Strong delayed onset despite the lower endpoint — stoned as a bat ~5 minutes post-dab. Harshness was present in the full session; absent when finishing Sarah's last 20 seconds (tail end of her run). User hypothesis: harshness is front-loaded rather than endpoint-driven. The observation is real; the mechanism is speculative — a lighter partial load producing less irritation regardless of session position is equally consistent. Not a working position until something tests it. No distinct flavor; Sarah found the taste actively unpleasant.",
    ),
    CompletedRun(
        strain='WW Z',
        run_date=date(2026, 5, 19),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 5, 20, 1, 20, tzinfo=timezone.utc),
        waypoints=WWZ_RUN3,
        equipment=RIG_2,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 430°F — fast ramp (30s), 20s hold; up 10°F from Run 2',
        swab='One light golden with a small amber spot; the other barely absorbed anything — cleanest swab so far.',
        session_char='Harshness at 414°F on the display during the ramp, lingered through the hold at low intensity, never spiked — a couple of coughs. Creative, sharp, stoned.',
        intensity='Good — creative, sharp, and stoned. Not as hard as Run 2; less material consumed.',
        dab_notes="Two swabs: one light golden with a small spot of amber, the other barely absorbed anything — cleanest run I've ever seen swab-wise. Harshness hit at exactly 414°F on the app display. Lingered and increased over the dab but never increased fast — mild, just a cough or two. Good intensity, not as hard as last night but I didn't take the last third of a second hit. I feel creative and sharp, and also stoned. This feels a little bit like trying to run a distillation column in my throat and lungs.",
        analysis="Cleanest swab in the log for this strain — one light golden with a small amber spot, the other barely absorbed anything. No floor signal at 430°F. Harshness appeared at 414°F on the display during the ramp (somewhere in the 15s–30s window), lingered at low intensity through the hold, never spiked — a couple of coughs, not acute. This is a different profile from typical tail harshness: it started mid-climb rather than at the endpoint. User raised a methodological point this session — reported 'tail harshness' may be a threshold-crossing description rather than an endpoint-specific signal; harshness builds continuously and registers when it becomes noteworthy, not when the curve hits a particular temperature. Consistent with that framing, the harshness here was mild throughout and never became the story. Effect was good: creative, sharp, stoned — consistent with Z lineage. Less hard-hitting than Run 2 but user also took less material.",
    ),
    CompletedRun(
        strain='WW Z',
        run_date=date(2026, 5, 19),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 5, 20, 4, 48, 24, tzinfo=timezone.utc),
        waypoints=WWZ_RUN3,
        equipment=RIG_2,
        duration_seconds=60,
        endpoint_note='<strong>Endpoint:</strong> 430°F — repeated from Run 3',
        swab='Darker than Run 3 — maybe amber.',
        session_char='Harshness around 420°F on display (mid-ramp). Creative, sharp, stoned via body sensation.',
        intensity='Similar to Run 3',
        dab_notes="Harshness didn't show up until around 420 on display. I added 10 seconds with the button. But only needed maybe 5, it was cashed. Swabs were darker than last time, maybe to amber. In theory nothing different this time but really different results. Feels similar to last time, creative and sharp but definitely also stoned via body sensation.",
        analysis='Run 4 repeats the same curve as Run 3 (380→410@15s→430@30s, hold to 50s) with one procedural difference: push-button extension to 60s, with material cashed around 55s. Load was in the ballpark with Run 3 — same jar section, possibly slightly less — which rules out load size as an explanation for the swab shift. The amber swab points at the extension: ~5s of 430°F hold after the load was spent, not a signal about the curve itself. Harshness appeared at ~420°F on the display, up from 414°F in Run 3. Both are mid-ramp (15–30s window), neither at the endpoint hold. The 6°F shift is within run-to-run variability, consistent with the threshold-crossing framing: harshness builds through the ramp and is noticed when it crosses a perceivable level, not pinned to a specific temperature. Effect was consistent — creative, sharp, stoned with body sensation.',
    ),
    CompletedRun(
        strain='WW Z',
        run_date=date(2026, 5, 20),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 5, 21, 1, 40, tzinfo=timezone.utc),
        waypoints=WWZ_RUN3,
        equipment=RIG_2,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 430°F — same curve as Runs 3–4, no push-button extension',
        swab='Clean light golden.',
        session_char='A little coughing, no harshness.',
        intensity="Mild — smaller load (user's read).",
        dab_notes='It was great, a little coughing but no harshness. Clean light golden swabs. A little mild on effect, my guess is smaller load.',
        analysis="Same curve as Runs 3–4 (380→410@15s→430@30s, hold to 50s), no push-button extension. Swab clean light golden — consistent with the Gemlock pattern. No harshness this run; Runs 3 and 4 both had harshness appearing mid-ramp at 414–420°F on the display. The difference may be load size — smaller load, less vapor density, less irritation regardless of temperature — but user couldn't confirm load was meaningfully different, so this is a confound, not a finding. Coughing without harshness is worth the distinction: vapor volume can produce coughing without the hot/irritating quality of harshness. Effect mild, consistent with user's smaller-load read.",
    ),
    CompletedRun(
        strain='WW Z',
        run_date=date(2026, 5, 20),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 5, 21, 3, 2, tzinfo=timezone.utc),
        waypoints=WWZ_RUN3,
        equipment=RIG_2,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 430°F — same curve as Runs 3-5, deliberate full load',
        swab='Light golden — same as Run 5.',
        session_char='Tail harshness in the last part.',
        intensity='Strong — hit really hard.',
        dab_notes='Swabs looked the same as last time, light golden. This one was more normal load. Harshness in the last part, and hit really hard. So load size really influenced both.',
        analysis="Load-size hypothesis from Run 5 tested. Run 5 (smaller load, no harshness, mild effect) vs. Run 6 (fuller load, tail harshness, hard hit) on the same curve and equipment — the cleanest within-strain comparison in the log. Both harshness and effect strength scaled up with load. Swab stayed light golden, consistent with every Gemlock run on this strain. The curve produces harshness under a full load; the question is whether that's load-density-at-430°F specifically, or just load-density at any temperature.",
    ),
    CompletedRun(
        strain='WW Z',
        run_date=date(2026, 5, 21),
        sessions_prior_today=0,
        utc_logged_at=datetime(2026, 5, 21, 22, 16, tzinfo=timezone.utc),
        waypoints=WWZ_RUN7,
        equipment=RIG_2,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 420°F — fast ramp (20s, 2°F/sec); 30s hold',
        swab='Light golden — clean.',
        session_char='First half clean, no harshness; second half mild harshness, cough, throat irritation.',
        intensity='Hard but manageable — fastest onset on this strain.',
        dab_notes="First draw was about 20 seconds. No harshness, but not a ton of flavor either. That's been true across this strain. Got a little harsh in second half, mild cough, irritation in throat. Effect is nice fast, maybe fastest onset I've seen from this strain. Hard but still manageable. I'm not wiped out. Normal load.",
        analysis="Fast ramp (2°F/sec, 420°F in 20s) — most compressed climb in the WW Z dataset. First half clean; harshness returned in the second half during the hold, mild but present. Normal load. Endpoint dropped 10°F from Runs 3–6 and harshness still appeared — temperature alone didn't resolve it. Run 5 (small load, 430°F, no harshness) points at load size as a candidate, but it's one uncontrolled data point. Two competing mechanisms: smaller load → less dense vapor → less irritation; or smaller load → material spent sooner → less accumulated heat exposure after the load is done. Both are consistent with the data so far. Fastest onset of any WW Z run — concentrated delivery consistent with the lower endpoint.",
    ),
    CompletedRun(
        strain='WW Z',
        run_date=date(2026, 5, 21),
        sessions_prior_today=1,
        utc_logged_at=datetime(2026, 5, 22, 1, 28, tzinfo=timezone.utc),
        waypoints=WWZ_RUN7,
        equipment=RIG_1,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 420°F — fast ramp (20s, 2°F/sec); 30s hold &nbsp;|&nbsp; <strong>Equipment:</strong> First run back on Cloud Vortex 21.0 + 6mm pearl',
        swab='Light golden — same as Gemlock runs.',
        session_char='First 30 seconds smooth; second 20 seconds rising harshness — more harsh than Run 7.',
        intensity='Medium. Slow onset (mood factor possible — Gemlock broke this session). Duration: roughly 2.5–3 hours.',
        dab_notes='First 30 seconds smooth, second 20 rising harshness. More harsh than previous run. Swabs were light golden, same as with Gemlock. Seems to have slow onset, or maybe breaking the joystick was a buzzkill. Effect duration roughly 2.5–3 hours.',
        analysis="First run back on Cloud Vortex 21.0 + 6mm pearl after the Gemlock broke. Small load — one of three roughly equal chunks, imprecise split. Equipment change and load change happened simultaneously: the load-size experiment can't be isolated here. More harshness than Run 7 despite the smaller load — counterintuitive if load size is the driver, but the spinner reintroducing a pearl and different airflow dynamics is an equally plausible explanation. Swab returned light golden, same as every Gemlock run on this strain — doesn't obviously support the Gemlock-lighter-swab hypothesis, though the load difference is a confound there too. Onset slower than Run 7; user flagged broken joystick as a mood factor, which is real and uncontrollable.",
    ),
    CompletedRun(
        strain='WW Z',
        run_date=date(2026, 5, 21),
        sessions_prior_today=2,
        utc_logged_at=datetime(2026, 5, 22, 5, 58, tzinfo=timezone.utc),
        waypoints=WWZ_RUN7,
        equipment=RIG_1,
        duration_seconds=50,
        endpoint_note='<strong>Endpoint:</strong> 420°F — fast ramp (20s, 2°F/sec); 30s hold — same as Runs 7–8',
        swab='Clean light golden.',
        session_char='Harshness in the second half. Medium intensity, delayed onset.',
        intensity='Medium, delayed onset.',
        dab_notes='Clean light golden swabs, harshness in the second half. Medium intensity, delayed onset. Kind of a whimper of a last dab.',
        analysis="Run 9 repeats the same curve as Runs 7–8 (fast ramp to 420°F in 20s, hold to 50s) on the spinner config with a small load — the final chunk of the jar. Harshness returned in the second half, consistent with Run 8 (small load, spinner, same outcome). Two consecutive small-load runs on the spinner both produced harshness; Run 5 (small load, Gemlock) was clean on the same endpoint. This is the clearest equipment signal in the WW Z dataset: the spinner appears to contribute to harshness at 420°F in a way the Gemlock didn't. The endpoint itself remains a candidate — 420°F sits near the cross-strain harshness boundary and harshness appeared mid-ramp at 414–420°F on display in Runs 3–4 regardless of config. Medium intensity and delayed onset consistent with Run 8. Jar done at 9 runs.",
    ),
]

# ── Status ──
STATUS = StrainStatus(
    name='WW Z',
    profile_anchor='#wwz-profile',
    next_text='Jar done — 9 runs. If it shows up again: fast ramp to 420°F is a reasonable starting point',
    accent=None,
    slug='wwz',
    info=[
        ('Strain', 'WW Z (White Widow × Zkittlez lineage — inferred)'),
        ('Consistency', 'Cold cure'),
        ('Producer', 'Quasi Farms (Michigan)'),
        ('Nose', 'Piney with sweet undertone (weak secondary signal only)'),
    ],
    terpene_note='<strong>Terpene inference:</strong> Pinene inferred dominant — weakly supported by piney nose observation. Standard cannabis palette otherwise. See <a href="#terpene-ref">Terpene Reference</a>.',
    next_dab_notes='Run 9 (small load, spinner): clean light golden swab, harshness in second half, medium intensity, delayed onset. Kind of a whimper of a last dab. Jar done.',
    next_ai_analysis="Jar done. Equipment config is the more likely harshness driver — Runs 8–9 (small load, spinner) both produced harshness where Run 5 (same load class, Gemlock) was clean. The 420°F endpoint also sits near the harshness boundary regardless of config. If this strain shows up again, the fast ramp to 420°F (380→400@10s→420@20s, hold to 50s) is a reasonable starting point. Harshness on the spinner at that endpoint is a known risk — step down to 415°F if it persists, or test a joystick if one's available.",
    next_waypoints=None,
    jar_index='<div style=\'text-align:center;margin-top:1em;\'><strong>Runs on the jar:</strong> 9<br><strong>Runs that ended without harshness:</strong> 1<br><strong>Dabs taken by Sarah that were logged:</strong> 0<br><strong>Sarah\'s review of the flavor:</strong> "almost gagging"<br><strong>Temperature at which harshness first appeared mid-ramp, Run 3:</strong> 414°F<br><strong>Temperature at which harshness first appeared mid-ramp, Run 4:</strong> 420°F<br><strong>Variables cleanly isolated in the load-size experiment before equipment changed:</strong> 0<br><strong>Session on which the Gemlock joystick broke:</strong> the one right before the last two runs<br><strong>Description of the final dab:</strong> "kind of a whimper of a last dab"<br><strong>Fraction of the jar described as "spectacular vapor":</strong> 1 in 9</div>',
)
