from wisdom_core import *

ENTRY = WisdomEntry(
    key='dec-matrix-snapshots-frozen',
    kind='decision',
    claim="Evidence-matrix snapshots are frozen artifacts, not a second source of truth",
    guidance="Do not treat a matrix cell as citable without re-verifying its "
             "`jars/<slug>.py:<line>` anchor against the live file; do not maintain "
             "the snapshot as runs are logged — it's frozen by design, re-generated "
             "by a fresh audit.",
    evidence=[
        Citation(
            source='session:wisdom-audit-2026-07-11',
            role='context',
            provenance='ai-authored',
            gist="The July 11, 2026 audit committed a per-run evidence matrix under "
                 "`audit/matrix-<date>/`.",
            confounds="none noted",
        ),
    ],
    positions=[
        Position(
            stated='Session (wisdom audit, July 11, 2026)',
            text="Jar files remain the single source of truth; the matrix is a dated, "
                 "banner-stamped snapshot whose value is its provenance tags and "
                 "harshness-facet decomposition (the judgment layer that doesn't "
                 "cheaply regenerate). Its derivable layer "
                 "(dates/rigs/curves/order/raw text) is better served by the "
                 "backlogged run-facts dump script. Do not treat a matrix cell as "
                 "citable without re-verifying its `jars/<slug>.py:<line>` anchor "
                 "against the live file; do not maintain the snapshot as runs are "
                 "logged — it's frozen by design, re-generated by a fresh audit.",
        ),
    ],
    updated='Session (wisdom audit, July 11, 2026)',
)
